cmd-replay.c
doc/uftrace-live.md
doc/uftrace-record.md
doc/uftrace-replay.md
utils/filter.c
utils/filter.h
utils/utils.h

Since replay result is too long to read, it'd be better to provide a way to set color for specific functions.  This branch adds a new trigger 'color' to provide the way.

replay: Add 'color' trigger to highlight some functions

---

README.md

Please use correct English.
Signed-off-by: Jungsu Sohn <jsson98@gmail.com>

doc: Fix typo in README.md

---

cmd-record.c
uftrace.c
utils/debug.c
utils/utils.h

Hi, Namhyung :smile:
I send minor commits about color setting
- Add new enum color_setting
- Make setup_color function be more compact
Thanks,
Taeung

Minor refactoring about color setting

---

doc/uftrace-live.md
doc/uftrace-record.md

Hi @namhyung 😃 
Add 'DYNAMIC TRACING' description to `live` and `record` man pages.
(I referred to your commit log message https://github.com/namhyung/uftrace/commit/a65ecf3d7351ca9c971054e76bd5cc68b1bde59f)

doc: Update live and record man pages for dynamic tracing

---

libmcount/dynamic.c

Hi @namhyung 
It is a small PR.
Warning message if the function for 'dynamic tracing' `--patch` can't be found.
```
$ gcc -o hello.dyn -pg -mfentry -mnop-mcount hello.c
```
```
uftrace -P unknown_func ./hello.dyn 
hello
foo
bar
0.520 us [18603] | __monstartup();
0.314 us [18603] | __cxa_atexit();
0.685 us [18603] | puts();
0.186 us [18603] | puts();
0.084 us [18603] | puts();
```
When a given function (e.g. unknown_func) wasn't patched : `<func name> cannot be patched dynamically`
```
uftrace -P unknown_func ./hello.dyn 
unknown_func cannot be patched dynamically
hello
foo
bar
0.520 us [18603] | __monstartup();
0.314 us [18603] | __cxa_atexit();
0.685 us [18603] | puts();
0.186 us [18603] | puts();
0.084 us [18603] | puts();
```
When several functions weren't patched: `some functions …

mcount: Warn if the appointed function can't be found

---

.gitignore
Makefile
README.md
doc/uftrace-live.md
doc/uftrace-record.md
doc/uftrace-script.md
libmcount/mcount.c

This fixes some minor problems on script related commits.

Fix some minor issues on script

---

cmd-dump.c
cmd-graph.c
cmd-info.c
cmd-replay.c
cmd-report.c
cmd-script.c
doc/uftrace.md
tests/s-libfoo.cpp
tests/t131_lib_dlopen.py
tests/t168_lib_nested.py
uftrace.c
utils/data-file.c
utils/utils.c

Change log:
- add missing script command in uftrace man page
- make --nest-libcall imply --force
- allow to read data file inside uftrace.data like directory
- fix 131 lib_dlopen test
- fix some tests by properly removing old directory
- add a check routine for --record execution in script to remove coverity warning

Add various misc commits

---

doc/uftrace-record.md

There was some changes in uftrace-script.md so same changes have to be
applied to uftrace-record.md regarding script execution part.

doc: Fix to follow changes in uftrace-record

---

utils/kernel.c

Signed-off-by: Vincent LE GARREC <legarrec.vincent@gmail.com>

kernel: funciton-fork -> function-fork

---

cmd-record.c

Signed-off-by: Vincent LE GARREC <legarrec.vincent@gmail.com>

record: warn if FTRACE not enabled in kernel

---

configure

For portability, in particular I'm building on nixos.
Signed-off-by: Andrew Slough <andrew.slough@gmail.com>

build: Change configure shebang to /usr/bin/env bash

---

README.md

line 107
From `sudo uftrace -k hello`
To     `sudo uftrace -k tests/t-hello`
line 126
From `uftrace record -A fib@arg1 -R fib@retval fibonacci 5`
To     `uftrace record -A fib@arg1 -R fib@retval tests/t-fibonacci 5`
When I try to execute "From commands" it occurs error;No such executable file.

doc: Fix example command.

---

doc/uftrace-live.md

The man page of uftrace live is not still updated yet.  This fixes the
document just like uftrace record man page.

doc: Fix uftrace live man page

---

utils/session.c
utils/symbol.c

Hello @namhyung , I send this PR.
I solved issue #194 .
First, I added error handling for return values from fopen  in session.c.
Second, I changed fuctions from to pr_out in symbol.c.
Signed-off-by: Sangwon Hong <qpakzk@gmail.com>

Solve issue #194 .

---

doc/uftrace-live.md
doc/uftrace-replay.md
doc/uftrace.md

I'm so sorry..(Because i made a mistake (close my last `pull request`.....) 😥 )
So i send you this pull request again..
Thank you! (Thank you for letting me know about `uftrace` and understanding. 😊 )
Signed-off-by : JangSoJin <wkdthwls3@naver.com>

doc:Add more possible values

---

doc/uftrace-replay.md

I made some mistakes 😅..
Is it Ok? Thank you😅!!
Signed-off-by: yujeongKim <yjeong711@hanmail.net>

doc: Add example about time-range option

---

utils/utils.c

If uftrace.data.old directory contains
subdirectories, we can see the warning message
when recording a target program:
$ file uftrace.data.old/sub
uftrace.data.old/sub: directory
$ uftrace record hello
WARN: removing old directory failed: Is a directory
So let remove_directory() able to recursively delete
subdirectories.
Fixes #186.

utils: Recursively remove directory

---

doc/uftrace-recv.md

doc: add usage for `uftrace recv`

---

arch/i386/Makefile
arch/i386/cpuinfo.c
arch/i386/fentry.S
arch/i386/mcount-arch.h
arch/i386/mcount-dynamic.c
arch/i386/mcount-support.c
arch/i386/mcount.S
arch/i386/plthook.S
arch/i386/regs.c
cmd-record.c
tests/s-exp-int.c
tests/t043_full_demangle.py
tests/t058_arg_int.py
tests/t063_retval.py
tests/t065_arg_order.py
tests/t083_arg_float.py
tests/t084_arg_mixed.py
tests/t086_arg_stack.py
tests/t087_arg_variadic.py
utils/compiler.h
utils/symbol.c

This PR is for support i386 and contain test cases for that. 
note that, it is not support xray. 
because llvm does not support xray option for 32bit architecture yet. 
you can find information about this at below link. 
https://llvm.org/docs/XRay.html#xray-in-llvm

Support i386 with test

---

cmd-replay.c
utils/field.h

I forgot to change some comments, so fixed it in this patch.

field: Fix some minor comment changes

---

utils/fstack.c
utils/fstack.h

Extracting duplicated code of setup_task_filter()
and setup_task_handle(), create new prepare_task_handle()

fstack: Refactor setup_task_{filter,handle}

---

libmcount/mcount.c

To clean up `mcount_{entry,exit}_filter_record()` that
seems too big, make script processing code in them
new functions `script_hook_{entry,exit}()`.
I tested this PR like below:
```
$ ./runtest.py script
157 script_python       : OK OK OK OK OK OK OK OK OK OK
169 script_args         : OK OK OK OK OK OK OK OK OK OK
170 script_filter       : OK OK OK OK OK OK OK OK OK OK
171 script_option       : OK OK OK OK OK OK OK OK OK OK
```

record: Refactoring script functions of record time

---

cmd-dump.c
cmd-info.c
cmd-record.c
cmd-recv.c
libmcount/internal.h
libmcount/mcount.h
libmcount/record.c
utils/data-file.c
utils/debug.c
utils/kernel.c
utils/symbol.c
utils/symbol.h
utils/utils.c
utils/utils.h

Hi @namhyung ,
I missed this PR,
I'd appreciate it, if you check this.
v2:
- remove `#define PATH_MAX 4096` in uftrace.h
- rebased on current master

Refactoring the code regarding buffer and PATH_MAX

---

README.md

In PR #321 , I added `-h` option, but it wasn't updated in README.md. So I updated it.

doc: Add `-h` option to see commands and options

---

doc/uftrace-graph.md
doc/uftrace-info.md
doc/uftrace-record.md
doc/uftrace-report.md

doc: Add uftrace-tui to SEE ALSO in related commands

---

doc/uftrace.md

tui command is missing in uftrace man page so update it.

doc: Add missing tui command

---

INSTALL.md
configure

doc: Update INSTALL.md for missing libdw description

---

misc/ubuntu-install-deps.sh

This adds a convenient script to install dependent packages for ubuntu
system.  It installs all the required packages for uftrace.

misc: Add a script to install dependent packages

---

INSTALL.md

Related to #448.
Signed-off-by: Taeguk Kwon xornrbboy@gmail.com

doc: Mention installing 'pkg-config' in INSTALL.md

---

cmds/report.c

Hello.
I think, the if conditional statement in line 95 is useless.
The if conditional statement is always true.
So, Remove dead Conditional expression code.
Thanks.
problem code:
https://github.com/namhyung/uftrace/blob/4d4edc16c02e89e20ec3133339346bb308c64b7a/cmds/report.c#L92-L99

report: Remove dead code in insert_entry()

---

doc/uftrace-live.md
doc/uftrace-record.md

doc: Add -fxray-instrument description to --patch option

---

misc/bash-completion.sh
misc/install-elfutils.sh
misc/version.sh

Hello.
I modified the UUOC(useless use of cat) and typo.
Thanks.

script: Fix useless use of cat and typo

---

cmds/dump.c

It was missing to add base process name at the beginning of header so
this patch adds it.
{"traceEvents":[
{"ts":0,"ph":"M","pid":149779,"name":"process_name","args":{"name":"[149779] gcc-5"}},
{"ts":0,"ph":"M","pid":149779,"name":"thread_name","args":{"name":"[149779] gcc-5"}},
{"ts":0,"ph":"M","pid":149790,"name":"process_name","args":{"name":"[149790] cc1"}},
{"ts":0,"ph":"M","pid":149790,"name":"thread_name","args":{"name":"[149790] cc1"}},
{"ts":0,"ph":"M","pid":149791,"name":"process_name","args":{"name":"[149791] x86_64-linux-gn"}},
{"ts":0,"ph":"M","pid":149791,"name":"thread_name","args":{"name":"[149791] x86_64-linux-gn"}},
{"ts":0,"ph":"M","pid":149792,"name":"process_name","args":{"name":"[149792] collect2"}},
{"ts":0,"ph":"M","pid":149792,"name":"thread_name","args":{"name":"[ …

chrome: Add task names for each process

---

gdb/uftrace/plthook.py
misc/gen-autoargs.py

Hello,
I think, some variables are unused.
So, remove variables unused.
Thanks.

misc: Remove unused python variable

---

cmds/tui.c

Hello.
I think, the if conditional statement in line 2119, 2142 is useless.
The if conditional statement is always false.
So, Remove dead Conditional expression code.
Thanks.
problem code:
https://github.com/namhyung/uftrace/blob/9fe84ef0a89aba719054b3f7d9d5ec5669a9717b/cmds/tui.c#L2112-L2156

tui: Remove dead code

---

utils/symbol.c

Extracting duplicated code of find_map(), and create new check_map_symtab()
Fixed: #468

symbol: Refactor find_map()

---

cmds/report.c

report: Fix a typo in comment

---

arch/i386/mcount-dynamic.c

Fixed: #494
Signed-off-by: Leah Neukirchen <leah@vuxu.org>

mcount: Use renamed struct mcount_dynamic_info fields in i386 code

---

arch/i386/mcount-dynamic.c
arch/x86_64/mcount-dynamic.c

mcount: Fix Unchecked Return Value in mcount_setup_trampoline()

---

cmds/dump.c
doc/uftrace-dump.md
tests/t207_dump_graphviz.py
uftrace.c
uftrace.h
utils/utils.h

committed to support output format of dot.
associated with issue #355

Support output dot

---

cmds/script.c
doc/uftrace-live.md
doc/uftrace-record.md
doc/uftrace-script.md
doc/uftrace.html
libmcount/mcount.c
scripts/dump.py
scripts/info.py
utils/script-python.c
utils/script.h

This PR changes some keys of uftrace_begin(ctx) as follows:
- "recording" -> "record"
- "args"      -> "cmds"

Change keys in uftrace_begin(ctx)

---

misc/install-deps.sh

This commit allows installation script to be automated.
And allows passing the extra argument to the package manager.
Fixed: #531

Added extra argument for install-deps.sh

---

doc/uftrace.html

This PR contains some enhancements of slide document. It includes:
- Change foobar.c example so that it can better explain filter effect
- Show uftrace.data directory after record is done
- Fix some layout of a few animated slides
- Replace ubuntu dependent install to install-deps.sh
- Add dump.py link to its source code

slide: Enhance the slide document

---

utils/data-file.c
utils/fstack.c
utils/session.c

uftrace: Fix crash in uftrace

---

README.md

This PR updates one points in README.md
The commit remove the extra space in README.md.
Signed-off-by: Claudia J. Kang <claudiajkang@gmail.com>

doc: Enhance the documentation in README.md

---

misc/install-deps.sh

Hello.
I modified the UUOC(useless use of cat).
Thanks.

misc: Fix useless use of cat

---

misc/install-deps.sh

misc: Add support for Debian

---

doc/uftrace-live.md

This commit adds the caller-filter option in doc/uftrace-live.md
Signed-off-by: Claudia J. Kang <claudiajkang@gmail.com>

doc: Add caller-filter option

---

utils/auto-args.c
utils/fstack.c

uftrace : fix memory leak and Null Pointer Dereference

---

cmds/record.c
utils/symbol.c
utils/symbol.h

This PR does misc refactoring for a few function names.
- check_libpthread() to has_dependency()
- load_module_symbol() to load_module_symbol_file()
- save_module_symbol() to save_module_symbol_file()

Apply misc refactoring for a few function names

---

libmcount/record.c

it will ignore the previous map area if we continue when reach special
mapped area like [stack]. because typically the [stack] area that
specially mapped is end of memory space. therefore, modify codes of
record_proc_maps function to save the previous memory area to file when
reach special area.

record: write the previous memory area to file when reach special mapped area

---

Makefile
cmds/live.c
libmcount/mcount.c
uftrace.c
utils/debug.c
utils/pager.c
utils/utils.h

The pager in the busybox doesn't support color so disable it.
Fixed: #667
Signed-off-by: Namhyung Kim <namhyung@gmail.com>

utils: Check busybox environment for color

---

cmds/record.c

It was missing to send .dbg files when -H/--host option is used, so it
was fail to replay the received data.
This patch sends .dbg files to fix such problem.
Fixed: #677

record: Send .dbg files for -H/--host option

---

cmds/record.c
cmds/recv.c

It'd be helpful to send logfile as well as recorded trace data.

record: Send logfile for -H/--host option

---

cmds/replay.c

It didn't fully handle the char type dump when --chrome option is used.
The following dump output gets failed when loading it in chrome browser.
```
{...,"args":{"arguments":"('"')"}},
```
It's because the second argument '"' is misinterpreted as " is the
content, but it looks like a closing quotation mark.  The " character
should be escaped from '"' to '\"' as follows:
```
{...,"args":{"arguments":"('\"')"}},
```
This also handles \ character to be escaped because the following json
cannot be interpreted in chrome browser.
```
{...,"args":{"arguments":"(\"Next\:\")"}},
```
It becomes as follows:
```
{...,"args":{"arguments":"(\"Next\\:\")"}},
```
Fixed: #735

chrome: Fix a bug when displaying character type

---

utils/utils.c
utils/utils.h

This patch adds const qualifiers to some parameters that are not changed
inside the functions.

utils: Add const to unchanged char* parameters

---

doc/uftrace.html

slide: Add full dynamic tracing section

---

arch/i386/mcount-dynamic.c
check-deps/__have_libcapstone.c
utils/symbol.c

this PR have fix some bugs in i386.
include #762 #805.

Fix i386 bugs

---

doc/uftrace.html

Some names of tutorial are changed so it needs to be updated as well.

slide: Fix wiki pages to updated links

---

cmds/report.c
cmds/tui.c
libmcount/mcount.h
uftrace.c
uftrace.h
utils/utils.h

It's better to avoid hard coding for default values for some options.

uftrace: Stringify default values for some options

---

doc/ko/uftrace-dump.md
doc/uftrace-dump.md

Hi,
I translated man page of uftrace dump into Korean.
There might be awkward expressions in translation.
So if you have better translation, please let me know!
Also I'll leave a comment on the confusing part to translate. Please check it.
Thank you :)
Signed-off-by: Jeesoo Min <kuongee@gmail.com>

doc/ko: Translate man page of uftrace dump

---

misc/install-deps.sh

Add Manjaro, Alpine support to install-deps.sh

misc: Add Manjaro, Alpine support to install-deps.sh

---

doc/ko/uftrace-dump.md
doc/uftrace-dump.md

I found mistakes in my latest work.
I should have double checked.... :(
I'm really sorry about that.

doc: Fix --tid option description in uftrace-dump

---

cmds/record.c

Fixed `installtion` to `installation`

record: Fix typo in comment

---

doc/ko/uftrace-report.md
doc/uftrace-report.md

Hi, I'm just finished translation of report.md in Korean.
And I also changed --threads options to --task in both of doc/uftrace-report.md and doc/ko/uftrace-report.md
If there is any awkward translation, please leave me a comment.
Thanks:)
Signed-off-by: SeoYoung Kim gegirafe@gmail.com

doc: Translate uftrace-report.md

---

doc/ko/uftrace-recv.md

Hello,
I added my thoughts to the translation.
So, it can be different from English interpretation.
Thanks.

doc: Add Korean language translation for recv

---

cmds/replay.c

replay: Fix white space

---

doc/ko/README.md

This is a preparation for Korean translation for README.md.
The copied document is expected to be translated in Korean language.

doc/ko: Copy English README.md to doc/ko directory

---

utils/auto-args.c

utils: Fix memory leak in utils/auto-args.c

---

utils/data-file.c
utils/debug.c
utils/filter.c
utils/fstack.h
utils/kernel.c
utils/perf.h

uftrace: Fix white space

---

utils/fstack.c

live: Fix a memory leak in live replay

---

cmds/live.c

In some systems like a non-rooted android environment (termux)
You don't have a write access to /tmp directory

live: Use current directory when /tmp is failed

---

doc/ko/uftrace-info.md

Hi, I translated uftrace-info.md to Korean
Please let me know if there are any edits
Thank you
Signed-off-by: jungwoo <jungwoo5759@gmail.com>

doc/ko:Translate uftrace-info.md to Korean

---

misc/install-deps.sh

./misc/install-deps.sh: There is wrong tab size in the recently added line.
Signed-off-by: sangyun-han <sangyun628@gmail.com>

misc: Fix tab size in install-deps.sh

---

utils/dwarf.c

Signed-off-by: Joonho Ryu <ruujoon93@gmail.com>

dwarf: Fix white space

---

doc/ko/uftrace-replay.md
doc/uftrace-replay.md

Hi, I translated replay.md to Korean!
most of the content is same as live.md,
so I copied and pasted the common area.
If there's any updates are made in ko/live.md
I'll immediately update this one as well!
Thank you :)
Signed-off-by: Minchul Kang <tegongkang@gmail.com>

doc/ko: Translate replay.md to Korean

---

doc/ko/uftrace-script.md

Hi, I translated uftrace-script.md in Korean
If there is any awkward translation, please leave me a comment.
Thanks:)

doc/ko: Translate man page of uftrace script

---

doc/ko/uftrace-graph.md

안녕하세요.
공통옵션과 공통 분석 옵션은 dump 에 있는 내용 그대로 사용했습니다.
참고 부탁드립니다.

doc: Add Korean language translation for graph

---

misc/docker/arch/Dockerfile
misc/docker/centos/7/Dockerfile
misc/docker/ubuntu/16.04/Dockerfile
misc/docker/ubuntu/18.04/Dockerfile

misc: Modify dockerfiles to use -y option with install-deps.sh

---

README.md
doc/ko/README.md

This changes the links for dynamic tracing to their actual description
in README.md.

doc: Update dynamic tracing section link in README.md

---

utils/auto-args.c

Fix memory leaks in argspec
Fixed: #1053

utils: Fix memory leak in argspec

---

doc/ko/uftrace-graph.md
doc/uftrace.html

This PR includes the following changes.
- task graph example update in slide tutorial
- task graph manual update for Korean man page

doc: task graph manual update

---

configure
tests/t157_script_python.py
tests/t234_script_luajit.py
utils/script.c

This PR contains various script fixes including
- build: Fix `--without-libpython` for python3
- script: Show an warning if interpreter is not available
- tests: Fix script engine tests

various script fixes

---

doc/ko/uftrace-report.md
doc/uftrace-report.md

doc: Fix deprecated --threads option to --task

---

misc/install-deps.sh

misc: Add linuxmint to misc/install-deps.sh

---

cmds/dump.c

In some rust functions, the name contains " mark and it makes uftrace
dump --chrome output cannot be loaded in chrome browsers due to parse
errors.
This patch fixes the problem by escaping it in the function name.
Before:
```
{... ,"name":"_<extern "C" fn(A0) .> R as rusty_v8..support..CFnFrom<F>>::mapping::c_fn"},
```
After:
```
{... ,"name":"_<extern \"C\" fn(A0) .> R as rusty_v8..support..CFnFrom<F>>::mapping::c_fn"},
```

chrome: Fix rust function name that has " inside

---

doc/ko/uftrace-live.md
doc/ko/uftrace-record.md
doc/ko/uftrace-script.md
doc/uftrace-live.md
doc/uftrace-record.md
doc/uftrace-script.md
utils/script-luajit.c

script: Apply misc fix for luajit and script docs

---

tests/s-dwarf2.cpp

This commit amends test warning referred on issue #1250

test: Fixed warning on tests/s-dwarf2

---

arch/x86_64/mcount-dynamic.c

Fixes #1265.
See the commit message for more technical informations. In short, I believe that the `xray_instr_map` section may have changed a bit in how its content is referenced. I haven't look at any LLVM/clang code to confirm that.
Test 140 `dynamic_xray` should also pass now.
~~NOTE: this has not been tested for non-PIE executable. I can't get them to compile on my system, thus I can't test them.~~ It works for non-PIE executable also.

arch/x86_64: correctly compute xray instrumentation addresses

---

Makefile
arch/aarch64/mcount-support.c
arch/arm/mcount-support.c
arch/i386/mcount-support.c
arch/x86_64/mcount-event.c
arch/x86_64/mcount-support.c
cmds/dump.c
cmds/graph.c
cmds/info.c
cmds/record.c
cmds/replay.c
cmds/report.c
libmcount/mcount.c
libmcount/plthook.c
libmcount/record.c
utils/data-file.c
utils/debug.c
utils/demangle.c
utils/fstack.c
utils/hashmap.c
utils/regs.c
utils/session.c
utils/symbol.c
utils/utils.c
utils/utils.h

This PR adds some debugging features for easier debugging.
The details are written in the commit message.

utils: Add stacktrace and ASSERT, DASSERT

---

misc/docker/alpine/3.13/Dockerfile
misc/docker/alpine/3.14/Dockerfile
misc/docker/fedora/33/Dockerfile
misc/docker/fedora/34/Dockerfile

This commit adds additional Dockerfiles
which run uftrace in alpine and fedora linux

misc: Add Dockerfiles for alpine and fedora linux

---

misc/docker/alpine/3.13/Dockerfile
misc/docker/alpine/3.14/Dockerfile
misc/docker/arch/Dockerfile
misc/docker/centos/7/Dockerfile
misc/docker/fedora/33/Dockerfile
misc/docker/fedora/34/Dockerfile
misc/docker/ubuntu/16.04/Dockerfile
misc/docker/ubuntu/18.04/Dockerfile

This commit adds build arguments in Dockerfiles,
which enables tests for distributions.
With this commit, we can test uftrace in specific distros
like `docker build --build-arg test=yes .`.

misc: Add docker build argument for distribution tests

---

Makefile
NEWS

I'm preparing v0.11 release.  Please test it!

New release v0.11

---

Makefile
NEWS

Hello folks,
I'm preparing a new release.  Please help testing it, thanks!

New release v0.12

---

doc/uftrace.html

Fixes #1472
Signed-off-by: Sahil Siddiq <icegambit91@gmail.com>

doc: Fix tutorial slide (fixes #1472)

---

README.md
doc/ko/README.md

Add python version 3 in README.md

---

INSTALL.md
doc/uftrace-dump.md
doc/uftrace-graph.md
doc/uftrace-live.md

Correct grammatical errors and re-write some sentences to make it easier to understand.

doc: Improve English description

---

utils/kernel.c

Follow-up from https://github.com/namhyung/uftrace/pull/1481#pullrequestreview-1042865238 for `utils/kernel.c`

trivial: Remove duplicate #include

---

tests/runtest.py

Add an option to keep compiled binaries 
so that runtest.py do not remove test directory if using -k or --keep option
Fixed: #1469
Signed-off-by: Yusun Choi <tanks2438@outlook.kr>

test: Add -k, --keep option for compiled binaries

---

doc/uftrace-script.md

Signed-off-by: Seonghee Jin <seonghee@tsnlab.com>

doc: Fix a grammar error in a doc file

---

utils/graph.c

graph: Fix a minor spelling error caught by codespell

---

cmds/dump.c

When executing 'dump' command, uftrace prints 'file header'.
And it prints 'feature mask' and its bit name.
(e.g. "PLTHOOK", "KERNEL", ..)
Similarly, it prints 'info mask' value. So, I added simple logic
to print 'info' bit name too.(e.g. "EXE_NAME", "CMDLINE", ...)
Signed-off-by: DaeRo Lee <skseofh@naver.com>

dump: Add to print 'info' bit name

---

tests/.gitignore
tests/t207_dump_graphviz.py

Update 207 dump_graphviz expected test result.
Fixed: #1502

test: 207 update dump_graphviz test

---

tests/runtest.py

Disable multiprocessing pool explicitly with -j option
- Not including -j option will behave as before, even if the actual `arg.worker` value is set to 1 later
- Mode reflected in console message as `"with %d worker" -> "without worker pool"`
dotdict class (L849-L853) from https://stackoverflow.com/a/23689767
- To minimize code changes that access the `shared` dict
- Mentioning reference just in case of licensing complications
Addresses #1078 but did not solve the problem raised in that issue (#1063)
Signed-off-by: JongHyeon Hwang <jhh.20@icloud.com>

test: Support non-multiprocessing runtest.py

---

doc/ko/uftrace-report.md
doc/uftrace-report.md

update document for commit a926a9cfba9686367be923409a47a03cc13d5f93
Signed-off-by: Joonho Seo <tjwnsgh1110@gmail.com>

doc: Update document for new report field "size"

---

tests/runtest.py

Change default compiler to gcc and clang
so that if not using -c or --compiler option,
runtest.py use gcc and clang for default compiler
and display test result of using gcc and clang compiler.
Signed-off-by: Yusun Choi <tanks2438@outlook.kr>

test: Use both of gcc and clang by default

---

utils/utils.c

This is a fix for an issue found in #1509.
In the parse_timestamp function, when a string such as 8959832.082682731
was input as an argument value, there was a problem that it was not parsed
correctly in the number of decimal places.
```
$ make TESTARG="-v parse_times" unittest
TEST     test_unit
Running 1 test cases
======================
Testing parse_timestamp...
test failed at /home/user/uftrace/utils/utils.c:1121: time == tc[i].val
time             = 8959832000000000
tc[i].val        = 8959832082682731
[001] parse_timestamp               : FAIL
-------------
```
This was a parsing issue in the strtoull function caused by setting the base
to 0, and I solved the problem by specifying an explicit decimal base.
The parse_time function that uses strtoull was also changed.
Additionally, in …

utils: Fix the problem of handling numbers after the decimal point

---

tests/t207_dump_graphviz.py

Closes #1568
I fixed test failure by changing expected out put at dump_graphviz.py

Fix test failure in 207 dump_graphviz

---

cmds/dump.c
utils/kernel.c
utils/script.c

issue #1553 related Null dereference amend works.

utils: Null dereference amend

---

Makefile
NEWS

Hello,
I'm preparing a new release.  Please test! :)
It's a new release with the following highlights.  More information can be found in [NEWS](../blob/check/release/NEWS).  I wish spending more time on the agent changes on the next development cycle.
* -L/--loc-filter option using DWARF source location
* make -Z/--size-filter option as a general filter
* preparation for a background agent
* many test & CI infra updates

Release v0.13

---

arch/x86_64/mcount-dynamic.c

Recent gcc might enable -fcf-protection by default, it inserts a special instruction endbr64 at the beginning of each function.
If -fpatchable-function-entry is used together, the NOP instructions are inserted right after endbr64 instruction and it makes our expectation for NOP sled pattern fail as follows.
```
$ gcc -fpatchable-function-entry=5 -o t-abc s-abc.c
$ uftrace -P. --debug-domain dynamic:4 t-abc
dynamic: dynamic patch type: t-abc: 5 (fpatchable)
dynamic: skip non-applicable functions: a
dynamic: skip non-applicable functions: b
dynamic: skip non-applicable functions: c
dynamic: skip non-applicable functions: main
0.828 us [ 32089] | getpid();
```
To avoid the problem, this patch first checks whether the beginning instruction is 'endbr64' and skips it is matched, then it works …

dynamic: x86_64: Support endbr64 in NOP sled

---

README.md

Update the introduction to uftrace in README.md

README.md: Update the introduction to uftrace

---

arch/x86_64/mcount-insn.c

Since 'ret' instruction can be a target of another jump instruction, it is not safe to patch and move the instruction somewhere else.
For example, the following instruction pattern must not be patched because the branch target of 'jne' instruction at ef0af8 is the address of the 'ret' instruction at ef0ac8.
```asm
0000000000ef0ac0 <_ZN2v88internal4Heap20CreateFillerObjectAtEmiNS0_20ClearFreedMemoryModeE>:
ef0ac0:       f3 0f 1e fa             endbr64
ef0ac4:       85 d2                   test   %edx,%edx
ef0ac6:       75 08                   jne    ef0ad0 <_ZN2v88internal4Heap20CreateFillerObjectAtEmiNS0_20ClearFreedMemoryModeE+0x10>
ef0ac8:       c3                      ret
...
ef0af8:       75 ce                   jne    ef0ac8 …
```

dynamic: x86_64: Do not allow ret insn for patch target

---

arch/x86_64/mcount-insn.c

This PR fix build on x86_64 fix #1707

Fix #1707 x86 build 

---

doc/uftrace.html

Update explanation of configure.
Fixed: #1743

docs: uftrace slides update

---

doc/ko/CONTRIBUTING.md

CONTRIBUTING.md file is translated into Korean.
------------------------------------------------------
Few notices in this translation:
* Rather than a 1:1 translation between English and Korean, I focused on being as natural as possible when reading in Korean.
* Due to some of awkwardness, I used polite words in translation. 
Since other doc (.md) files were not translated using polite words, if you think this CONTRIBUTING.md file needs to be changed for a consistency with other documents, please let me know.

doc/ko: Update CONTRIBUTING.md in Korean

---

check-deps/Makefile

build: Add -mno-sse to fix i386 build

---

README.md

Add packaging status on the right side in README.md
ref)
https://repology.org/project/uftrace/versions
https://repology.org/badge/vertical-allrepos/uftrace.svg
Signed-off-by: Michelle Jin <shjy180909@gmail.com>
* Preview

doc: Add packaging status in README.md
