namhyung/uftrace

- Makefile
and not uftrace.c, because that symbol is only used in cmd-record.c. without this change, it looks like passing --libdir to configure has no effect.
> define INSTALL_LIB_PATH for cmd-record.c

- configure
build: switch to bash for configure script
/bin/sh means system default shell.
But it can be variable by linux distributions vendor or user flavor
IMHO, this patch provides better compatibility for various build environments
> build: switch to bash for configure script

- tests/runtest.py
uftrace correctly avoids spawning a pager when stdout is not a tty, and
runtest.py correctly runs uftrace connected to pipes, but (many? most?)
individual tests spawn uftrace themselves without connecting it to
any pipes.
thus, if you try to run runtests.py yourself in an interactive shell
with a tty, uftrace may try to spawn many many pagers in the course of
the test. and depending on your pager availability and configuration,
*each pager* might require interaction with the user before it will
quit.
you can, of course, use `runtests.py | cat` to avoid the whole pager
mess entirely, but this also has the effect of removing the coloring
from runtests.py output, which is extremely useful.
instead, this change adds `--no-pager` to every uftrace invocation under
tests.
> don't try to spawn pagers during test

- Makefile
- arch/arm/Makefile
- arch/x86_64/Makefile
Taken together, this will allow the Debian packaging to add the recommended hardening flags to the various pieces of the final result.
> Tweaks to build flags

- utils/fstack.c
When fstack.c file compiles using gcc version 4.5.2(Ubuntu/Linaro
4.5.2-8ubuntu4), uninitialized next_time variable causes warning
by calling __read_rstack function. So, init next_time variable
to 0 for removing warning.
Signed-off-by: Wangyong Choi <choiwangyong@gmail.com>
> fstack: Initialize next_time variable for removing warning

- libmcount/mcount.c
'recover' trigger assumes that return addresses in the current call
stack are replaced to mcount_exit by mcount_entry in binaries built with
'-pg' option.  So this patch simply disables 'recover' trigger in
cygprof_entry generated by '-finstrument-functions' option.
We may have to consider some cases when -pg and -finstrument-functions
are mixed in a single binary in the future.
> mcount: Disable 'recover' trigger in cygprof_entry

- libtraceevent/event-parse.c
- libtraceevent/kbuffer-parse.c
- libtraceevent/kbuffer.h
- libtraceevent/parse-filter.c
- libtraceevent/trace-seq.c
This removes below compiler warnings:
1. ignoring return value [-Wunused-result]
2. may be used uninitialized [-Wmaybe-uninitialized]
3. comparison between signed and unsigned integer expressions [-Wsign-compare]
4. signed and unsigned type in conditional expression [-Wsign-compare]
> Shutting off compiler warnings from libtraceevent

- cmd-graph.c
- cmd-replay.c
- cmd-report.c
- doc/uftrace-dump.md
- doc/uftrace-graph.md
- doc/uftrace-live.md
- doc/uftrace-replay.md
- doc/uftrace-report.md
This branch enables --kernel-only option not only for dump command but also for replay, report, and graph commands.
> Enable --kernel-only for replay, report, and graph

- cmd-record.c
Since some shared object files are executable, check_binary has to allow
it can be traced without --force option.
> record: Fix to handle shared object executable

- doc/uftrace-dump.md
- doc/uftrace-graph.md
- doc/uftrace-replay.md
- doc/uftrace-report.md
- utils/fstack.c
--tid option provides flexible usages such as the following ways:
$ uftrace replay --tid 1000,1004
or
$ uftrace replay --tid 1000 --tid 1004
But having --tid option more than twice does not work due to parsing
error so this patch fixes it and updates the man pages as well.
Suggested-by: Namhyung Kim <namhyung@gmail.com>
> uftrace: Fix --tid option usage

- tests/t129_session_tid.py
- utils/data-file.c
Prevents issue #40 from happening in the future, where a task does not have
a session because the session is identified by tid instead of pid.
> session: Save sessions per pid instead of tid v2

- cmd-dump.c
chrome://tracing support nanoseconds.
> Dump: Adding nanoseconds precision for "ts" field in Trace Event Format output

- utils/debug.c
- utils/utils.h
Currently not only __pr_err but also __pr_warn
use red color. So I suggest changing to yellow color.
And I think it is better to add a prefix "WARN:" such as pr_err
> ftrace: Change warning msg color from red to yellow

- check-deps/Makefile
- configure
The current 'make clean' does not clean up the timestamp files that are
generated during 'configure' executed to prevent the permission problems
such as the following example.
$ sudo ./configure
$ ./configure --prefix=$HOME/usr
touch: cannot touch 'check-tstamp': Permission denied
$ sudo make clean
...
$ ./configure --prefix=$HOME/usr
touch: cannot touch 'check-tstamp': Permission denied
> build: Fix a permission problem in configure

- cmd-info.c
- utils/data-file.c
Even though a task file is missing, uftrace info
should work regardless of it.
> info: Skip a case of missing task file

- uftrace.c
The user can check a time-range usage with help message as below
$ uftrace --help | grep time-range
-r, --time-range=TIME~TIME Show output within the TIME range only
But I think the user can be confusing
because they can't know what does TIME mean
e.g. duration, timestamp, elapsed time etc.
Sure, `uftrace replay` man pages contain this
but I think it is better that there is the mention
not only in man page but also help message.
So I modify the help message for time-range.
> uftrace: Supplement help message for a time-range option

- cmd-record.c
cmd-record.c: In function ‘copy_to_buffer’:
cmd-record.c:555:3: warning: ignoring return value of ‘write’,
declared with attribute warn_unused_result [-Wunused-result]
write(thread_ctl[1], &kick, sizeof(kick));
^
> record: Fix a compiler warning

- tests/t122_time_range2.py
- uftrace.c
- utils/utils.h
We can use --time-filter or -t option
to filter functions by time as below.
$ uftrace -t 1us ./a.out
But currently we can't use a float value for the threshold
because uftrace only handle the value as uint64_t type.
So fix codes to enable the user to use a float value for it e.g.
$ uftrace -t 0.3us ./a.out
> record: Allow a float value for time filter

- libmcount/mcount.c
- utils/data-file.c
- utils/symbol.c
- utils/symbol.h
Hi @namhyung 
This is PR for #56.
I ran the record and replay command on both of arm32 and x86_64 using same data file from arm32.
**get uftrace.data on arm32**
| VMSPLIT   |      ARM      |  x86_64 |
|:----------:|:-----:|:-----:|
| 1G |  OK | OK |
| 2G |  OK | OK |
| 3G | OK | OK |
| 3GOPT | OK | OK |
**get uftrace.data on x86_64**
| VMSPLIT   |      ARM      |  x86_64 |
|:----------:|:-----:|:-----:|
| FIXED | ERR | OK |
> symbol: Fix a symbol-finding bug on ARM

- utils/symbol.c
Hi, @namhyung,
This is small PR to fix a reading 64-bit address from kallsyms on 32-bit systems.
Basically, uftrace allows that replay can be run on any architceture.
So, we can execute the `uftrace replay --kernel` on x86_64 machine 
from uftrace.data which was stored at 32-bit ARM architecture, and 
it works well. By the way, In the opposite case, the result as follows:
```
$ uftrace replay --kernel
DURATION    TID     FUNCTION
1.074 us   [20819] | __monstartup();
0.774 us   [20819] | __cxa_atexit();
[20819] | main() {
[20819] |   printf() {
[20819] |     <ffff811effb0>() {
0.947 us   [20819] |       <ffff81019d20>();
5.223 us   [20819] |     } /* <ffff811effb0> */
3.599 us   [20819] |     <ffff8101a430>();
4.112 us   [20819] |     <ffff81064010>();
1.111 us   [20819] | …
```
> symbol: Fix a reading 64-bit address from kallsyms on 32-bit systems

- cmd-replay.c
- uftrace.c
- uftrace.h
Hi Namhyung :smile: 
This is small PR mentioned at #66 
Additionally I used `enum replay_field_id` instead of just integer values
for **index of field_table array** in order to better readability.
> Display timestamp or elapsed time by default when using time-range

- cmd-dump.c
- libmcount/mcount.c
Hi @namhyung 
I found little things that can be refactored with the macro `NSEC_PER_SEC` 100000000
on my way that I've been looking over recent your commits. 😄
> dump, mcount: Use a macro NSEC_PER_SEC instead of just integer 1000000000

- utils/demangle.c
It doesn't seem to be necessary to skip '_GLOBAL__sub_I_' prefix from the
given symbol.  Some of users got confused by that as if main() function
is called twice just like the stackoverflow question.
This patch removes the '_GLOBAL__sub_I_' prefix and the result is as
follows:
$ uftrace ./a.out
A is created
A is destroyed
0.744 us [121820] | __cxa_atexit();
[121820] | _GLOBAL__sub_I_main() {
[121820] |   __static_initialization_and_destruction_0() {
57.113 us [121820] |     std::ios_base::Init::Init();
0.115 us [121820] |     __cxa_atexit();
57.961 us [121820] |   } /* __static_initialization_and_destruction_0 */
58.110 us [121820] | } /* _GLOBAL__sub_I_main */
[121820] | main() {
[121820] |   A::A() {
6.913 us [121820] |     std::operator <<();
4.977 us [121820] | …
> demangle: Keep _GLOBAL__sub_I_ prefix in symbols

- doc/uftrace-live.md
- doc/uftrace-record.md
Currently uftrace supports the dynamic tracing feature 'X-ray'
of Clang/LLVM 4.0 so add examples for it to live and record man pages.
I referred to your mention on #88 😄 
If you give me some feedback, I'll update this PR.
> doc: Add examples for X-ray dynamic tracing to live and record man pages

- tests/t097_dump_basic.py
- tests/t098_dump_tid.py
- tests/t099_dump_filter.py
- tests/t100_dump_depth.py
Hi @namhyung ,
I fixed several dump test scripts.
* Correctly check architecture (64 bit or 32 bit) in fixup()
* Use fixup() when the target program don't contain `build-id`
I found the problem when using GCC 7 (no default `build-id` option) as below.
(GCC 5 and 6 haven't this problem)
```
$ gcc -dumpversion
7.0.1
$ ./runtest.py dump
097 dump_basic          : NG NG NG NG NG NG NG NG NG NG
098 dump_tid            : NG NG NG NG NG NG NG NG NG NG
099 dump_filter         : NG NG NG NG NG NG NG NG NG NG
100 dump_depth          : NG NG NG NG NG NG NG NG NG NG
...
```
Detailedly
```
$ ./runtest.py -d dump
------------------------: …
```
> Fix dump test scripts

- libtraceevent/event-parse.c
- libtraceevent/parse-filter.c
- utils/utils.c
gcc 7 has added a default warning about fallthrough unlike gcc 6:
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
So add the fallthrough comments into the switch statements
that are cause of the below warning. This commit handles #89
```
/home/taeung/git/uftrace/utils/utils.c: In function ‘parse_min’:
/home/taeung/git/uftrace/utils/utils.c:288:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
decimal *= 10;
~~~~~~~~^~~~~
/home/taeung/git/uftrace/utils/utils.c:289:3: note: here
case 3:
^~~~
CC       arch/x86_64/cpuinfo.o
CC       arch/x86_64/regs.o
LINK     arch/x86_64/uftrace.o
FLAGS:   * new build flags or cross compiler
CC FPIC  libtraceevent/event-parse.o
/home/taeung/git/uftrace/libtraceevent/event-parse.c: In function ‘process_arg_token’: …
```
> Add the fallthrough comments to avoid the warning of gcc 7

- configure
Hello,
Someone's trying to introduce `uftrace` on Fedora [1] and I'd like to see this move forward. One problem is that the configure script doesn't meet packaging expectations, which is fixed in 77dcd9c ca9d704. That should make downstream maintainers lives easier since they'd less likely need to manually update the packaging whenever a guideline changes.
I also polished the script a bit.
Dridi
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1398922
> Make the configure script more packaging-friendly

- libmcount/mcount.c
I found this situation with GDB.
Currently mcount_init() is first called before __monstartup(),
so check mcount_setup_done in __monstartup(), not mcount_init(),
to not call mcount_startup() twice.
Fixes: cb38d982 ("mcount: Staticize startup and cleanup routines")
Or,
check the `mcount_setup_done` variable on both ?
> mcount: Only call mcount_startup() one time

- arch/x86_64/fentry.S
- arch/x86_64/mcount.S
Hi @namhyung , 😄 
I fixed comments about stack frame (with -pg, -mfentry)
based on your mention yesterday. 😄 
I'd appreciate some feedback on this PR!
Thanks,
Taeung
> arch/x86: Fix comments about stack frame with -pg / -mfentry

- cmd-dump.c
- cmd-replay.c
- doc/uftrace-record.md
- libmcount/record.c
- tests/s-std-string.cpp
- tests/t146_std_string.py
- utils/filter.c
- utils/filter.h
- utils/fstack.c
Since std::string is widely used in C++ programs, so it'd be useful to support it when displaying arguments and return values.
Currently, it only supports std::string in libstdc++ library.
> std::string support for argument/retval display

- tests/runtest.py
It's easier to compare the 'result' and 'expected' in runtest.py output
when they are placed closely.
With this change, the 'result' and 'expected' are placed very closely so
they can be easily compared.
> test: Reorder 'expected' and 'result' in verbose mode

- cmd-recv.c
- uftrace.c
- uftrace.h
- utils/utils.c
- utils/utils.h
Hi, @namhyung.
I hope to add a feature to execute command when uftrace data received.
With this, user can see the output of their own script to analysis something immediately the trace ends.
Originally, I hope to create some remote interface that start/end the trace and do something after the trace.
It may be a first step to reach that.
> Add a method to trigger some command line when trace data received (during uftrace recv)

- utils/utils.c
[Error]
error: 'PATH_MAX' undeclared (first use in this function); did you mean
'INT8_MAX'?
Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>
> utils: Add limits header to fix build error

- Makefile
To use build with musl, need to argp library.
So need to add LDFLAGS from outside.
Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>
> Makefile: Add LDFLAGS in export

- arch/x86_64/mcount-dynamic.c
Hi @namhyung ,
I came up with little refactoring patches while reading the code for dynamic tracing.
If you give me some feedback, I'd appreciate it. 😄 
Additionally what do you think about renaming "target_addr" to "jump_offset" ? like below.
```
diff --git a/arch/x86_64/mcount-dynamic.c b/arch/x86_64/mcount-dynamic.c
index 2b660c7..771c789 100644
--- a/arch/x86_64/mcount-dynamic.c
+++ b/arch/x86_64/mcount-dynamic.c
@@ -150,7 +150,7 @@ out:
#define NOP_INSN_SIZE 5
-static unsigned long get_target_addr(struct mcount_dynamic_info *mdi, unsigned long addr)
+static unsigned long get_jump_offset(struct mcount_dynamic_info *mdi, unsigned long addr)
{
while (mdi) {
if (mdi->addr <= addr && addr < mdi->addr + mdi->size)
@@ -165,7 +165,7 @@ static int patch_fentry_func(struct mcount_dynamic_info …
```
> dynamic tracing: small refactoring

- arch/x86_64/mcount.S
Hi @namhyung , 😄 
The commit 854abed ("Fix filtering on x86_64") subtracts
the offset from the start of child function which is 9 bytes
(1 for push; 3 for mov; 5 for call). But we don't need to do it anymore,
because match_ip() checks an address between the start address
of function to be filtered and it's the end address.
Furthermore, the calculation adjusting the offset is not perfect.
For examples, if the child address is 0x400693 on hello(),
```
Dump of assembler code for function hello:
0x400686 <+0>:	push   %rbp
0x400687 <+1>:	mov    %rsp,%rbp
0x40068a <+4>:	sub    $0x10,%rsp
0x40068e <+8>:	callq  0x400520 <mcount@plt>
child addr => 0x400693 <+13>:
```
We can get 0x40068a(i.e 0x400693 - 0x9), not 0x400686 (i.e. correct hello()
function address) by this calculation.
So remove it. …
> arch/x86: remove needless adjustment the offset for child func addr

- Makefile
It'd be useful if 'make tags' can generate ctags file for useful source
files excluding tests and check-deps.
> build: Add 'make ctags' rule for ctags

- Makefile
- check-deps/Makefile
- check-deps/Makefile.check
- check-deps/__have_libpython2.7.c
- cmd-record.c
- cmd-script.c
- doc/Makefile
- doc/uftrace-live.md
- doc/uftrace-record.md
- doc/uftrace-script.md
- libmcount/mcount.c
- libmcount/plthook.c
- misc/bash-completion.sh
- scripts/count.py
- scripts/replay.py
- scripts/simple.py
- tests/t157_script_python.py
- uftrace.c
- uftrace.h
- utils/script-python.c
- utils/script-python.h
- utils/script.c
- utils/script.h
- utils/utils.c
- utils/utils.h
This PR supports python binding for C/C++ function entry and exit so that one can easily add a python script to hook function entry and exit and do whatever they want.
It includes `-S` / `--script` option for running a given script in record time and also includes `script` command to process with a given script for recorded data.
As an example, if `simple.py` script is written as follows:
```
def uftrace_entry(args):
_symname = args["symname"]
print("entry : " + _symname + "()")
def uftrace_exit(args):
_symname = args["symname"]
print("exit  : " + _symname + "()")
```
The `record` or `live` shows the following output in record time:
```
$ uftrace -S scripts/simple.py -F main tests/t-abc
entry : main()
entry : a()
entry : b()
entry : c()
entry : getpid()
exit  : getpid()
exit  : c()
exit …
```
> Support python script for function entry and exit

- libmcount/mcount.c
- libmcount/mcount.h
- libmcount/record.c
- uftrace.h
- utils/filter.h
Since /proc/[pid]/statm prints the number of pages for each field, it'd
be better to keep the memory size in KB.
> mcount: Fix the size in proc statm event

- cmd-recv.c
It sometimes happens that (htonl(a) + htonl(b)) == htonl(a + b), but
sometimes (usually?) those are quite different.
This fixes t142_recv_multi.py so that it doesn't leave hung daemon
uftrace instances lying around when the memory maps file is of certain
sizes that happen to exercise this htonl bug.
> Fix calc of message sizes in send_trace_metadata

- tests/unittest.h
Hi Namhyung,
I attended to your uftrace seminar today and got impressed so much.  During the time, I found two trivial nitpicks by coincidence.  So, here's the patches.
Thanks,
SeongJae Park
> Test trivial fix

- utils/debug.c
When __print_time_unit() is called from print_diff_time_unit(),
an absolute value of delta_nsec is needed.
But it isn't needed at the print_time_unit() case,
so fix it.
Fixes #133.
Fixes: adf2763 ("report: Allow diff output as numbers")
Reported-by: @suapapa Homin Lee <homin.lee@suapapa.net>
> replay: Fix a bug using abs() discarding upper 32-bit

- tests/s-alloca.c
- tests/s-openclose.c
- tests/t016_alloca.py
- tests/t079_replay_kernel_D.py
- tests/t080_replay_kernel_D2.py
- tests/t081_kernel_depth.py
- tests/t132_trigger_kernel.py
- tests/t138_kernel_dynamic.py
- tests/t139_kernel_dynamic2.py
- tests/t143_recv_kernel.py
- tests/t161_pltbind_now.py
- tests/t162_pltbind_now_pie.py
Since older gcc such as gcc-4.xx and gcc-5.xx have a bug in
-finstrument-functions, some of tests are failed.
The problem is that gcc sometimes put '__cyg_profile_func_enter' and
'__cyg_profile_func_exit' for some library calls, which is not expected.
For example, the below example shows unexpected additional open call.
```
$ gcc -finstrument-functions -O2 s-openclose.c
$ uftrace a.out
[18948] | main() {
[18948] |   open() {
7.493 us [18948] |     open();
19.570 us [18948] |   } /* open */
4.143 us [18948] |   close();
25.447 us [18948] | } /* main */
```
Unlike this, clang doesn't have such problem for the same example.
```
$ clang -finstrument-functions -O2 s-openclose.c
$ uftrace a.out
[18980] | main() {
13.103 us [18980] |   open();
4.433 us [18980] |   close();
31.157 us [18980] | } …
```
> test: Avoid -finstrument-functions bug in gcc

- cmd-dump.c
- cmd-graph.c
- cmd-info.c
- cmd-replay.c
- cmd-report.c
- cmd-script.c
- utils/data-file.c
Currently if there isn't uftrace.data/info file,
print the error message with `pr_dbg()`.
But use `pr_err()` to let users know the error case, though
no using a debug -v option.
Fixes #127.
If you don't want to use `pr_err()`,
what about like below ?
```
diff --git a/cmd-info.c b/cmd-info.c
index 844ddfe..8d64fde 100644
--- a/cmd-info.c
+++ b/cmd-info.c
@@ -774,7 +774,10 @@ int command_info(int argc, char *argv[], struct opts *opts)
struct ftrace_file_handle handle;
const char *fmt = "# %-20s: %s\n";
-        open_data_file(opts, &handle);
+        if (open_data_file(opts, &handle) < 0) {
+                pr_warn("no trace data found\n");
+                return -1;
+        }
snprintf(buf, sizeof(buf), "%s/info", opts->dirname);
```
> uftrace: Show the error message when info file can't be found

- uftrace.c
--nop option is for performance testing so doesn't require to use pager
so it's better to disable it.
> uftrace: Disable pager when using --nop option

- cmd-info.c
- cmd-record.c
- uftrace.h
Currently we get a record date from the info file's mtime.
But it isn't reliable because it can be changed anytime.
So implement a new info item 'record_date' that will be
saved at the time of recording.
Note:
- Rename `recorded date` to `record date`
- Save a `record date` when tracing was stopped.
Or, record the `record date` immediately after `start_tracing()` ?
- Save a `record date` as just a date string, not a timestamp value (i.e. `time_t`)
I'd appreciate some feedback on this. 😄
> info: Add a info item 'record_date' to uftrace_info_bits

- utils/script-python.c
Since sys.path is not properly set before, there was some import errors.
This patch first gets the correct sys.path by running python
interpreter, then generate .py_sys_path.def file so that it can be
included by utils/script-python.c.
This also adds RTLD_GLOBAL flag to dlopen to complete the symbol
resolution of subsequently loaded shared objects.
Now, it's ready to use matplotlib and numpy in uftrace python script.
> python: Fix to import matplotlib and numpy

- README.md
- doc/uftrace-info.md
Hi @namhyung 
I send this patch because of a bit renewed info output with `elapsed time`.
But I didn't want to change all info output due to changed one thing,
so I just inserted one line with a elapsed time value from trace data recorded
with `t-abc` of tests/s-abc.c in my case.
What do you think about that ?
> doc: Add a item 'elapsed time'

- uftrace.h
struct uftrace_record has a member 'addr'.
It can mean child ip or uftrace_event_id,
so add this comment.
> record: Add a comment for 'addr' of uftrace_record

- cmd-record.c
- cmd-script.c
- doc/uftrace-script.md
- uftrace.c
- uftrace.h
It'd be better to have an option to record a new trace before running a
given script.  This patch adds --record option to do it in script
command.
> script: Add a new --record option

- cmd-info.c
Even though there is uftrace.data/`<exename>`.sym,
if the executable file is removed,
uftrace --symbols shows nothing like below, so fix it.
```
$ uftrace record tests/t-abc
$ rm tests/t-abc
$ uftrace info --symbols
Normal symbols
==============
Dynamic symbols
===============
```
Fixes #175.
> info: Fix --symbols problem in no executable file case

- cmd-replay.c
- tests/t146_arg_std_string.py
std::string can be directly represented with operator""s in C++14.
So it'd be better to display std::string in C++14 style.
> replay: Add 's' postfix to std::string

- tests/runtest.py
runtest.py uses exec() inside and it accepts a dictionary contains local
variables.  But it makes a problem when tracing it using settrace(),
which is used in trace.py as follows:
```
$ cd tests
$ python runtest.py 136
(... runs without a problem ...)
$ python -mtrace --trace runtest.py 136
...
runtest.py(414):     tc = _locals['tc']
--- modulename: trace, funcname: _unsettrace
trace.py(80):         sys.settrace(None)
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/usr/lib/python2.7/trace.py", line 819, in <module>
main()
File "/usr/lib/python2.7/trace.py", line 807, in main
t.runctx(code, globs, globs)
File …
```
> test: Fix runtest.py to be able to run with -mtrace

- arch/x86_64/mcount.S
The commit 666bdf3 ("mcount: Hijack the return address
in mcount_entry()") already eliminate the code hijacking
return addr based on a return value of mcount_entry()
But a 'cmpq' instruction that seems needless
still remains. So, remove it.
> mcount: Remove a residue 'cmpq' after mcount_entry()

- cmd-info.c
Claudiu Balogh reported that uftrace cannot read data that has more than
1000 threads.  It's because the current implementation stores the
task list in a fixed size buffer (4096).
So this patch makes the buffer to be allocated dynamically to make it
work for any size of task list.
> info: Use dynamically allocated buffer for cmd-info.c

- README.md
- cmd-graph.c
- doc/uftrace-graph.md
- tests/runtest.py
- tests/t069_graph.py
- tests/t070_graph_backtrace.py
- tests/t071_graph_depth.py
- tests/t088_graph_session.py
- tests/t089_graph_exit.py
- tests/t095_graph_tid.py
- tests/t096_graph_filter.py
- tests/t104_graph_kernel.py
- tests/t108_graph_time.py
- tests/t165_graph_sched.py
Since the header of graph output was very long, it'd be better to make
it simpler so that it can be shown as a compact form.
Before:
\#
\# function graph for 'main' (session: a4016e70192f5080)
\#
backtrace
\=====================================
backtrace #0: hit 1, time  13.013 us
[0] main (0x400cc9)
calling functions
\=====================================
13.013 us : (1) main
...
After:
\# Function Call Graph for 'main' (session: a4016e70192f5080)
\=============== BACKTRACE ===============
backtrace #0: hit 1, time  13.013 us
[0] main (0x400cc9)
\========== FUNCTION CALL GRAPH ==========
13.013 us : (1) main
> graph: Make graph output header simpler

- doc/uftrace-live.md
- doc/uftrace-record.md
This PR updates argspec in uftrace live man page and also update the man
page for newly added function pointer type in argspec.
> doc: Update man pages for funcptr arg type and live command

- doc/uftrace-script.md
Hi, I think there is a typo in the script example.
line 58
Before
~~~
$ uftrace record -F main tests/t-abc
$ uftrace scripts -S scripts/simple.py
program begins...
entry : main()
entry : a()
entry : b()
entry : c()
entry : getpid()
exit  : getpid()
exit  : c()
exit  : b()
exit  : a()
exit  : main()
program is finished
~~~
After
~~~
$ uftrace record -F main tests/t-abc
$ uftrace script -S scripts/simple.py
program begins...
entry : main()
entry : a()
entry : b()
entry : c()
entry : getpid()
exit  : getpid()
exit  : c()
exit  : b()
exit  : a()
exit  : main()
program is finished
~~~
Thank you! :)
Signed-off-by: JangSoJin <wkdthwls3@naver.com>
> doc:Fix script example command

- doc/uftrace-live.md
Sorry, but I found the wrong command. 
I think `-pg` option is missing by mistake. 
When i try to execute it(`uftrace ./abc`), I found out error message.(`It seems not to be compiled with -pg......`)
line 101
Before
~~~
$ cat abc.c
void c(void) {
/* do nothing */
}
void b(void) {
c();
}
void a(void) {
b();
}
int main(void) {
a();
return 0;
}
$ gcc -o abc abc.c
~~~
After
~~~
$ cat abc.c
void c(void) {
/* do nothing */
}
void b(void) {
c();
}
void a(void) {
b();
}
int main(void) {
a();
return 0;
}
$ gcc -pg -o abc abc.c
~~~
That's it, Thanks! :) 
Signed-off-by: JangSoJin <wkdthwls3@naver.com>
> doc:Fix -pg command

- doc/uftrace-live.md
- doc/uftrace-record.md
Since --nest-libcall implies --force, it updates record and live man
pages.  It also updates record man pages that --kernel-buffer implies
--kernel as well.
> doc: Add missing imply rules in man pages.

- tests/s-alloca.c
- tests/s-fork.c
- tests/s-fork2.c
- tests/s-malloc-fork.c
- tests/s-ucontext.c
I think, maybe some users will be confused by the `warning message(implicit function declaration)` below during compilation for test.  
https://github.com/namhyung/uftrace/commit/04491ff880bd6592daca9be8d7397668bf848119  
```
$ gcc -o t-alloca -pg s-alloca.c  
s-alloca.c: In function ‘foo’:  
s-alloca.c:8:2: warning: implicit declaration of function ‘strncpy’ [-Wimplicit-function-declaration]  
strncpy(ptr, "hello world\n", c);  
^  
```
https://github.com/namhyung/uftrace/commit/b1024b6905404b8709e0819f0f72f378d436c232
```
$ gcc -o t-fork -pg s-fork.c  
s-fork.c: In function ‘main’:  
s-fork.c:37:3: warning: implicit declaration of function ‘wait’ [-Wimplicit-function-declaration]  
wait(NULL);  
^  
$ gcc -o t-fork2 -pg s-fork2.c  
s-fork2.c: In function ‘main’:  
s-fork2.c:11:3: …
```
> test: Add explicit function declaration.

- doc/uftrace-replay.md
backtrace trigger is not working with `-F` any more.
So it should be replaced by `-T` option.
Before
~~~
$ uftrace replay -F 'b@backtrace,depth=2'
~~~
After
~~~
$ uftrace replay -T 'b@filter,backtrace,depth=2'
~~~
Thanks !! :)
Signed-off-by: JangSoJin <wkdthwls3@naver.com>
> doc:Fix example command

- libmcount/mcount.c
- scripts/replay.py
- utils/script-python.c
- utils/script.c
- utils/script.h
Sometimes, when fork is called in the target program, python output is printed twice because its buffer is not flushed when creating a new process.
This PR makes python interpreter flush its internal buffer to avoid the problem by calling "sys.stdout.flush()".
```
Before:
$ uftrace -S scripts/replay.py tests/t-fork
[15120] | main() {
[15120] |   fork() {
590.585 us [15132] |   } /* fork */
[15132] |   a() {
[15132] |     b() {
[15132] |       c() {
[15132] |         getpid() {
9.400 us [15132] |         } /* getpid */
39.670 us [15132] |       } /* c */
59.414 us [15132] |     } /* b */
93.723 us [15132] |   } /* a */
1.078 ms [15132] | } /* main */
[15120] | main() {
[15120] |   fork() {
208.274 us [15120] |   } /* fork */
[15120] |   wait() {
6.277 ms [15120] |   } /* wait */
[15120] | …
```
> script: Flush python internal buffer at fork

- arch/aarch64/mcount-arch.h
- arch/arm/mcount-arch.h
- arch/x86_64/mcount-arch.h
- tests/unittest.h
- uftrace.h
- utils/asm.h
- utils/compiler.h
- utils/filter.h
- utils/fstack.h
- utils/kernel.h
- utils/perf.h
- utils/script-python.h
- utils/script.h
- utils/symbol.h
- utils/utils.h
I solved #187 a little bit.
I changed to naming convention of the C++ language standard in uftrace.h file and utils/utils.h file.
> Naming convention of the C++ language standard.

- INSTALL.md
- Makefile
- arch/arm/mcount-support.c
- check-deps/Makefile
- check-deps/Makefile.check
- check-deps/__arm_has_hardfp.c
- configure
- misc/install-elfutils.sh
Sometimes it'd be better to provide full compilation method especially
in cross compile environment or in some systems that cannot install
libelf properly for some reasons.
This adds "misc/install-elfutils.sh" to download and compile elfutils.
The usage is as follows:
$ export CROSS_COMPILE=arm-linux-gnueabi-
$ export ARCH=arm
$ export CFLAGS="-march=armv7-a"
$ ./misc/install-elfutils.sh --prefix=`pwd`/build.arm
$ ./configure --prefix=`pwd`/build.arm --with-elfutils=`pwd`/build.arm
$ make
$ make install
Some of environmental variables and prefix is better to be same both for
install-elfutils.sh and configure.
> build: Add install-elfutils.sh to build elfutils manually

- uftrace.c
Like the `--column-offset=DEPTH` line of current `uftrace --help` results, add default values of options, `-f`(`--output-fields=FIELD`) and `--diff-policy`, respectively.
Following the written in `man uftrace-replay`, parenthesizing both default values with quote(`'`)s.
I think the users may infer that the `FIELD` and `POLICY` can be seperated by comma(`,`) from this.
Now we can see the followed results of `uftrace --help`:
```
$ uftrace --help
Usage: uftrace [OPTION...]
[record|replay|live|report|info|dump|recv|graph|script]
[<program>]
uftrace -- function (graph) tracer for userspace
...
--column-offset=DEPTH  Offset of each column (default: 8)
...
--diff-policy=POLICY   Control diff report policy (default:
'abs,compact,no-percent')
...
-f, --output-fields=FIELD  Show FIELDs in the …
```
> doc: Add two default values of options, `-f` and `--diff-policy=POLICY`

- doc/uftrace-script.md
Fix discussed on #240
The example python script, `arg.py`, in the EXAMPLES section was
written using tabs, not white spaces, to indent the code lines,
rendered a wrong man page. This may occur an error if who follow that
as it was.
Now we can see the correct man page like this:
$ man uftrace-script
...
EXAMPLES
...
$ cat arg.py
#
#
def uftrace_entry(ctx):
if "args" in ctx:
print(ctx["name"] + " has args")
def uftrace_exit(ctx):
if "retval" in ctx:
print(ctx["name"] + " has retval")
...
Signed-off-by: Hansuk Hong <flavono123@gmail.com>
> doc: Fix tabs to white spaces of `arg.py` example

- INSTALL.md
I think many people just want to read quick guide for installtion but
pandoc is not written there.  Some people may have problems finding
uftrace man pages.
So it'd be better to provide a very simple command for pandoc
installation in the quick install guide page.
Likewise, it also adds libpython2.7-dev installation command.
> doc: Add more packages in quick install guide

- scripts/trace-memcpy.py
trace-memcpy.py example traces only memcpy() call and calculate how
many times memcpy is called and how much bytes are copied in total.
The usage and output looks as follows:
$ uftrace script -S scripts/trace-memcpy.py --record /bin/ls scripts/
count.py
trace-memcpy.py
replay.py
simple.py
9 times memcpy called
183 bytes copied
The last two lines are printed by trace-memcpy.py
> script: Add trace-memcpy.py script for memcpy info

- doc/uftrace-info.md
uftrace support viewing of symbol information from ELF binary. 
but there is no example from document. 
so, I'm add that!!
> doc: add usage for `uftrace info --symbol` with ELF binary directly.

- utils/utils.c
When there is only a 'uftrace.data.old',
```
$ ls
hello  uftrace.data.old
```
if recording, innocent old directory can be eliminated.
```
$ uftrace record hello
$ ls
hello  uftrace.data
```
So I change the logic removing old directory.
> utils: Adjust the logic removing old directory

- scripts/trace-memcpy.py
The keyword "global" was missing for "count" variable in uftrace_end
function so this patch fixes it.
> script: Fix to add global keyword to count variable

- doc/uftrace-graph.md
Change [\<function\>] -> [*FUNC*]
Because of '<>' on markdown, it disappears
on the 'graph' man page and github man page.
Here:
Here:
```
$ man uftrace graph
...
UFTRACE-GRAPH(1)                                            UFTRACE-GRAPH(1)
NAME
uftrace-graph - Show function call graph
SYNOPSIS
uftrace graph [options] []
...
```
So, fix it.
> doc: Fix '[<function>]' that is invisible

- cmd-replay.c
Some systems are running for a long time and it creates tid more than
6 digits.  In this case, the alignment is a bit broken so this fixes the
problem by giving more spaces for TID field.
Before:
```
$ uftrace -D 2 tests/t-abc
1.627 us [142664] | __monstartup();
0.913 us [142664] | __cxa_atexit();
[142664] | main() {
1.536 us [142664] |   a();
2.670 us [142664] | } /* main */
```
After:
```
$ uftrace -D 2 tests/t-abc
1.627 us [142664] | __monstartup();
0.913 us [142664] | __cxa_atexit();
[142664] | main() {
1.536 us [142664] |   a();
2.670 us [142664] | } /* main */
```
> replay: Adjust TID space for tid more than 6 digits

- libmcount/plthook.c
- scripts/replay.py
- scripts/report-libcall.py
- utils/script-python.c
- utils/script.c
This PR is to fix thread-safety problem running python script in record time.
Before:
```
$ uftrace record -S ./scripts/replay.py tests/t-thread
[30186] | main() {
[30186] |   pthread_create() {
35.314 us [30186] |   } /* pthread_create */
[30186] |   pthread_create() {
19.590 us [30186] |   } /* pthread_create */
[30186] |   pthread_create() {
96.816 us [30186] |   } /* pthread_create */
[30186] |   pthread_create() {
process crashed by signal 11: Segmentation fault (si_code: 1)
[30189] | foo() {
child terminated by signal: 11: Segmentation fault
```
After:
```
$ uftrace record -S ./scripts/replay.py tests/t-thread
[ 29732] | main() {
[ 29732] |   pthread_create() {
29.533 us [ 29732] |   } /* pthread_create */
[ 29732] |   pthread_create() {
156.904 us [ 29732] |   } /* pthread_create …
```
> script: Fix thread-safety issue in python interpreter execution

- libmcount/plthook.c
- utils/filter.c
this "PR" is splitted part from "support-i386".
two fix for uftrace.
first commit:
```
trigger: do not use memcpy() for copying trigger
if we use memcpy to copy the &iter->trigger,
depending on the size of the uftrace_trigger *tr
we will ride optimization path to use SSE inside memcpy.
it will change status of SIMD register like mmx.
therefore we lose original value of register.
so, we decide not to use memcpy.
```
second commit:
```
mcount: add mcount_arch_child_idx()
The value of child idx may be different for each architecture.
For this reason, we added the part that calculates child_idx
to be implemented by each architecture.
```
> some fix for uftrace

- arch/i386/common.S
- arch/i386/fentry.S
- arch/i386/mcount-support.c
- arch/i386/plthook.S
some code of supporting i386 have been not supported from the old version gcc.
this PR is the patch to resolve that.
> Support old gcc version

- cmd-graph.c
- cmd-replay.c
- doc/uftrace-graph.md
- tests/runtest.py
- tests/t097_dump_basic.py
- tests/t098_dump_tid.py
- tests/t099_dump_filter.py
- tests/t100_dump_depth.py
- tests/t116_field_none.py
- tests/t181_graph_full.py
- tests/t187_graph_field.py
- tests/t188_graph_field_none.py
- uftrace.c
- utils/field.c
- utils/field.h
The -f/--output-fields option is to specify fields in the replay output.
This patch implements the same feature for graph output.  Users can
customize the output for their needs like below:
```
$ uftrace graph -f time,selftime,addr
========== FUNCTION CALL GRAPH ==========
10.339 ms                  4004a0 : (1) t-sort
10.339 ms 134.739 us       4004a0 : (1) main
53.878 us   2.207 us       4005f1 :  +-(2) foo
51.671 us  51.671 us       4005c7 :  | (6) loop
:  |
10.150 ms  57.077 us       400621 :  +-(1) bar
10.093 ms  10.093 ms       400480 :    (1) usleep
```
The default value is 'time' only.  And it also accepts a special
field name of 'none' which disables the field display and shows function
graph output only.
```
$ uftrace graph -f none
========== FUNCTION CALL GRAPH ==========
(1) …
```
> graph: Use -f/--output-fields to customize its output

- doc/uftrace-live.md
- doc/uftrace-record.md
In the man pages of record and live, read trigger examples are a bit wrong
so this patch fixes it.
> doc: Fix a tiny mistake on read trigger example

- utils/fstack.c
Currently the task that is chosen by --tid option
task->t become NULL on setup_task_filter().
Hence this crash can occur.
So properly set task->t regardless --tid option.
Fixes #304.
> fstack: Fix the segfault when using --tid

- .gitignore
The commit 2094fe4 ("demangler: Add an executable
"demangler" file") generates a binary misc/demangler,
so add it to .gitignore.
> demangler: Ignore new 'misc/demangler' binary

- Makefile
This patch provides two make options for debugging purposes.
DEBUG option allows uftrace build with -O0 option to make it easy to run
it with some debuggers such as gdb.  The usage is as follows:
$ make DEBUG=1
PG option allows uftrace build with -pg option to make it tracable with
another uftrace.  The usage is as follows:
$ make PG=1
$ uftrace -t 3ms -- uftrace record -d xxx tests/t-abc
[ 19570] | main() {
[ 19570] |   command_record() {
47.038 us [ 19570] |     fork();
[ 19570] |     do_main_loop() {
[ 19574] |     } /* fork */
[ 19574] |     do_child_exec() {
[ 19574] |       execv() {
[ 19570] |       load_module_symtabs() {
[ 19570] |         load_symtab() {
3.031 ms [ 19570] |           qsort();
4.839 ms [ 19570] |           qsort();
10.578 ms [ 19570] |         } /* load_symtab */ …
> build: Add DEBUG=1 and TRACE=1 make options

- cmd-dump.c
- tests/runtest.py
- tests/t101_dump_chrome.py
- tests/t107_dump_time.py
- tests/t166_dump_sched.py
- tests/t196_chrome_taskname.py
- utils/data-file.c
- utils/fstack.c
- utils/kernel.c
- utils/kernel.h
- utils/perf.c
- utils/perf.h
It'd be a lot better to show the task name of each process in chrome
trace output so that users can understand what the process does.
This patch adds the task name info in chrome dump output as follows:
$ uftrace record -F main tests/t-taskname
$ uftrace dump --chrome
{"traceEvents":[
{"ts":0,"ph":"M","pid":9413,"name":"process_name","args":{"name":"t-taskname"}},
{"ts":15429161593.248,"ph":"B","pid":9413,"name":"main"},
{"ts":15429161593.548,"ph":"B","pid":9413,"name":"task_name1"},
{"ts":15429161593.726,"ph":"B","pid":9413,"name":"prctl"},
{"ts":0,"ph":"M","pid":9413,"name":"process_name","args":{"name":"foo"}},
{"ts":15429161598.204,"ph":"E","pid":9413,"name":"prctl"},
{"ts":15429161598.926,"ph":"E","pid":9413,"name":"task_name1"}, …
> dump: Add task name to chrome dump output

- doc/uftrace.md
- uftrace.c
I solved issue #319 .
The -h option is to print help message. It's the short version of --help
option.
Although -? option has a same role as -h option, the -h option is easier
to assume --help option than the -? option.
So it is useful to add the -h option.
Signed-off-by: Sangwon Hong <qpakzk@gmail.com>
> uftrace: Add -h option

- tests/t185_exception2.py
- tests/t186_exception3.py
The personality routines such as `__gxx_personality_v0()`
can make output be various so exclude them.
Test case 124 already do it so fix test case 185 and 186.
Like the commit 019c1fd ("test: Update C++ exception test case")
Before:
```bash
./runtest.py exception
124 exception           : OK OK OK OK OK OK OK OK OK OK
185 exception2          : NG NG NG NG NG NG NG NG NG NG
186 exception3          : NG NG NG NG NG NG NG NG NG NG
```
After:
```sh
./runtest.py exception
124 exception           : OK OK OK OK OK OK OK OK OK OK
185 exception2          : OK OK OK OK OK OK OK …
```
> test: Filter out personality routunes in C++ exception test cases

- Makefile
this PR associated with #324.
we have used brace expansion to uninstall libmcount shared object series.
but it is not supported from other shell environment like dash.
therefore uninstall-script at makefile be changed to that did not use
brace expansion.
> changed the uninstall-script in the makefile to not use the brace expansion.

- cmd-live.c
- cmd-record.c
- uftrace.h
If we use `{get,put}_libmcount_path()` functions,
First, we can check both the library path the user gave with `-L`
and second path appending "/libmcount"(for test).
Second, we can previously check whether libmcount*.so files exist or no,
to avoid errors that can occur when recording.
How about this patches ?
>  record: Use {get,put}_libmcount_path()

- cmd-live.c
- cmd-record.c
- utils/utils.c
Since strjoin internally uses realloc passing the @left argument, the
@left must be dynamically allocated buffer.
But the commit 5eb6468 passes a buffer by getting getenv(), which makes
realloc in strjoin fail.
This patch fixes the problem and adds such information to strjoin
function to prevent such misuse.
> utils: Fix to avoid realloc fail in strjoin

- libmcount/internal.h
- libmcount/record.c
Both `record_event()` and `record_ret_stack()` have
the same code getting current shmem buffer,
so refactor it with new function get_shmem_buffer().
> record: Refactoring with get_shmem_buffer()

- tests/runtest.py
- tests/s-thread-exit.c
- tests/t015_longjmp.py
- tests/t087_arg_variadic.py
- tests/t133_long_string.py
- tests/t144_longjmp2.py
- tests/t145_longjmp3.py
_FORTIFY_SOURCE macro is used by default when optimization is on.  It generates additional buffer overflow detection calls.  So this fixes those kind of useless difference.
This also includes to use `colordiff` instead of `diff` for better comparison.
> test: Suppress generating buffer overflow detection calls

- cmd-record.c
- doc/uftrace-live.md
- doc/uftrace-record.md
- uftrace.c
- uftrace.h
Most system enables ASLR by default for security reasons, but it makes
difficult to analyze target processes execution from its address
information because its address space is randomized.
Pratik Bhatu requested to turn off ASLR for easiser analysis of target
processes, so this patch adds a new option --no-randomize-addr to
disable ASLR.
> record: Add --no-randomize-addr to disable ASLR

- cmd-info.c
- tests/t097_dump_basic.py
- tests/t098_dump_tid.py
- tests/t099_dump_filter.py
- tests/t100_dump_depth.py
- uftrace.h
Solve #343 .
The `program version` showed uftrace version of currently running `uftrace info`.
Fix uftrace version that recorded the data.
When recording the data, write uftrace version in `uftrace.data/info` file. So It is possible to show a correct uftrace version by reading `uftrace.data/info` file.
> info: Fix program version that recorded the data

- utils/debug.c
Since current gray color looks same as normal color depending on the
terminal environment, this has to be much clear on every envinronment.
So this patch changes gray color to more distinguishable gray.  It will
make user comfortable when reading replay output.
> utils: Make gray color more distinguishable

- uftrace.c
If given wrong tid value with --tid option,
some problems can occur at setup_task_filter().
So check given tid value. Hanbum Park reported this
problem with the dump subcommand.
Fixes: #374
> uftrace: Check if wrong tid value or not

- .gitignore
- Makefile
- misc/run-lcov.sh
- tests/Makefile
This PR provides a way to generate code coverage report using gcov and lcov.
It'd be useful to see the code coverage of uftrace itself for debugging purposes.
It also includes some scripts from lcov project.
The execution sequence is as follows:
1. build uftrace with gcov enabled
$ make GCOV=1
2. run uftrace
$ ./uftrace info
3. run a script to generate html report
$ ./misc/run-lcov.sh
4. open `uftrace.html` in a browser
> gcov: Add a convenient way to generate code coverage report

- libmcount/mcount.c
- libmcount/record.c
- utils/session.c
- utils/symbol.c
- utils/symbol.h
Based on current master branch,
I found this problem in the hello world case with `-k` option
like below:
```
$ sudo uftrace -k ./hello
hello
1.107 us [ 25464] | __monstartup();
0.994 us [ 25464] | __cxa_atexit();
[ 25464] | main() {
[ 25464] |   puts() {
0.537 us [ 25464] |     <ffff81003860>();
1.690 us [ 25464] |     <ffff81215420>();
0.425 us [ 25464] |     <ffff81003620>();
7.092 us [ 25464] |     <ffff810692b0>();
16.544 us [ 25464] |   } /* puts */
...
```
This problem is related with The commit de7387f
("session: Don't create a map for main executable")
The commit excludes `[stack]` in a map, when skipping special
mappings like `[heap]`, however, `[stack]` is still needed
to get kernel base addr. If skipping `[stack]` mapping,
we aren't able to properly find kernel base addr at …
> session: Fix missing kernel base addr problem

- cmds/record.c
This fixes the below error message when --nop option is enabled.
$ uftrace --nop -vvv abc
uftrace: checking binary abc
symbol: check trace functions in abc
uftrace: creating 0 thread(s) for recording
uftrace: using libmcount-nop.so library for tracing
uftrace: all process/thread exited
uftrace: child terminated with exit code: 0
uftrace: fill header (metadata) info in /tmp/uftrace-live-1O7bAj/info
uftrace: /home/honggyu/work/uftrace/cmds/record.c:377:fill_file_header
ERROR: cannot open info file: No such file or directory
> record: Do not read uftrace.data/info with --nop

- Makefile
This patch allows libmcount libraries to be compiled with code coverage
support option.
Since gcov related options are smart enough, the target program doesn't
have to be compiled with code coverage option but just with normal
tracable option such as -pg, -finstrument-functions or without such
flags.
The --coverage option is a synonym for -fprofile-arcs -ftest-coverage
(when compiling) and -lgcov (when linking) so it's used for simplicity.
> gcov: Support code coverage for libmcount-*.so

- utils/debug.c
The current gray color still looks same as normal text color in some
environments.  This patch makes the gray to dark gray.
> utils: Make gray color to dark gray

- configure
In configure script, --without-libstdc++ doesn't work as below:
$ ./configure --without-libstdc++
$ make
$ ldd uftrace | grep libstdc++
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa6df232000)
So this patch fixes the problem matching it to check-deps/cxa_demangle.
> build: Fix --without-libstdc++ option in configure

- utils/symbol-libelf.h
After the commit 60d013e ("symbol: Add
elf_for_each_nhdr() macro"), segfaults occurs
when using event options, so fix it.
Fixes: #403
Reported-by: Honggyu Kim <honggyu.kp@gmail.com>
> symbol: Fix a bug missing d_buf of Elf_Data

- cmds/tui.c
- doc/uftrace-tui.md
In tui mode, 'c' key is very useful by collapsing nested children.
It'd also be very useful to provide a short key to find the child that
has longest execution time among all the other children.
The 'l' key for longest child performs as below:
1. unfold the current node
2. find a child that has the longest execution time
3. collapse all the other children except for the longest child
4. move to the longest child
It'd be useful when finding the performance critical execution path.
Resolved: #398
> tui: Support to find longest executed child in tui graph

- doc/uftrace-live.md
- doc/uftrace-record.md
- uftrace.c
It'd be better to provide a short option for --auto-args, so this patch
adds -g so that we can simply see arguments and return values.
> uftrace: Make -a option synonym for --auto-args

- cmds/dump.c
Currently, the arguments are wraped by parenthesis and it looks like
tuple.  But return value is also represented in the same way.
As return value only contains a single value, so it'd be better to show
it without parenthesis.
Before:
{ ...,"args":{"arguments":"(0xa9ad68, -1)"}},
{ ...,"args":{"retval":"(2)"}},
After:
{ ...,"args":{"arguments":"(0xa9ad68, -1)"}},
{ ...,"args":{"retval":"2"}},
> chrome: Don't use parenthesis for return value

- misc/gen-autoargs.py
- utils/auto-args.c
- utils/auto-args.h
- utils/filter.c
operator new and operator delete are widely used in C++ programs so it'd
be better to add them to auto-args list.
operator new and delete has various prototypes including nothrow and
placement versions, but we only handles the basic forms.  For more
prototypes, '/usr/include/c++/5/new' file can be referenced.
This patch adds them to misc/prototypes.h and fixes misc/gen-autoargs.py
to handle them.
> misc: Add operator new and delete to auto-args

- arch/i386/mcount-dynamic.c
To Fix the compiler warning:
uftrace/arch/i386/mcount-dynamic.c: In function 'mcount_setup_trampoline':
uftrace/arch/i386/mcount-dynamic.c:22:28: warning: unused variable‘adi’
[-Wunused-variable]
struct arch_dynamic_info *adi = mdi->arch;
uftrace/arch/i386/mcount-dynamic.c: In function 'patch_fentry_func':
uftrace/arch/i386/mcount-dynamic.c:75:24: warning: cast to pointer from
integer of different size
[-Wint-to-pointer-cast]
unsigned char *insn = (void *)sym->addr;
> i386: Fix compiler warning

- Makefile
- configure
- misc/version.sh
It'd be better to display the result of feature detect when running
configure script.
```
$ ./configure --prefix=$HOME/usr --without-libdw
...                        prefix: /home/honggyu/usr
...                        libelf: [ on  ]
...                         libdw: [ OFF ]
...                  libpython2.7: [ on  ]
...                   libncursesw: [ on  ]
...                  cxa_demangle: [ on  ]
```
It shows the outlook almost same as Linux perf tool.
> build: Display feature detect result of configure

- utils/symbol-rawelf.c
- utils/symbol-rawelf.h
- utils/utils.h
sometime uftrace should reference the address (eg, section offset) that
the ELF field points to. Since section headers are not essential, they
can refer to insecure memory and cause errors such as segment faults.
so, add logic to validate ELF before using it.
> symbol: validate ELF format before using it

- README.md
Currently, some links in README.md point things that are in 'master' branch of 'upstream' repository.
But, these links couldn't work as expected in different branch or forked repository.
So, I think that using relative link than absolute link is better.
Related Material: https://help.github.com/articles/about-readmes/#relative-links-and-image-paths-in-readme-files
Signed-off-by: Taeguk Kwon <xornrbboy@gmail.com>
> doc: Prefer relative link than absolute link in README.md

- doc/uftrace-live.md
- doc/uftrace-record.md
- doc/uftrace-script.md
- scripts/count.py
- scripts/replay.py
- scripts/report-libcall.py
- scripts/simple.py
- scripts/trace-memcpy.py
https://github.com/namhyung/uftrace/blob/419e65024ad19ac85d120f30123802be694a0967/utils/script-python.c#L508
As you can see above, ```uftrace_begin``` requires one argument.
But there are no arguments in ```uftrace_begin``` of some scripts and documents.
So, I add missing argument in 'uftrace_begin'.
Signed-off-by: Taeguk Kwon <xornrbboy@gmail.com>
> script: Add missing argument in 'uftrace_begin'

- misc/symbols.c
- utils/data-file.c
- utils/dwarf.c
Hello,
The memory allocated by getline() is not freed.
So, It should free the allocated memory.
Associated issue : #441
Thanks.
> Fix memory leak in Multiple functions

- cmds/record.c
A part of conditional expression is always true.
So, Remove dead Conditional expression code.
#442
Reference: https://cwe.mitre.org/data/definitions/571.html
https://wiki.sei.cmu.edu/confluence/display/c/MSC07-C.+Detect+and+remove+dead+code
> record: Remove dead code in save_session_symbols()

- tests/s-dlopen.c
- tests/s-dlopen2.cpp
- tests/t200_lib_dlopen2.py
recently loader does not allow load shared object from unspecified path.
therefore, when load shared object by using dlopen then must specify the
path where to load shared object.
Fixed: #437
> test: update tests that relate with dlopen

- cmds/report.c
- doc/uftrace-live.md
- doc/uftrace-record.md
- doc/uftrace-script.md
- libmcount/plthook.c
- libtraceevent/event-parse.c
Hello.
I corrected the typos.
Thanks.
Changes:
```
/libmcount/plthook.c:718: neccesary -> "necessary"
/libtraceevent/event-parse.c:5709: successully -> "successfully"
/doc/uftrace-script.md:44: addtional -> "additional"
/doc/uftrace-record.md:111: addtional -> "additional"
/doc/uftrace-live.md:136: addtional -> "additional"
/cmds/report.c:559: happend -> "happened"
```
> uftrace: Fix a typo in comment

- utils/symbol.c
A part of conditional expression is always true.
So, Remove dead Conditional expression code.
Fixed: #452
> symbol: Remove dead code in save_module_symbol()

- cmds/replay.c
This patch fixes an error while loading chrome trace viewer.  It's
because it doesn't allow to contain non-ascii characters inside json
format.
Fixed: #425
> chrome: Properly escape non-ascii characters

- utils/filter.c
Possible memory leaks from usage of strdup without free().
So, It should free the allocated memory.
Fixed: #458
> filter: Fix memory leak in setup_trigger()

- doc/uftrace-replay.md
Since -f FIELD/--output-fields=FIELD option now supports to show
task-name with 'task' and module-name with 'module', so this adds them
to the man page of replay.
> doc: Add task and module fields to replay man page

- cmds/info.c
> info: Fix invalid strncmp count in read_cpuinfo()

- cmds/info.c
- misc/symbols.c
- utils/data-file.c
- utils/symbol-rawelf.c
Hello.
In my opinion, The format string is mismatched.
"%lu" is the correct format for unsigned long.
So, I changed the variables to unsigned long data types.
Thanks.
> uftrace: Fix format string mismatch

- cmds/info.c
- utils/dwarf.c
- utils/session.c
- utils/symbol.c
- utils/symbol.h
With `valgrind`, I found some memory leaks and unsafe codes. And I fixed them.
I used the command: `valgrind --leak-check=full --show-leak-kinds=all --error-limit=no --track-origins=yes uftrace vector.out`
And `vector.out` is created from the simple source code:
```cpp
#include <vector>
int main() {
std::vector<int> vec;
vec.push_back(12);
}
```
I want your reviews because I'm still not familiar and not well-understanding to the codebase.
Signed-off-by: Taeguk Kwon <xornrbboy@gmail.com>
> uftrace: Fix memory leaks and improve memory safety.

- gdb/uftrace/mcount.py
- misc/gen-autoargs.py
- tests/runtest.py
- tests/t003_thread.py
- tests/t049_column_view.py
- tests/t050_no_pltbind.py
- tests/t051_return.py
- tests/t052_nested_func.py
- tests/t053_filter_time.py
- tests/t055_filter_time_N.py
- tests/t056_filter_time_T.py
- tests/t057_filter_time_D.py
- tests/t064_trigger_trace.py
- tests/t084_arg_mixed.py
- tests/t176_arg_fptr.py
- tests/t178_arg_auto1.py
- tests/t182_thread_exit.py
- tests/t190_trigger_autoargs.py
Hello,
Resolved the Reimport problem, and removed unused python modules.
Thanks.
after test log:
```
./runtest.py 
003 thread              : OK OK OK OK OK OK OK OK OK OK
049 column_view         : OK OK OK OK OK OK OK OK OK OK
050 no_pltbind          : OK OK OK OK OK OK OK OK OK OK
051 return              : OK OK OK OK OK OK OK OK OK OK
052 nested_func         : OK OK OK OK OK NG NG NG NG NG
053 filter_time         : OK OK OK OK OK OK OK OK OK OK
055 filter_time_N       : OK OK OK OK OK OK OK OK OK OK
056 filter_time_T       : OK OK OK OK OK OK OK OK OK OK
057 filter_time_D       : OK OK OK OK OK OK OK OK OK OK
064 trigger_trace       : OK OK OK OK OK OK OK OK …
```
> test: Fix Reimport issue and unused python modules

- utils/kernel.c
This is to remove the following warning message.
uftrace/utils/kernel.c:205:3: warning: ignoring return value of ‘write’
> utils: Check return value of write

- libmcount/plthook.c
Fixes
plthook.c:128:41: error: use of undeclared identifier 'RTLD_DEFAULT'
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> include dlfcn.h for RTLD_DEFAULT

- cmds/dump.c
- utils/perf.c
It was missing to call update_perf_task_comm to get the finally updated
comm name.
> chrome: Update perf event before getting task name

- tests/runtest.py
- tests/t101_dump_chrome.py
- tests/t107_dump_time.py
- tests/t166_dump_sched.py
- tests/t196_chrome_taskname.py
Since process_name and thread_name fields have more information, the
tests have to be modified accordingly.
> tests: Fix dump --chrome output

- cmds/graph.c
Hello,
In the process of using the graph function, a memory leak occurs.
So, I modified the source code.
Thanks
Valgrind log:
```
==24087== 7 bytes in 1 blocks are definitely lost in loss record 1 of 3
==24087==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24087==    by 0x613EC39: strdup (strdup.c:42)
==24087==    by 0x121BD3: create_graph (graph.c:137)
==24087==    by 0x12A468: walk_sessions (session.c:238)
==24087==    by 0x12251A: setup_graph_list (graph.c:154)
==24087==    by 0x12251A: build_graph (graph.c:486)
==24087==    by 0x12251A: command_graph (graph.c:677)
==24087==    by 0x111A6F: main (uftrace.c:1065)
==24087== 
==24087== 80 (40 direct, 40 indirect) bytes in 1 blocks are definitely lost in loss record 3 of 3
==24087== …
```
> graph: Fix memory leak

- utils/dwarf.c
Sometimes it might be NULL. Protect it from segmentation fault.
Fixed: #490
> dwarf: Fix Null Pointer Dereference in load_debug_file()

- tests/runtest.py
Removed unnecessary line end semicolons in Python.
Signed-off-by: Ahn, Seung-rye <seungrye@gmail.com>
> Removed unnecessary line end semicolons.

- cmds/live.c
Hello,
On line 33 of the reset_live_opts(), NULL pointer before "free" it, losing what it points to. 
So, Memory leakage occurs.
Thanks.
Problem code:
https://github.com/namhyung/uftrace/blob/3066f545a220f10df1f33ad184de01563fd3f877/cmds/live.c#L24-L37
valgrind log:
```
==4943== 4 bytes in 1 blocks are definitely lost in loss record 1 of 1
==4943==    at 0x4C2FA3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4943==    by 0x4C31D84: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4943==    by 0x14776A: strjoin (utils.c:413)
==4943==    by 0x112740: opt_add_string (uftrace.c:212)
==4943==    by 0x112740: parse_option (uftrace.c:385)
==4943==    by 0x61CD255: group_parse (argp-parse.c:257)
==4943==    by 0x61CD255: parser_parse_opt …
```
> live: Fix memory leak in reset_live_opts()

- cmds/info.c
Reported-by: GwanYeong Kim <gy741.kim@gmail.com>
> info: Avoid segfault when task.txt doesn't exist

- misc/debug-mcount.cmd
- misc/debug.sh
This commit allows using custom command & argv with debug.sh
Example:
sh misc/debug.sh tests/t-fibonacci 5
If no arguments are passed to debug.sh, it defaults to tests/t-abc.
Fixed: #511
> misc: Change debug.sh using custom command & argv

- doc/uftrace.html
This commit update uftrace.github.io index page's installation link.
Fixed : #547
Signed-off-by: Claudia J. Kang <claudiajkang@gmail.com>
> doc: Update index page's installation link.

- check-deps/Makefile
- check-deps/Makefile.check
- check-deps/__cc_has_wstringop_truncation.c
- cmds/record.c
This commit fixes the GCC8 string tuncation warning occured from strncpy.
Fixed: #571
> record: fix GCC8 string truncation warning

- utils/data-file.c
There is an error when reading data file inside uftrace.data.
The problem is because of saved_errno is not recovered when data file is
normally opened inside uftrace.data directory.
This fixes the problem by recovering saved_errno when data file is
properly opened.
Fixed: #589
> utils: Fix data file open failure inside data dir

- Makefile
When running make with multiple threads, sometimes the script.o target fail to build because of missing version.h
It happens because script.c is including version.h but this dependency is missing in the Makefile.
Signed-off-by: Anas Balboul anasbalbo@gmail.com
> build: adding version.h dependency manually

- tests/t208_watch_cpu.py
This patch fixes the below test failure.
```
$ ./runtest.py -dp -O1 208
Test case                 pg
------------------------: O1
t208_watch_cpu: diff result of -pg -O1
--- expect      2018-11-20 12:33:26.146855841 +0900
+++ result      2018-11-20 12:33:26.146855841 +0900
@@ -1,3 +1,6 @@
- main() {
+ __monstartup() {
/* watch:cpu (cpu=N) */
+ } /* __monstartup */
+ __cxa_atexit();
+ main() {
sysconf();
208 watch_cpu           : NG
```
> tests: Fix watch_cpu test with -F main

- cmds/replay.c
- utils/auto-args.c
- utils/debug.c
- utils/utils.h
Automatic argument display is great but it sometimes looks too verbose
with too many arguments and return values.
This patch makes arguments and return values more colorful if they are
some special types.  The color scheme is as follows:
- string types     : magenta
- char types       : magenta
- enum types       : blue
- function pointer : cyan
- parens and comma : bold
This would make users more comfortable to identify those values.
> replay: Make arguments and retvals colorful

- cmds/tui.c
- doc/uftrace-tui.md
- doc/uftrace.html
This PR makes some changes on TUI as follows:
1. Set the focus on the current function when switching from graph to report window
2. Make 'R' to go to the top of report window
3. Set to the top when switched from session window
4. Cancel search when cursor moves
5. Add 'z' key to set current line to the center of screen
6. Update the description of Enter key
7. Show source location info in report footer
> tui: Apply various enhancements for tui command

- tests/Makefile
unittest is a useful tool to be a target of uftrace itself, so it'd be
useful to be compiled with -pg and -g flags unconditionally so that it
can be directly traced to understand uftrace internal.
> test: Add -pg and -g flags to tests/Makefile

- tests/runtest.py
- tests/t141_recv_basic.py
- tests/t142_recv_multi.py
- tests/t143_recv_kernel.py
- tests/t150_recv_event.py
- tests/t151_recv_runcmd.py
- tests/t157_script_python.py
- tests/t167_recv_sched.py
- tests/t199_script_info.py
- tests/t207_dump_graphviz.py
The PR enables running parallel tests through multiprocessing pool.
Due to the concurrent test, the result won't be shown in an orderly manner.
So instead of showing result directly, the progress bar has been added.
After all, tests are done, the test result will be shown at once.
**Change log**
- Progress bar for visualizing current running tests
- build directory changed: `uftrace/tests` -> `/tmp/<temporarily_created>`
- build and test with absolute path
- test port randomization for not to conflict socket during a concurrent tests
```bash
$ export TESTARG='-j 8'; make test;
> ...
./runtest.py all
Start 211 tests with 8 worker
Progress [########################################] 211/211
------------------------: O0 O1 O2 O3 Os O0 O1 …
```
> test: parallel tests implementation with multiprocessing

- libmcount/record.c
Function allocate_shmem_buffer() first argument's name "buf"
seems pretty ambiguous.
Paired to cmds/record.c's record_mmap_file(), both of the function
uses shared memory by leveraging mmap() through sess_id.
static void record_mmap_file(const char *dirname, char *sess_id, int bufsize)
And from this viewpoint, since it doesn't mean anything,
argument name "buf" seems meaningless.
> mcount: rename ambiguous argument name

- Makefile
It'd be better to have a switch for address sanizitzer.  Due to
preloading problem, it's not applied to libmcount*.so.
> build: Add a build option ASAN=1 to use address sanitizer

- cmds/tui.c
- doc/uftrace-tui.md
Current c/e works for collapse/expand its direct children, but it
doesn't fold/unfold in a nested manner.
This patch adds C/E keys for nested collapse/expand.
> tui: Add C/E keys for nested collapse/expand

- misc/symbols.c
This patch is to properly release allocated memory in sessions.  It also
changes the name "read_session" to "read_sessions" so that it can be
corresponding to "delete_sessions".
> misc: Cleanup sessions at the end of misc/symbols

- cmds/dump.c
- cmds/graph.c
- cmds/replay.c
- cmds/report.c
- cmds/script.c
- cmds/tui.c
- tests/t215_no_libcall_replay.py
- tests/t216_no_libcall_report.py
- tests/t217_no_libcall_dump.py
- tests/t218_no_libcall_graph.py
- tests/t219_no_libcall_script.py
- utils/fstack.c
- utils/fstack.h
Since the option --no-libcall only work for record command, it'd be
better to apply it to other analysis commands including replay, report,
dump, graph, tui, and script.
> uftrace: Apply --no-libcall to analysis commands

- cmds/report.c
- utils/fstack.c
Some features are not well tested after applying --no-libcall to
analysis commands.  This is a fixup patch for that.
Before:
```
$ make test
[039] fstack_skip                   : SIG
...
067 report_diff         : NG NG NG NG NG NG NG NG NG NG
158 report_diff_policy1 : NG NG NG NG NG NG NG NG NG NG
159 report_diff_policy2 : NG NG NG NG NG NG NG NG NG NG
160 report_diff_policy3 : NG NG NG NG NG NG NG NG NG NG
177 report_diff_policy4 : NG NG NG NG NG NG NG NG NG NG
```
After:
```
$ make test
[039] fstack_skip                   : PASS
...
067 report_diff         : OK OK OK OK OK OK OK OK OK OK
158 report_diff_policy1 : OK OK OK OK OK OK OK OK OK OK
159 report_diff_policy2 : OK OK OK OK OK OK OK OK OK OK
160 report_diff_policy3 : OK OK OK OK OK OK OK OK OK OK
177 report_diff_policy4 : OK OK OK …
```
> uftrace: Fix missing changes of --no-libcall apply

- doc/uftrace-dump.md
- doc/uftrace-graph.md
- doc/uftrace-replay.md
- doc/uftrace-report.md
- doc/uftrace-script.md
- doc/uftrace-tui.md
The option --no-libcall is added to many analysis commands, but didn't
update the man pages.  This patch adds the explanation to each analysis
command.
It also updates some description in script command because the meaning
of "show" doesn't make sence for script execution.
> doc: Add --no-libcall to man pages of analysis commands

- cmds/tui.c
Since it may take some time to build graph when tui is launched, users
may get confused if it's currently working or just stuck.
To inform that tui is working, this patch adds a kind message at the
center of screen showing "Building graph for TUI...".
> tui: Add a loading message before main screen shown

- doc/uftrace-live.md
- doc/uftrace-record.md
- doc/uftrace-replay.md
- doc/uftrace.html
- tests/t038_trace_disable.py
- tests/t040_replay_onoff.py
- tests/t042_live_disable.py
This patch adds a new section that describes trace control triggers.
It only covers "trace_on", "finish", and signal trigger as of now.
This also adds a good example that shows replay output with dwarf args info of a real world program (clang).
>  slide: Add Trace Control Triggers section

- cmds/dump.c
- cmds/replay.c
- utils/symbol.c
- utils/symbol.h
The symbol address search is done based on ranged comparison.  It may be
useful for finding functions, but it'd be better to show its offset when
it comes to data symbols.
Source:
```
int a[] = { 1, 2, 3, 4 };
void foo(int *a, int *b, int *c, int *d) { }
int main()
{
foo(&a[0], &a[1], &a[2], &a[3]);
return 0;
}
```
Before:
```
$ uftrace -a a.out
1.867 us [ 40216] | __monstartup();
1.080 us [ 40216] | __cxa_atexit();
[ 40216] | main() {
1.766 us [ 40216] |   foo(&a, &a, &a, &a);
3.096 us [ 40216] | } = 0; /* main */
```
After:
```
$ uftrace -a a.out
1.867 us [ 40216] | __monstartup();
1.080 us [ 40216] | __cxa_atexit();
[ 40216] | main() {
1.766 us [ 40216] |   foo(&a, &a+4, &a+8, &a+12);
3.096 us [ 40216] | } = 0; /* main */
```
The change is applied to replay and dump commands. …
> symbol: Display data symbol with offset

- cmds/info.c
It'd be more readable for users to show signal string of exit status in
uftrace info output.
Here are the example outputs:
```
```
> info: Show signal string for exit status

- tests/runtest.py
- tests/t022_filter_kernel.py
- tests/t079_replay_kernel_D.py
- tests/t080_replay_kernel_D2.py
- tests/t081_kernel_depth.py
- tests/t103_dump_kernel.py
- tests/t104_graph_kernel.py
- tests/t111_kernel_tid.py
- tests/t132_trigger_kernel.py
- tests/t137_kernel_tid_update.py
- tests/t138_kernel_dynamic.py
- tests/t139_kernel_dynamic2.py
- tests/t143_recv_kernel.py
- tests/t148_event_kernel.py
- tests/t149_event_kernel2.py
- tests/t163_event_sched.py
- tests/t164_report_sched.py
- tests/t165_graph_sched.py
- tests/t166_dump_sched.py
- tests/t167_recv_sched.py
- tests/t174_replay_filter_kernel.py
- tests/t189_replay_field2.py
- tests/t196_chrome_taskname.py
- tests/t208_watch_cpu.py
- tests/t221_taskname_time.py
New multiprocessing.Pool(1) for serial tests added.
By adding extra 'serial' attribute to TestBase,
all the serial testcases will be executed in new worker.
Since serialized tests, has been implemented, 
test case results might be showing up slow (ongoing tests)
Fixed: #620
> test: serialized test implemented

- arch/arm/mcount.S
- arch/arm/plthook.S
Current implementation for mcount_return and plthook_return only reserve
r0 and r1 registers assuming the size of return value is enough with 8
bytes.
But some functions may have a return type in struct and its size is more
than 8 bytes as following example:
```
struct { int64_t quot, int64_t rem}
__aeabi_ldivmod(int64_t numerator, int64_t denominator) {
int64_t rem, quot;
quot = __divmoddi4(numerator, denominator, &rem);
return {quot, rem};
}
```
In this case, we might partially lose return values because the return
value is stored in r0, r1, r2, and r3 registers to keep 16 bytes in
the return type of struct { int64_t quot, int64_t rem}.
So this patch fixes to keep r0-r3 registers to prevent such problems.
Fixed: #679
> arm: Handle struct return type by keeping more regs on stack

- tests/t079_replay_kernel_D.py
- tests/t081_kernel_depth.py
- tests/t132_trigger_kernel.py
- tests/t137_kernel_tid_update.py
- tests/t138_kernel_dynamic.py
- tests/t139_kernel_dynamic2.py
- tests/t143_recv_kernel.py
- tests/t174_replay_filter_kernel.py
replacing 'sys_open' to 'sys_openat' has replaced
other function rather than 'sys_open'
return result.replace('sys_open', 'sys_openat')
by this line, not only 'sys_open', but also 'do_sys_open'
has been replaced to 'do_sys_openat' which is misbehavior
because it doesn't exist in kernel symbol.
```
t081_kernel_depth: diff result of -pg -O0
--- expect	2019-03-12 23:23:20.943082509 +0900
+++ result	2019-03-12 23:23:20.943082509 +0900
@@ -3,3 +3,3 @@
sys_openat() {
-       do_sys_openat();
+       do_sys_open();
} /* sys_openat */
081 kernel_depth        : NG
```
> test: fix sys_open replace exact match

- tests/t143_recv_kernel.py
Test t143 is broken due to missing filter at previous commit.
From commit b4812a, kernel function 'exit_to_usermode_loop'
had been removed from the result, and added to --notrace option.
Seems this one is missing at t143.
> test: broken test due to missing notrace filter

- libmcount/event.c
- utils/filter.c
- utils/kernel.c
- utils/kernel.h
- utils/utils.h
this commit allows passing '@k' for kernel option as an abbreviated form of '@kernel'
created a util function for strstr(buf, '@k')
// before
$uftrace -K 2 -F sys_openat@kernel --force ./echo-sync
// after
$uftrace -K 2 -F sys_openat@k --force ./echo-sync
> utils: enable @k as an abbreviated form of @kernel

- arch/arm/mcount-support.c
- libmcount/plthook.c
This PR contains some bug fixes in libmcount as follows:
- Fix to properly add SINGLE_THREAD macros
- Fix mtd access before mcount_prepare()
- Fix missing comma in skip_libs
- Fix a segfault while checking hard float in arm
> mcount: Fix a few bugs in libmcount

- cmds/replay.c
- utils/symbol.c
This patch only changes whitespaces to tabs and no functional change is
applied.
> uftrace: Fix coding style from whitespaces to tabs

- uftrace.c
This patch is to fix segfault in --opt-file as follows:
```
$ cat opts
--no-pager -D 3 t-abc
$ uftrace --opt-file opts
2.193 us [ 56595] | __monstartup();
1.176 us [ 56595] | __cxa_atexit();
[ 56595] | main() {
[ 56595] |   a() {
2.137 us [ 56595] |     b();
3.663 us [ 56595] |   } /* a */
4.653 us [ 56595] | } /* main */
WARN: Segmentation fault
Segmentation fault (core dumped)
```
Fixed: #709
> uftrace: Fix segfault when --opt-file is used

- utils/debug.c
In some environments, path resolution is failed so it gets crashed while
checking if it's busybox or not.
This patch adds a fail safe routine for such cases.
> utils: Fix segfault while busybox checking

- Makefile
It'd be useful to enable leak sanitizer for better leak check.
For simplicity, this switch is on when ASAN=1 is used.
> build: Add -fsanitize=leak when ASAN=1 is used

- libmcount/internal.h
- libmcount/plthook.c
Since GOT section is not well explained in the code, it might be
difficult to read and understand the code by general developers.
This PR adds some useful explanation for GOT section for better
understanding and it also changes the cryptic index number to got_idx.
It also refines some debug messages in plthook.
> plthook: Add some comments and refine debug msg

- cmds/record.c
This code seems to have attempted to return the full installation path.
However, the return code is missing. If it does not return here, strcpy
will only return the name of libmcount only from below line. therefore,
added returning code.
> record: Add the missed returnning code

- scripts/strings.py
argstr.py is to display unique string collected from arguments and
return values.
It displays all the strings collected at runtime as follows:
```
$ uftrace script -S scripts/strings.py --record /usr/bin/uptime
00:05:01 up 37 days, 13:16, 12 users,  load average: 4.94, 4.85, 4.90
"procps-ng"
---
"C"
---
"phsV"
---
"/proc/uptime"
---
"00:05:01 up 37 days, 13:16, 12 users,  load average: 4.94, 4.85, 4.90"
---
"en_US.UTF-8"
---
"NULL"
---
"/usr/share/locale"
---
"/proc/loadavg"
---
```
In many cases, same strings are repeatedly collected during funtion
tracing so this tool can be useful when observing their unique set.
> script: Add script/strings.py to print runtime strings

- cmds/tui.c
This pull request adds tui current position to lower right corner.
By counting the last_index of tui_window at each _init,
it is possible to show position of current index in percentage.
(tui_*_init)
On graph_fold (collapse, expand), longest_child, Enter Key events,
tui will recalculate the last_index to adjust position.
By default, when width(COLS) is not enough to show message at footer,
current index position will be hide automatically.
```
$ uftrace tui
0.256 us :     └─(1) fflush
uftrace graph: top: 232 depth: 6, curr: 252 depth: 0 last: 252             100%
$ uftrace tui
149.399 us :  └─(1) main
148.174 us :     ├─(1) printf
uftrace graph: /home/vault19/workspace/uftrace-data/simple-test/hello.c [line:3
```
Fixed: #625
> tui: added current position to footer

- libmcount/plthook.c
This PR applies the following changes:
- plthook: Fix size format in debug message
- plthook: Refine plthook exit debug message
- plthook: Add some explanation about GOT patching
Before:
```
plthook: [idx: 2] enter 4005b0: (null) (mod: 7f2869c4f168)
plthook: [idx: 2] exit  0: __monstartup
plthook: [idx: 4] enter 4005d0: (null) (mod: 7f2869c4f168)
plthook: [idx: 4] exit  0: __cxa_atexit
```
After:
```
plthook: [idx: 2] enter 4005b0: __monstartup@plt (mod: 7f37a39e6168)
plthook: [idx: 2] exit  400671: __monstartup     (resolved addr: 7f37a3590bf0)
plthook: [idx: 4] enter 4005d0: __cxa_atexit@plt (mod: 7f37a39e6168)
plthook: [idx: 4] exit  400575: __cxa_atexit     (resolved addr: 7f37a31f7280)
```
> plthook: Fix size format and refine debug message

- libmcount/mcount.c
The mtd_key deletion in mcount_cleanup() sometimes makes other thread
get crashed because they may try to get mtdp based on this mtd_key after
being deleted.  The error message is as follows:
plthook_exit: Assertion `!check_thread_data(mtdp)' failed.
The expected behavior is to call mcount_cleanup() after all the other
threads are destoryed, but it doesn't work as expected in some cases.
Since this key deletion is not that important, it'd be better not to do
it until we find a better solution.
> mcount: Fix mtdp assertion failure in plthook_exit

- cmds/record.c
This PR applies the following misc changes:
- record: Fix currently broken --nop option
- record: Check binary before creating uftrace.data
> record: Fix --nop option and relocate check binary

- cmds/record.c
It'd be better to have a task name for writer threads.
> record: Set writer thread name to "WriterThread"

- cmds/record.c
Current working directory can be changed during (shell) scripts execution
due to internal chdir() inside scripts.
If it is changed, the problem that uftrace.data can't be found can occur:
```
$ uftrace record --force ./configure
mcount: /home/honggyu/work/uftrace/libmcount/record.c:1093:record_proc_maps
ERROR: cannot open for writing maps file: No such file or directory
```
Because of trying to create "uftrace.data/sid-xxxxx.map" of which the prefix
is a relative path. So convert uftrace data directory path that can be
relative to an absolute path in tracing (shell) scripts case.
Fixed: #745
> record: Use absolute path of uftrace data directory when tracing (shell) scripts

- libmcount/mcount.c
It seems that there was a mistake when refactoring mtdp recursion guard.
It makes a segfault in many big programs because mtdp->recursion_guard
is accessed when mtdp is NULL.
Since recursion guard can be properly managed inside mcount_prepare(),
this patch simply removes the problematic code.
Fixed: #753 #638 #752
> mcount: Fix incorrect mtdp recursion handling

- cmds/record.c
Currently uftrace explicitly requires to have a correct pathname, so it
has to be used with full pathname as follows:
$ uftrace --force /usr/bin/python -c ''
This patch allows the user can provide the command name, which is placed
one of directories in PATH environment.
So uftrace can be simply used as follows:
$ uftrace --force python -c ''
It'd be helpful especially when tracing with -P option and it will make
easier to use full dynamic tracing feature as follows:
$ uftrace -P. -a python -c 'print("Hi, Python")'
Closes: #474
> record: Find the execution binary in PATH

- arch/i386/Makefile
This patch is to fix a build error for i386 in x86_64 machine.
```
$ ARCH=i386 CFLAGS=-m32 LDFLAGS=-m32 ./configure
...         prefix: /usr/local
...         libelf: [ on  ] - more flexible ELF data handling
...          libdw: [ on  ] - DWARF debug info support
...   libpython2.7: [ OFF ] - python scripting support
...    libncursesw: [ OFF ] - TUI support
...   cxa_demangle: [ on  ] - full demangler support with libstdc++
...     perf_event: [ on  ] - perf (PMU) event support
...       schedule: [ on  ] - scheduler event support
$ make
CC       arch/i386/cpuinfo.o
LINK     arch/i386/uftrace.o
ld: Relocatable linking with relocations from format elf32-i386
(/home/uftrace/arch/i386/cpuinfo.o) to format elf64-x86-64
(/home/uftrace/arch/i386/uftrace.o) is …
```
> build: Fix a build error for i386 in x86_64 machine

- Makefile
libmcount*.so don't need to have executable permission on its stack.
It can make some difference in the original programs by having
executable permission on its stack.
For example, there is a failed unittest in chrome because of it.
$ uftrace record ./base_unittests --gtest_filter=ProcMapsTest.ReadProcMaps
> build: Do not set stack memory as executable

- utils/kernel.c
It was missing to update the fix for caller filter with time filter as
written in the following commit.
7dc6915 fstack: Fix caller filter with time filter
Fixed: #622
> kernel: Fix caller filter with time filter

- arch/i386/mcount-dynamic.c
This patch is to fix the following build error.
```
arch/i386/mcount-dynamic.c:105:5: error: conflicting types for ‘mcount_patch_func’
int mcount_patch_func(struct mcount_dynamic_info *mdi, struct sym *sym)
^
In file included from arch/i386/mcount-dynamic.c:9:0:
libmcount/internal.h:431:5: note: previous declaration of ‘mcount_patch_func’ was here
int mcount_patch_func(struct mcount_dynamic_info *mdi, struct sym *sym,
struct mcount_disasm_engine *disasm)
^
Makefile:28: recipe for target 'arch/i386/mcount-dynamic.op' failed
```
> i386: Fix a build error in mcount_patch_func

- arch/x86_64/mcount-dynamic.c
- libmcount/mcount.c
clang compiler doesn't allow the following syntax:
```
warning: adding 'int' to a string does not append to the string
strncmp(spec, "SIGRTM" + off, 6 - off)
~~~~~~~~~^~~~~
```
There are a few more warnings as follows:
```
warning: passing 'unsigned char *' to parameter of type 'char *'
converts between pointers to integer types with different sign
__builtin___clear_cache(origin_code_addr,
^~~~~~~~~~~~~~~~
warning: passing 'unsigned char *' to parameter of type 'char *'
converts between pointers to integer types with different sign
origin_code_addr + origin_code_size);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This patch is to avoid such warnings.
Fixed: #764
> build: Fix a few warnings in clang build

- misc/prototypes.h
- utils/auto-args.h
This patch adds the prototypes of the following functions.
```
int clock_getres(clockid_t clk_id, struct timespec *res);
int clock_gettime(clockid_t clk_id, struct timespec *tp);
int clock_settime(clockid_t clk_id, const struct timespec *tp);
```
Let's say there is an example related to clock in C++ chrono as follows:
```
$ cat chrono_clock.cc
#include <chrono>
int main()
{
std::chrono::system_clock::now();
std::chrono::steady_clock::now();
std::chrono::high_resolution_clock::now();
}
```
It's very easy to see how each C++ chrono class internally calls
clock_gettime() as follows:
```
$ g++ -std=c++11 -pg chrono_clock.cc
$ uftrace -la -f none --no-comment a.out
main() {
std::chrono::_V2::system_clock::now() {
clock_gettime(CLOCK_REALTIME, 0x7ffd800ee4c0) = 0;
} …
```
> misc: Add clock_gettime family to misc/prototypes.h

- INSTALL.md
- README.md
- doc/uftrace.html
This PR updates README page with the following changes:
- slide: Fix a broken link to clang dumped html page
- doc: Add flame-graph chart to README.md
- doc: Move build guide to upper part of README.md
- doc: Refine install description
https://github.com/honggyukim/uftrace/tree/doc/readme-update
> doc: readme update

- libmcount/mcount.c
- libmcount/plthook.c
Currently, each entry function changes the value of errno when
initializing mcount thread data. The problem is that since errno is
shared with the target program, it affects the execution of the target
program. therefore, added some code to solve this problem and to prevent
this happening never again.
> mcount: Add code to store the errno from each entry

- utils/symbol.c
It's better to use a common routine for checking if it's the end of
symbol.  It also fixes a minor warning in fprintf type mismatch.
> symbol: Combine common check into is_symbol_end

- libmcount/plthook.c
This patch is to fix the following build error for ARM arch.
libmcount/plthook.c:899:20: error: 'errno' undeclared
> build: Fix a build error due to missing errno.h

- arch/aarch64/mcount.S
- arch/aarch64/plthook.S
Current implementation for mcount_return and plthook_return only reserve
x0 register assuming the size of return value is enough with 8 bytes.
But some functions may have a return type in struct and its size is more
than 8 bytes as following example:
```c
struct { int64_t quot, int64_t rem}
__aeabi_ldivmod(int64_t numerator, int64_t denominator) {
int64_t rem, quot;
quot = __divmoddi4(numerator, denominator, &rem);
return {quot, rem};
}
```
In this case, we might partially lose return values because the return
value is stored in x0 and x1 registers to keep 16 bytes in the return
type of struct { int64_t quot, int64_t rem}.
So this patch fixes to keep both x0 and x1 registers to prevent such
problems.
It's also required to save d0 and d1 VFP registers in return hook.
This patch is inspired …
> aarch64: Handle struct return type by keeping more regs on stack

- libmcount/dynamic.c
- tests/runtest.py
- tests/s-dynmain.c
- tests/s-libdyn1.c
- tests/s-libdyn2.c
- tests/t224_dynamic_lib.py
the patch function functionally was previously only applicable to main
binary functions. However, it can also patch the functions of the
external module after the "Full-Dynamic" update. so, this PR make this
possible through the '-p' option.
Usage:
```
$ uftrace -P.@libv8.so v8_shell
```
Write the name of the function to be patched before @ and write the name
of the module containing the function.
> dynamic: support for patching external modules with the full-dynamic

- tests/s-sleep2.c
- tests/t226_default_opts.py
- uftrace.c
- uftrace.h
- utils/utils.c
This introduces a new file "default.opts" in uftrace.data directory.
The file "uftrace.data/default.opts" will contain the default options to
be applied during running analysis commands.
In some cases, the record time filters are not properly applied for
analysis commands especially for kernel and event records.
It can be fixed by applying the record time filter again for analysis
commands.
Fixed: #658 #739
> uftrace: Introduce uftrace.data/default.opts file

- utils/demangle.c
- utils/dwarf.c
- utils/symbol.c
- utils/utils.h
It'd be better to distinguish between mcount and plthook related debug
messages because they are directly related to program execution.
It's better not to print too many symbol, dwarf, and demangle messages
when we want to see where the program is segfaulted.
> utils: Add pr_dbg4 and use it for trivial messages

- cmds/record.c
In some cases, the following message is printed in a normal execution.
WARN: Didn't you run 'make install' ?
/home/root
The message is printed if libmcount.so is not found the installtion
path, but it can be used anywhere especially in embedded environments
that use read-only file system.
It seems that specifying the basename of libmcount.so is enough for
LD_PRELOAD, it'd be better to remove this message.
But if libmcount.so is found in the installtion path, it has the higher
priority of use.
Fixed: #796
> record: Remove a message for installtion path check

- arch/arm/mcount-support.c
As of now, record command always gets segfault in arm environment.
It's a regression that was introduced by the following commit.
d8eb70b4 symbol: Use module symbol table in find_symtabs()
This patch fixes the problem by adding map start address.  In addition
to this, it removes the code for cache lookup because it's not
thread-safe code.
Fixed: #807
> arm: Fix segfault by adjusting map start address

- misc/install-deps.sh
In some old distros such as Ubuntu 14.04, capstone is not provided.
In this case, the entire package installation gets failed.
```
$ sudo ./misc/install-deps.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libcapstone-dev
```
To prevent such problems, it'd be better to add capstone installtion
separetely so that it doesn't affect other pacakge installation.
> misc: Add capstone package separately

- cmds/record.c
- libmcount/mcount.c
In some cases, it's difficult to analyze a bug report based on logfile
output because it doesn't contain some critical messages, which are
printed by pr_color.  In most cases, such colored messages are crash
points, but it's difficult to match where the program gets segfault
among the long list of debug messages.
This patch makes pr_color print message to logfp as well as outfp only
if logfp is not stderr so that it doesn't print duplicate message.
> utils: Print pr_color to logfp as well

- misc/run-lcov.sh
The changed usage of misc/run-lcov.sh is as follows:
```
$ ./misc/run-lcov.sh -h
Usage: ./misc/run-lcov.sh [<options>]
-h          print this message
-o <DIR>    set output report dir as <DIR>            (default: coverage.html)
-b          generate the report with branch coverage  (default: off)
```
> misc: Refactor run-lcov.sh script for branch on/off

- arch/x86_64/mcount-insn.c
Since it's hard to predict the target of an indirect jump, we just disallow patching it for now.
Allowing it may cause a thread to jump to the prologue and corrupt the execution. 
Signed-off-by: Anas Balboul <anasbalbo@gmail.com>
> dynamic: Disallow patching functions with an indirect jump

- cmds/info.c
- cmds/record.c
- uftrace.c
Hello,
In the process of using the record function, a memory leak occurs.
So, I added a missing "free()" function.
asprintf() man page:
```
This pointer should be passed to free(3) to release the allocated storage when it is no longer needed.
```
realloc() man page:
```
The free() function frees the memory space pointed to by ptr, which must have been returned by a previous call to malloc(), calloc() or realloc(). Otherwise, or if free(ptr) has already been called before, undefined behavior occurs. If ptr is NULL, no operation is performed.
```
valgrind log:
```
$ valgrind --leak-check=full uftrace record -P. ./yara my_first_rule my_first_rule
==15195== Memcheck, a memory error detector
==15195== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==15195== Using …
```
> uftrace : fix memory leak

- uftrace.c
This patch is to fix segfault in --logfile.
If logfd is NULL, set logfd to stderr before calling pr_err().
Fixed: #853
> uftrace: Fix segfault when given logfile name is already taken by a directory

- arch/x86_64/mcount-insn.c
check_unsupported function is designed to disallow jumps to patched
function prologue. but insn_check given as argument has been not setted
the value before using it. following the context, copy_size could be
used at here.
> dynamic: fix miss used insn_check

- Makefile
This patch adds docdir variable to make it changable.  It could be used
to store translated versions of man pages.
> build: Add docdir to make for later usage

- configure
> uftrace: configure script exits when OS is not Linux

- cmds/dump.c
- cmds/info.c
- cmds/replay.c
- utils/fstack.h
- utils/utils.c
- utils/utils.h
Remove single quote escaping logic
And change function name from 'strquote' to 'json_quote'
After change
```
$ uftrace record -t 1ms ./python -c "print('Hello')"
$ uftrace info | grep cmdline
$ uftrace dump --chrome | grep command_line
"command_line":"uftrace record -t 1ms ./python -c print('Hello')"
```
I check that visualized trace output is successfully opened.
Fixed: #857
> util : Change quote escaping function

- cmds/report.c
Hello,
In the process of using the report function, a memory leak occurs.
The memory allocated by find_or_create_node() is not freed.
So, I added `free()` function.
valgrind log:
```
$ valgrind --leak-check=full uftrace report --no-pager
==21644== Memcheck, a memory error detector
==21644== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==21644== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==21644== Command: uftrace report --no-pager
==21644==
Total time   Self time       Calls  Function
==========  ==========  ==========  ====================
9.730 ms   70.896 us           1  main
8.167 ms    2.005 us           1  yr_compiler_get_rules
4.551 ms  320.210 us           1  yr_arena_duplicate
4.139 ms    4.139 ms           3  linux:schedule
3.611 ms …
```
> report: Fix memory leak in print_and_delete()

- misc/install-deps.sh
Hi there,
I'm sorry about the delay. I was completely unaware of the new issue (#886, #887) about adding docker files. This patch is for Arch Linux support in `install-deps.sh`.
Please review this commit and let me know if anything matters.
Thank you! 😃 
Fixed: #883
Signed-off-by: Handong Choi <wschd770@gmail.com>
> misc: Add Arch Linux support for required dependency install

- misc/docker/arch/Dockerfile
- misc/docker/centos/7/Dockerfile
- misc/docker/ubuntu/16.04/Dockerfile
- misc/docker/ubuntu/18.04/Dockerfile
Using Dockerfiles, you can test uftrace on multiple distros easily.
docker build -t <tagname> .
This fixes #886
> misc: Add Dockerfiles for arch, centos, ubuntu

- utils/fstack.c
it's only possible to be NULL when the data is broken. 
Anyway we need to protect from it.
Fixed : #882
> fstack: Fix Null Pointer Dereference in setup_task_filter()

- arch/aarch64/mcount-support.c
- arch/arm/mcount-support.c
- arch/i386/mcount-support.c
- arch/x86_64/mcount-support.c
- libmcount/internal.h
- libmcount/record.c
- tests/t231_arg_bound.py
If the given argument index is out of memory or inaccessible, a segfault will occur.
I added code to check the validity of the memory address before accessing the address.
Before :
```
$ uftrace -A puts@arg123123123 ./simple
WARN: Segmentation fault: address not mapped (addr: 0x7ffc65604290)
WARN: Backtrace from uftrace:
WARN: =====================================
WARN: [1] (puts[5597527fe660] <= main[5597527fe86b])
WARN: [0] (main[5597527fe838] <= __libc_start_main[7feaa464bb97])
0.840 us [ 13506] | __monstartup();
0.305 us [ 13506] | __cxa_atexit();
[ 13506] | main() {
[ 13506] |   puts() {
uftrace stopped tracing with remaining functions
================================================
task: 13506
[1] puts
[0] main
```
After : …
> mcount: fix segfault in mcount_get_stack_arg()

- tests/runtest.py
The current runtest.py works with the full capable cpus, but it doesn't
have to create such amount if the number of tests are lower than the
cores.  This fixes the problem by limiting the number bounded to the
number of testcases.
Before:
$ ./runtest.py 001
Start 1 tests with 40 worker
...
After:
$ ./runtest.py 001
Start 1 tests with 1 worker
...
> tests: Limit workers bounded to testcases

- uftrace.c
remove description about default value of option -K
because it doesn't actually have a default value.
Fixed: #901
Signed-off-by: Yeomin Nam <y.minn13@gmail.com>
> record: Fix description for option -K

- cmds/info.c
- utils/fstack.c
- utils/fstack.h
Add option mode checking logic to setup filter option.
After apply this patch, `uftrace info` do not print message whether or not filter is applied.
Fixed: #899
> info: Check option mode when setup filter

- libmcount/record.c
When using ARG_FMT_STD_STRING, the memory address was not checked properly.
Added code to check for memory address using check_mem_region().
Fixed: #905
> record: Fix segfault when using std::string fmt

- arch/x86_64/dynamic.S
Hello.
I corrected the typos.
Thanks.
Changes:
`occured` -> `occurred`
> mcount: Fix a typo in comment

- cmds/record.c
Since strnpy is safer than strcpy,
I changed `strcpy(lib, libmount)`
to `strncpy('lib, libmount, sizeof(lib))`
Signed-off-by: kangtegong <tegongkang@gmail.com>
> record: Modified strcpy to strncpy

- utils/symbol.c
It looks weird to read the number of symbols to 'addr' variable.
So it's better to use proper variable names for better readability.
```
$ cat uftrace.data/libc-2.23.so.sym
000000000001f7d0 P realloc
000000000001f7e0 P __tls_get_addr
000000000001f7f0 P memalign
...
```
> utils: Use a proper name for symtab->nr_alloc

- doc/uftrace-record.md
I just found unnecessary ')' in line 550, DYNAMIC TRACING [section](https://github.com/namhyung/uftrace/blob/master/doc/uftrace-record.md#dynamic-tracing).
Signed-off-by: Handong Choi wschd770@gmail.com
> doc: Fix typo error in uftrace-record.md

- utils/utils.c
This PR fixes a number of segfaults caused when parsing options from a file ( `--opt-file`). Relevant issue #914 .
Note that there are still some leaks related to option parsing but they are not particularly tied to `setargs()`. They are caused by `exit()`-ing when an executable cannot be opened. This probably needs a new issue opened.
Signed-off-by: George Karlos gkarloscodes@gmail.com
> utils: Fix segfaults caused by setargs()

- libmcount/plthook.c
Hello.
I think, the if conditional statement in libmcount/plthook.c on line 246 is useless.
If `plt_found` is not true, it is processed on line 202.
So, The if conditional statement is always true.
https://github.com/namhyung/uftrace/blob/519ecef22613cca6260e8a2b52b5cf8a2903b087/libmcount/plthook.c#L202-L249
Thanks.
> plthook: Remove dead code in find_got

- uftrace.c
Fixed `avaiable` to `available`
> uftrace: Fix typo in uftrace_options

- cmds/tui.c
> tui: Fix typo in comment

- uftrace.c
Added code to free for `opts->sig_trigger`
Fixed: #963
> uftrace: Fix memory leak in opts

- misc/install-deps.sh
./misc/install-deps.sh: Syntax error: ")" unexpected (expecting ";;")
The commit ffb70d3 introduced the problem.
Signed-off-by: sungho-yoon <lacrimak3@gmail.com>
> misc: Fix missing ;; in install-deps.sh

- utils/dwarf.c
> utils: Fix compilation warnings when HAVE_LIBDW is not defined

- cmds/info.c
Fixed the stack overflow by inserting null byte at the end of the string.
Fixed: #939
> info: Fix stack buffer overflow when reading cmdline

- utils/fstack.c
align size before calling xrealloc.
Fixed: #919
> fstack: fix heap buffer overflow in read_task_arg

- cmds/dump.c
- cmds/record.c
Hi, I just found some typo issues. Also, I added a comment for the chrome output like the flamegraph and graphviz.
Signed-off-by: Henry Choi <wschd770@gmail.com>
> uftrace: Fix typo and add comment for --chrome dump

- cmds/info.c
- utils/symbol.c
This isn't really accurate right. fread() doesn't always
return 0 in error. It could return < number of elements
and set errno.
Fixed: #952
> uftrace: Fix fread() error handling

- cmds/record.c
- cmds/recv.c
- utils/compiler.h
- utils/utils.h
This fixes following warnings and errors:
```console
/data/data/com.termux/files/home/uftrace/utils/compiler.h:50:10: warning: '__noreturn' macro redefined [-Wmacro-redefined]
^
/data/data/com.termux/files/usr/include/sys/cdefs.h:86:9: note: previous definition is here
#define __noreturn __attribute__((__noreturn__))
/data/data/com.termux/files/home/uftrace/utils/utils.h:237:10: warning: 'ntohq' macro redefined [-Wmacro-redefined]
^
/data/data/com.termux/files/usr/include/sys/endian.h:69:9: note: previous definition is here
#define ntohq(x) __swap64(x)
/data/data/com.termux/files/home/uftrace/utils/compiler.h:49:10: warning: '__used' macro redefined [-Wmacro-redefined]
^
/data/data/com.termux/files/usr/include/sys/cdefs.h:90:9: note: previous definition is here
#define __used …
```
> android: Fix some of compile warnings and errors in android bionic

- cmds/record.c
Using full dynamic tracing, uftrace could be worked with binary files
which are not compiled with -pg or -finstrument-functions flag
but, MCOUNT_MSG does not have explaination for it.
Fixed:#760
Signed-off-by: JoonhoRyu <ruujoon93@gmail.com>
> record: Modify MCOUNT_MSG in record.c

- doc/ko/uftrace.md
uftrace didn't support korean man page.
this will help the people who use korean to use it easily
Signed-off-by: Joonho Ryu <ruujoon93@gmail.com>
> doc/ko/uftrace.md: Korean translation

- cmds/replay.c
Fixed to check if string is 4 bytes long before comparing it to null_str.
Removed unnecessary code for newline.
Fixed: #993
> replay: Fix heap buffer overflow in get_argspec_string()

- cmds/info.c
Fixed `\n` to be replaced with `space`.
Fixed: #996
> info: Fix error when reading multiple cmdline

- uftrace.c
Fixed `opts->cmd_line` allocated in `parse_cmdline()` to be freed.
Fixed: #1005
> uftrace: Fix memory leak in run_cmd

- cmds/dump.c
Fixed `acctually` to `actually`
> dump: Fix typo in comment

- libmcount/mcount.c
- libmcount/plthook.c
- libmcount/record.c
- libmcount/wrap.c
Hi there,
I just found some typo and grammar issues.
Signed-off-by: Handong Choi <wschd770@gmail.com>
> uftrace: Fix typo in comment

- arch/x86_64/mcount-insn.c
I think that orig_size should be used here instead of copy_size.
Signed-off-by: Anas Balboul <anasbalbo@gmail.com>
> dynamic: Fix a bug disallowing some functions to be patched

- .travis.yml
- misc/install-deps.sh
With this change you will immediately know
when change to install-deps.sh introduces some errors especially in Ubuntu.
> uftrace: Fix .travis.yml to use install-dep.sh

- .travis.yml
- tests/unittest.c
So far tests/unittest has always returned EXIT_SUCCESS even if there is a failed test.
I modified tests/unittest.c to return EXIT_FAILURE when there is at least
one of FAILED, SIGNALED, UNKNOWN test.
I also modified .travis.yml to build unittest with ASAN=1 and this reveals some new memory bugs.
> tests: Make unittest stricter

- doc/uftrace-graph.md
- doc/uftrace-replay.md
- doc/uftrace-report.md
- doc/uftrace-script.md
- doc/uftrace-tui.md
I updated the description of --tid option.
'thread' --> 'task'
The related commands are graph, replay, report, script and tui.
> doc: Update description of --tid option in related commands

- doc/uftrace-graph.md
- doc/uftrace-live.md
- doc/uftrace-record.md
- doc/uftrace-report.md
Hi, I just found some typo and grammar issues.
Also, some lines of the document should be ignored markdown formatting, so I fixed it by using `\`.
Signed-off-by: Handong Choi <wschd770@gmail.com>
> doc: Fix typo and grammar in doc files

- doc/ko/README.md
Hello, I translated README.md to Korean!
https://github.com/kangtegong/uftrace/blob/README-ko/doc/ko/README.md
If you find any awkward expressions or mistakes,
please let me know! :)
Thank you
Signed-off-by: kangtegong <tegongkang@gmail.com>
> doc/ko: Translate README to Korean

- misc/install-deps.sh
- tests/s-malloc-fork.c
- tests/s-malloc-hook.c
- tests/s-malloc-tsd.c
- tests/s-malloc.c
- tests/t062_arg_char.py
Since raspbian uses the same package install commands, it just simply
adds raspbian to ubuntu case.
It also applies some partial test fixes.
> tests: Fix some tests for ARM 32-bit raspbian

- cmds/script.c
- doc/ko/uftrace-script.md
- doc/uftrace-script.md
Hi there,
I fixed brackets to parentheses in the usage command and added extra description to uftrace-script man page.
Fixed: #976
Signed-off-by: Handong Choi <wschd770@gmail.com>
> uftrace: Fix usage description for script --record option

- cmds/live.c
- doc/ko/uftrace-live.md
- doc/uftrace-live.md
The live command is used to record the data in a temporary directory and
discards it after the execution.
Someone might want to see the replay output immediately, but also wants
to keep the recorded data to run another analysis command.
The current --record option is only used for script command, but can
also be used for live command for this purpose.
```
$ rm -rf uftrace.data
$ uftrace --record -F main t-abc
[109070] | main() {
[109070] |   a() {
[109070] |     b() {
[109070] |       c() {
0.933 us [109070] |         getpid();
3.617 us [109070] |       } /* c */
4.207 us [109070] |     } /* b */
4.844 us [109070] |   } /* a */
9.650 us [109070] | } /* main */
$ uftrace replay
[109070] | main() {
[109070] |   a() {
[109070] |     b() {
[109070] |       c() {
0.933 us [109070] | …
```
> live: Reuse --record option to keep recorded data

- cmds/tui.c
This patch reuses --report option in tui command so that it can be used
to start the tui window in report mode.
Closes: #1037
> tui: Use --report option to start with report mode

- utils/auto-args.c
- utils/filter.c
- utils/filter.h
Fix memory leaks in argument enum string.
Fixed: #920
> utils: Fix memory leaks in tui

- Makefile
This commit tie flags that appear in common into {TRACE,COVERAGE,ASAN}_CFLAGS
Additionally, it adds an UndefinedBehaviorSanitizer flag.
> build: Reduce common code, add SAN flag

- utils/perf.c
Fix memory leak with setup_perf_data.
This patch will prevent duplicate allocation of perf data.
Currently, we setup perf data both when opening data files
and processing uftrace information.
- `open_data_file` in `utils/data-file.c`
- `process_uftrace_info in `cmds/info.c`
This patch will prevent duplicate allocation of perf data.
Fixed: #1024
> utils: Fix memory leak with perf data in tui

- cmds/replay.c
- cmds/script.c
- utils/fstack.c
This PR fixes memory leaks and heap buffer overflow problems including the following commits
* fstack: Fix a heap buffer overflow
* replay: Fix a memory leak in event name
* script: Fix a memory leak in a struct strv variable
Fixes: #803 and other problems found in tests
> Fix memory leaks and heap buffer overflows

- cmds/dump.c
This commit checks that the inverted_time function pointer is non-NULL
before calling it in do_dump_replay.
Signed-off-by: Colin Lord <clord@xcom-labs.com>
> dump: Fix segfault in do_dump_replay on inverted timestamps

- cmds/graph.c
- cmds/replay.c
- cmds/tui.c
- utils/field.h
Since kernel address is represented in 64-bits, it cannot fit in the
current 12 width field and it makes the output ugly.
```
$ uftrace replay -f +addr
[191538]       40068f | main() {
[191538]       4004f0 |   puts() {
6.337 us [191538] ffffffff812211d0 |     sys_newfstat();
7.507 us [191538] ffffffff8106dba0 |     __do_page_fault();
19.908 us [191538] ffffffff8121c910 |     sys_write();
47.339 us [191538]       4004f0 |   } /* puts */
48.488 us [191538]       40068f | } /* main */
```
This patch uses effective_addr function to cut the higher 16 bits for
better address display in replay, graph, and tui commands.
Fixed: #989
> field: Fix the output of -f addr to fit in the width

- cmds/graph.c
- cmds/replay.c
- doc/uftrace-graph.md
- tests/t230_graph_task.py
- utils/field.c
- utils/field.h
The current graph --task output show tid with task name, but it looks
confusing because it doesn't explain the number is tid info.
So it'd be better to show tid in a TID field and it looks more clear.
In addition, this patch also changes TASK to TASK-NAME in the header.
Before:
```
$ uftrace graph --task
========== TASK GRAPH ==========
9.002  m    1.041  m : [168086] chrome
:  +-[168130] chrome
:  |
7.018  m    1.020  m :  +----[168131] chrome
:  |     |
2.039  m    2.802  s :  |     +----[168200] chrome
:  |     |     +-[168201] chrome
2.039  m   16.797 ms :  |     |     +-[168202] TaskSchedulerFo
2.039  m  432.881 ms :  |     |     +-[168204] Chrome_ChildIOT
...
```
After:
```
$ uftrace graph --task
========== TASK GRAPH ==========
7.018  m   25.892  s  [168086] : chrome
[168130] : +- …
```
> graph: Enhance task graph with field, time-filter, color

- arch/x86_64/mcount-dynamic.c
This patch align mprotect's address to the page size. It solves issue (or part of it) #1035: full dynamic tracing failure for V8.
> dynamic: Fix problem with mprotect's address that may be invalid

- utils/script-luajit.c
- utils/script-python.c
This PR includes the script changes below.
- script: Add a debug message to show loaded library
- script: Do not use pr_dbg at each luajit entry and exit
- script: Do not use pr_warn when luajit call failed
> script: Refine debug messages for python and luajit

- tests/t189_replay_field2.py
- tests/t196_chrome_taskname.py
- tests/t221_taskname_time.py
Since some of the tests require to read perf event, they may always be
failed if /proc/sys/kernel/perf_event_paranoid is 3 by default.
This patch adds a check routine if it has a permission for reading
perf event.  Otherwise, those tests are just skipped.
Before:
```
189 replay_field2       : NG NG NG NG NG NG NG NG NG NG
196 chrome_taskname     : NG NG NG NG NG NG NG NG NG NG
221 taskname_time       : NG NG NG NG NG NG NG NG NG NG
```
After:
```
189 replay_field2       : SK SK SK SK SK SK SK SK SK SK
196 chrome_taskname     : SK SK SK SK SK SK SK SK SK SK
221 …
```
> tests: Fix some tests by checking perf_event_paranoid

- utils/kernel.c
Replace versionsort() for non-libc environment such as bionic libc.
> utils: Replace versionsort() with custom comparison function.

- cmds/report.c
This patch is to fix the following report related tests.
```
$ ./runtest.py -j4 report
...
024 report_basic        : NG NG NG NG NG NG NG NG NG NG
025 report_s_call       : NG NG NG NG NG NG NG NG NG NG
046 report_task         : NZ NZ NZ NZ NZ NZ NZ NZ NZ NZ
090 report_recursive    : NG NG NG NG NG NG NG NG NG NG
092 report_tid          : NG NG NG NG NG NG NG NG NG NG
093 report_filter       : NG NG NG NG NG NG NG NG NG NG
094 report_depth        : NG NG NG NG NG NG NG NG NG NG
106 report_time         : NG NG NG NG NG NG NG NG NG NG
125 report_range        : NG NG NG NG NG NG NG NG NG NG
164 report_sched        : NG NG NG NG NG NG NG NG NG NG
216 no_libcall_report   : NG NG NG NG NG NG NG NG NG NG
```
Since the type of node->call is uint64_t, %lu is incorrectly used, so it
has to be …
> report: Fix report tests for i386

- tests/.gitignore
- tests/runtest.py
It'd be useful if abnormally finished test results are separately
collected because we don't have to see normally finished tests.
This patch makes runtest.py collect those abnormally finished results in
failed-tests.txt.
Here is the output in failed-tests.txt after running tests on x86_64.
```
052 nested_func         : OK OK OK OK OK NG NG NG NG NG
136 dynamic             : BI BI BI BI BI BI BI BI BI BI
151 recv_runcmd         : NG NG NG NG OK NG NG NG NG NG
162 pltbind_now_pie     : BI BI BI BI BI BI BI BI BI BI
182 thread_exit         : SG NG NG NG OK SG NG OK OK OK
184 arg_enum            : NG NG NG NG NG NG NG NG NG NG
```
> tests: Collect abnormally finished test results

- tests/runtest.py
- tests/s-malloc-fork.c
- tests/s-malloc-hook.c
- tests/s-malloc-tsd.c
- tests/s-malloc.c
- tests/t043_full_demangle.py
- tests/t051_return.py
- tests/t058_arg_int.py
- tests/t063_retval.py
- tests/t065_arg_order.py
- tests/t083_arg_float.py
- tests/t084_arg_mixed.py
- tests/t085_arg_reg.py
- tests/t086_arg_stack.py
- tests/t087_arg_variadic.py
- tests/t097_dump_basic.py
- tests/t098_dump_tid.py
- tests/t099_dump_filter.py
- tests/t100_dump_depth.py
- tests/t136_dynamic.py
- tests/t140_dynamic_xray.py
- tests/t223_dynamic_full.py
- tests/t232_dynamic_unpatch.py
- tests/t233_dynamic_unpatch2.py
This PR mainly fixes the problems when testing i386 under x86_64.
It fixes tests in i386 under x86_64 environment:
```
043 full_demangle       : NG NG NG NG NG NG NG NG NG NG
058 arg_int             : NG NG NG NG NG SK SK SK SK SK
063 retval              : NG NG NG NG NG SK SK SK SK SK
065 arg_order           : NG NG NG NG NG SK SK SK SK SK
083 arg_float           : NG NG NG NG NG SK SK SK SK SK
084 arg_mixed           : NG NG NG NG NG SK SK SK SK SK
086 arg_stack           : NG NG NG NG NG SK SK SK SK SK
087 arg_variadic        : NG NG NG NG NG SK SK SK SK SK
```
It fixes tests in arm 32-bit environment:
```
048 malloc_impl         : TM TM TM TM TM TM TM TM TM TM
058 arg_int             : NG NG NG NG NG SK SK SK SK SK
063 retval              : NG NG NG NG NG SK SK SK SK SK
065 arg_order …
```
> tests: Fix various test failures in 32-bit environment

- tests/t193_read_pmu_cycle.py
- tests/t194_read_pmu_cache.py
- tests/t195_read_pmu_branch.py
- tests/t227_read_pmu_cycle2.py
- tests/t228_read_pmu_cycle3.py
There are many pmu related tests, but the perf check rouintes are
missing, so they are all failed if the system doesn't have enough
value in `/proc/sys/kernel/perf_event_paranoid`.
This patch fixes the problem by checking and skipping the pmu tests.
Before:
```
193 read_pmu_cycle      : NG NG NG NG NG NG NG NG NG NG
194 read_pmu_cache      : NG NG NG NG NG NG NG NG NG NG
195 read_pmu_branch     : NG NG NG NG NG NG NG NG NG NG
227 read_pmu_cycle2     : NG NG NG NG NG NG NG NG NG NG
228 read_pmu_cycle3     : NG NG NG NG NG NG NG NG NG NG
```
After:
```
193 read_pmu_cycle      : SK SK SK SK SK SK SK SK SK SK
194 read_pmu_cache      : SK SK SK SK SK SK SK SK SK SK
195 read_pmu_branch     : SK SK SK SK SK SK SK SK SK SK
227 read_pmu_cycle2     : SK SK SK SK SK SK SK SK SK SK
228 …
```
> tests: Skip pmu tests with check_perf_paranoid()

- INSTALL.md
- configure
This PR introduces some useful configure options as follows:
```
--arch=<ARCH>         set target architecture              (default: system default arch)
e.g. x86_64, aarch64, i386, arm or thumb
--cross-compile=<CROSS_COMPILE>
Specify the compiler prefix during compilation
e.g. CC is overridden by $(CROSS_COMPILE)gcc
--cflags=<CFLAGS>     pass extra C compiler flags
--ldflags=<LDFLAGS>   pass extra linker flags
```
Since there is ordering problem using environmental variables and
configure options together, this recommends to use configure options
only.
Especially, --arch contains some useful builtin additional support in
i386 and thumb.  i386 automatically adds -m32 option to CFLAGS and
LDFLAGS and thumb is a pseudo architecture for Thumb mode in ARM
architecture.
Closes: #1095 …
> build: Add useful configure options

- doc/ko/uftrace-live.md
- doc/ko/uftrace-record.md
- doc/uftrace-live.md
- doc/uftrace-record.md
The options -U/--unpatch and -Z/--size-filter are missing in some man
pages so this patch adds them.
Closes: #1102
> doc: Add -U/-Z missing options for dynamic tracing

- libmcount/internal.h
- libmcount/mcount.c
In some cases, the target program might be crashed while running in the
deeply nested call.  In this case, the current implementation cannot
record its internal calls and lose most of the calls.
For example, there is an incorrected written factorial example.
```
$ cat factorial.c
int factorial(int n)
{
return n * factorial(n - 1);
}
int main()
{
return factorial(8);
}
```
The user expects the deeply nested calls, but it doesn't show anything
in the current implementation.
```
$ gcc -pg -g factorial.c
$ uftrace -a a.out
WARN: too deeply nested calls: 1024
2.010 us [ 36774] | __monstartup();
0.847 us [ 36774] | __cxa_atexit();
```
This patch make it flush the recorded data when the call is deeply
nested and it shows the internal …
> mcount: Flush data when call is deeply nested

- utils/graph.c
Add missing free to add_graph_exit when recover from fork.
This patch will remove memory leak when use graph command with fork.
Fixed: #1110
> utils: Fix memory leak in graph

- arch/aarch64/mcount-arch.h
- arch/aarch64/mcount-support.c
This PR fixes a few floating point argument/retval recording.
Here is an example program.
```c
$ cat float-test.c
#include <stdio.h>
float float_add(float a, float b)
{
fprintf(stderr, "float_add(%f, %f)", a, b);
return a + b;
}
double double_add(double a, double b)
{
fprintf(stderr, "double_add(%lf, %lf)", a, b);
return a + b;
}
int main(int argc, char *argv[])
{
double c;
c = float_add(-0.1, 0.2);
fprintf(stderr, " = %lf\n", c);
c = double_add(-0.11, 0.22);
fprintf(stderr, " = %lf\n", c);
return c > 0;
}
```
Before:
```
$ uftrace -a -F main a.out
float_add(1213624708152897478526956949371466656365453977070085167863541782041015626505309452532498268575431296447550982841406775763334082854912.000000, 0.000000) = 0.100000
double_add(-0.110000, 0.220000) = 0.110000
[  6041] | …
```
> aarch64: Fix floating point args recording

- utils/demangle.c
- utils/symbol.c
In most cases, demangler error is not a critical issue, but it looks
very annoying to see a lot of demangler failures in debug level 1.
In addition, symbol info can also be printed in a higher debug level.
This patch lowers the debug levels to hide messages which are not
related to tracing execution such as mcount and plthook.
> utils: Lower debug level in demangler and symbol

- tests/t022_filter_kernel.py
- tests/t079_replay_kernel_D.py
- tests/t081_kernel_depth.py
- tests/t103_dump_kernel.py
- tests/t104_graph_kernel.py
- tests/t111_kernel_tid.py
- tests/t132_trigger_kernel.py
- tests/t137_kernel_tid_update.py
- tests/t138_kernel_dynamic.py
- tests/t139_kernel_dynamic2.py
- tests/t143_recv_kernel.py
- tests/t174_replay_filter_kernel.py
Linux version check code have error, so this commit fix it.
Because Linux v4.17 (x86_64) changed syscall routines,
one commit add some codes for checking Linux version.
commit id: b4812af
However, this code have an error. If your Linux version is
more than 4.17 and less than 5.0, there is no error.
But my linux version is more than 5.0, so there is error.
The past commit(b4812af) fix test cases. The number is
022, 079, 081, 103, 104, 111, 132, 137, 138, 139, 143 and 174.
So I apply the new way of version check to that cases(12 cases).
This is my Linux environment.
```
$ uname -r
Linux kali 5.2.0-kali3-amd64 #1 SMP Debian 5.2.17-1kali2
(2019-10-17) x86_64 GNU/Linux
```
This is my test results. (before commit)
```
$ cd test
$ ./runtest.py
$ cat failed-tests.txt
Test case                 pg …
```
> tests: fix the way of checking linux version

- misc/install-deps.sh
Since kali uses the same package install commands, it just simply adds kali to ubuntu case.
Signed-off-by: Dohyun Kim <kimdo331@naver.com>
> misc: Add kali to install-deps.sh

- utils/dwarf.c
When use tui with fork, dinfo->locs can be overwritten.
This patch will remove memory leak when use tui with fork
Fixed: #1120
> utils: Fix memory leak in tui

- arch/arm/mcount-support.c
- libmcount/plthook.c
- libmcount/record.c
- tests/t083_arg_float.py
The designated initializer in C makes implicit memset internally in arm
architecture.  Due to the memset, VFP registers are clobbered
unexpectedly, so this patch fixes the problem by replacing the
designated initializer to explicit 'mcount_memset4'.
In addition, the offset of VFP registers were incorrect because the
following commit pushs d1 register on top of the original d0.
ffb69ce arm: Handle struct return type by keeping more regs on stack
So the offset is adjusted from -2 to -4 to cope with the change
Source:
```c
#include <stdio.h>
float float_add(float a, float b)
{
fprintf(stderr, "a = %f, b = %f\n", a, b);
return a + b;
}
int main(int argc, char *argv[])
{
double c;
c = float_add(-0.1, 0.2);
fprintf(stderr, "c = %f\n", c);
return c > 0;
}
```
Before:
```
$ uftrace -a -F main …
```
> arm: Fix floating point arguments in arm

- arch/x86_64/mcount-dynamic.c
In some environments, full dynamic tracing gets always crashed.
```
$ uftrace record -P. --debug-domain dynamic:3 t-abc
dynamic: dynamic patch type: t-abc: 0 (none)
dynamic: patch normal func: a (patch size: 9)
dynamic: patch normal func: b (patch size: 9)
dynamic: patch normal func: c (patch size: 9)
dynamic: patch normal func: main (patch size: 8)
dynamic: patched all (4) functions in 't-abc'
```
It works fine on many other machines, but gets crashed on some specific
machines.
It might has some read-only data in trampoline code, but the cleanup
phase sets the permission only with PROT_EXEC.
The reason is not 100% clear now, but it's verified that adding
PROT_READ permission fixes the crash problem.
Fixed: #1071
Signed-off-by: …
> dynamic: Fix a crash in x86_64 full dynamic tracing

- libmcount/mcount.h
- libmcount/wrap.c
- uftrace.c
- utils/utils.h
It'd be better to distinguish "wrap" domain from other debug messages.
Having this debug domain, users can easily see if there are some
wrapped functions such as dlopen as well.
It's especially useful if some problems are because of backtrace or
exception handling, etc.
This PR also adjusts debug messages in wrap domain as follows.
```
$ g++ -pg -o t-exception4 tests/s-exception4.cpp
$ uftrace record --force --debug-domain wrap:2 t-exception4
wrap: __cxa_throw: exception thrown from [2]
wrap: __cxa_begin_catch: exception catched begin on [1]
wrap: __cxa_end_catch: exception catched end
$ uftrace record --force --debug-domain wrap:3 t-exception4
wrap: __cxa_throw: exception thrown from [2]
wrap: mcount_rstack_reset_exception: [1] parent at 0x7fffc93355a8
wrap: …
```
> debug: Add a new debug domain for wrap

- tests/t079_replay_kernel_D.py
- tests/t080_replay_kernel_D2.py
- tests/t111_kernel_tid.py
- tests/t143_recv_kernel.py
This patch fixes some tests that are stuck or failed in aarch64.
Fixed: #1157, #1158
> tests: Fix stucked or failed tests in aarch64

- utils/kernel.c
TTBR is for page table setting and it is needed for security
enhancement against spectre/meltdown attacks.
post_ttbr_update_workaround() is better to be hidden not to
confuse general users unnecessarily.
Before:
```
$ uftrace -F main -k t-abc
[  4788] | main() {
1.041 us [  4788] |   post_ttbr_update_workaround();
[  4788] |   a() {
1.041 us [  4788] |     post_ttbr_update_workaround();
[  4788] |     b() {
0.521 us [  4788] |       post_ttbr_update_workaround();
[  4788] |       c() {
0.521 us [  4788] |         post_ttbr_update_workaround();
[  4788] |         getpid() {
0.521 us [  4788] |           post_ttbr_update_workaround();
1.042 us [  4788] |           sys_getpid();
1.042 us [  4788] |           post_ttbr_update_workaround();
6.771 us [  4788] |         } /* getpid */
0.521 us [ …
```
> kernel: Skip post_ttbr_update_workaround() in aarch64

- cmds/report.c
- cmds/tui.c
- doc/uftrace-report.md
- tests/t235_report_srcline.py
- uftrace.h
- utils/report.c
- utils/report.h
- utils/session.c
Show source line info of each function with loaded debug_info.
Fixed: #763
Could I leave 'Signed off' message after code review?
I think there are many other ways to implement this feature.
All comments are welcome.
> report: show source line info with --srcline option

- utils/kernel.c
If some cpus are offlined especially from the initial numbers, then
the current implementation fails to collect correct kernel-cpuXX.dat.
It's because it just simply counts the number of cpus, then collects
from cpu0 by looping over the number of cpus.
Here is the problematic cpu settings.
```
$ cat /sys/devices/system/cpu/possible
0-7
$ cat /sys/devices/system/cpu/offline
0-3,6-7
$ cat /sys/devices/system/cpu/online
4-5
```
In this case, uftrace has to collect kernel-cpu4.dat and kernel-cpu5.dat,
but it just collects kernel-cpu0.dat and kernel-cpu1.dat, which are
empty because they are offlined.
This patch fixes the problem by looping over all the cpus rather than
considering only online cpus.  It changes from _SC_NPROCESSORS_ONLN to
_SC_NPROCESSORS_CONF.
```
_SC_NPROCESSORS_ONLN
The …
```
> kernel: Properly handle offlined CPUs for kernel tracing

- utils/dwarf.c
- utils/dwarf.h
LoisHuang reported that the current implementation does not generate
source location info when the target binary is compiled with
-finstrument-functions even though it has debug info.
Binary compilation:
```
$ gcc -g -finstrument-functions -o t-abc.finst tests/s-abc.c
```
Before:
```
$ uftrace record -a t-abc.finst
$ cat uftrace.data/*.dbg
cat: cannot access 'uftrace.data/*.dbg': No such file or directory
```
After:
```
$ uftrace record -a t-abc.finst
$ cat uftrace.data/t-abc.finst.dbg
F: 73a a
L: 11 tests/s-abc.c
F: 77a b
L: 16 tests/s-abc.c
F: 7ba c
L: 21 tests/s-abc.c
F: 818 main
L: 26 tests/s-abc.c
```
Please note that it doesn't generate arguments information unnecessarily
because TRACE_CYGPROF type only has source location information.
Fixed: #1152
Signed-off-by: Honggyu Kim …
> dwarf: Produce srcline in .dbg for -finstrument-functions

- cmds/graph.c
- cmds/replay.c
- tests/t236_replay_srcline.py
- uftrace.c
- utils/field.c
- utils/field.h
Show source location of each function with loaded debug_info.
'-g' and '-pg' options are required when compiling an executable
to have source line information like this.
```
$ gcc -o t-abc -g -pg tests/s-abc.c
```
The '--srcline' option is required when using record command.
```
$ uftrace record --srcline t-abc
```
The '--srcline' option is also required when using replay command.
```
$ uftrace replay --srcline
1.483 us [  3237] | __monstartup();
0.658 us [  3237] | __cxa_atexit();
[  3237] | main() { [tests/s-abc.c:26]
[  3237] |   a() { [tests/s-abc.c:11]
[  3237] |     b() { [tests/s-abc.c:16]
[  3237] |       c() { [tests/s-abc.c:21]
3.711 us [  3237] |         getpid();
5.800 us [  3237] |       } /* c */ [tests/s-abc.c:21]
6.950 us [  3237] |     } /* b */ [tests/s-abc.c:16]
7.934 …
```
> replay: show source line info with --srcline option

- tests/t068_filter_time_A.py
- tests/t235_report_srcline.py
- tests/t236_replay_srcline.py
.dbg files are generated for binary files built with -g and -finstrument-functions
options together according to the latest changes.
It doesn't need to skip the test for case above in test cases for srcline anymore,
so it is deleted.
> test: Enable sub-case with -finstrument-functions option in srcline tests

- utils/dwarf.c
- utils/dwarf.h
Remove the common directory prefix if file name is under
the compile unit's compilation directory (DW_AT_comp_dir).
> dwarf : Remove common compile directory prefix from file name in .dbg

- libmcount/mcount.c
- tests/t246_report_srcline2.py
It generates .dbg file for every library with debug information
linked to the main executable when recording with --srcline option.
Fixed: #1138
> mcount: Generate .dbg file for library with debug section

- .travis.yml
Recently, Travis CI released support for multi-arch build. And also, it has multi-compiler support.
By this commit, travis will compile with amd64, arm64 architecture and with gcc, clang compiler. (Each arch x compilers)
Fixed: #1112 
> build: Add multi-arch and multi-compiler build test

- arch/aarch64/mcount.S
- cmds/replay.c
- libmcount/plthook.c
- tests/runtest.py
- tests/t051_return.py
- tests/t083_arg_float.py
- tests/t201_arg_dwarf1.py
- tests/t202_arg_dwarf2.py
- tests/t203_arg_dwarf3.py
- tests/t204_arg_dwarf4.py
- tests/t205_arg_auto4.py
- tests/t206_arg_enum2.py
- tests/t208_watch_cpu.py
- tests/t213_arg_symbol.py
- tests/t235_report_srcline.py
- tests/t236_replay_srcline.py
This PR fixes various test failures in i386 and aarch64.
i386 failures:
```
083 arg_float           : NG NG NG NG NG SK SK SK SK SK
116 field_none          : NG NG NG NG NG NG NG NG NG NG
185 exception2          : NG NG NG NG NG NG NG NG NG NG
186 exception3          : NG NG NG NG NG NG NG NG NG NG
201 arg_dwarf1          : NG NG NG NG NG SK SK SK SK SK
202 arg_dwarf2          : NG NG NG NG NG SK SK SK SK SK
203 arg_dwarf3          : NG NG NG NG NG SK SK SK SK SK
204 arg_dwarf4          : NG NG NG NG NG SK SK SK SK SK
205 arg_auto4           : NG NG NG NG NG SK SK SK SK SK
206 arg_enum2           : NG NG NG NG NG SK SK SK SK SK
213 arg_symbol          : NG NG NG NG NG SK SK SK SK SK
```
aarch64 failures:
```
051 return              : NZ NZ NZ NZ NZ NG NG NG NG NG
```
> tests: Fix various test failures in i386 and aarch64

- cmds/dump.c
- cmds/graph.c
- cmds/tui.c
- doc/uftrace-graph.md
- tests/t247_graph_srcline.py
- utils/graph.c
- utils/graph.h
Show source location of each function with loaded debug_info.
'-g' and '-pg' options are required when compiling an executable
to have source line information like this.
```
$ gcc -o t-abc -g -pg tests/s-abc.c
```
The '--srcline' option is required when using record command.
```
$ uftrace record --srcline t-abc
```
The '--srcline' option is also required when using graph command.
```
$ uftrace graph --srcline
========== FUNCTION CALL GRAPH ==========
8.909 us : (1) t-abc
1.260 us :  +-(1) __monstartup
:  |
0.179 us :  +-(1) __cxa_atexit
:  |
7.470 us :  +-(1) main [tests/s-abc.c:26]
5.522 us :    (1) a [tests/s-abc.c:11]
4.912 us :    (1) b [tests/s-abc.c:16]
4.176 us :    (1) c [tests/s-abc.c:21]
0.794 us :    (1) getpid
```
> graph: Show source location with --srcline option.

- Makefile
- arch/x86_64/mcount-insn.c
- cmds/recv.c
- cmds/replay.c
- cmds/report.c
- cmds/script.c
- utils/fstack.c
- utils/hashmap.c
- utils/script-python.c
The -Wdeclaration-after-statement option makes a warning when a
declaration is found after a statement in a block.  It makes easier to
identify when breaking the coding style showing the following warning.
```
warning: ISO C90 forbids mixed declarations and code
```
It makes some warnings in the existing code so this patch also fixes
those warnings together.
> build: Add -Wdeclaration-after-statement compiler flag

- cmds/tui.c
Unfortunately neovim doesn't pass this test as the name is `nvim`.
Simply add another test to check if `nvi` is the beginning of the
editor.
> [tui] Add support for +line for neovim

- arch/aarch64/mcount-dynamic.c
- libmcount/dynamic.c
- libmcount/internal.h
- utils/kernel.c
This PR applies some misc fixes as follows.
- mcount: Remove unused macro HASHMAP_INIT_VALUE
- kernel: Lower the debug level for record wrote message
- mcount: Make the return type of mcount_save_code to void
> Apply some misc fixes

- configure
This is related issue #1137 
It checks if `make` and `${CC}` and adds `Error:` prefix to indicate explicit error.
> configure: check if make and gcc exist or not and change error message format

- cmds/script.c
This patch fixes the regression for 169 script_args because of the
following commit.
d8423932 build: Add -Wdeclaration-after-statement compiler flag
It initializes 'struct script_context' without designated initialization
, but missed to zero clear the other fields, so the following test fails
as follows.
```
t169_script_args: diff result of -pg -O0
--- expect      2020-09-13 10:55:23.717086273 +0100
+++ result      2020-09-13 10:55:23.717086273 +0100
@@ -1 +1,2 @@
fopen(/dev/null)
+fclose(/dev/null)
169 script_args         : NG
```
> script: Fix script_context initialization

- check-deps/Makefile.check
It might be failed to find a correct python3 version used for scripting.
It's because python3 version is found by the python3 binary, but not by
finding python3 library actually used.
The current implementation finds python3 version as follows:
```
$ python3 -c 'import sysconfig; print(sysconfig.get_config_vars()["LDVERSION"])'
3.7m
```
However, python3-config finds different version.
This patch is to find the correct version by parsing the output of
'python3-config --libs'.
```
$ python3-config --libs | sed 's/-l\(python[0-9\.m]\+\) .*/\1/g'
python3.5m
$ python3.7-config --libs | sed 's/-l\(python[0-9\.m]\+\) .*/\1/g'
python3.7m
```
This might be a corner case fix but to support many more different
environments.
> build: Find and use a correct python3 version

- cmds/replay.c
- utils/auto-args.c
- utils/filter.h
The enum value can contain a negative value, but it's incorrectly
displayed in the current implementation.
Let's say there is a simple program as follows.
```c
$ cat enum.c
enum et {
MINUS_ONE = -1,
ZERO,
ONE,
};
void foo(enum et e) {}
int main() {
foo(MINUS_ONE);
return 0;
}
```
The tracing output with auto-args is as follows.
```
$ gcc -pg -g enum.c
$ uftrace -a a.out
[ 56519] | main() {
4.446 us [ 56519] |   foo(ONE|ZERO|MINUS_ONE+0xffffffff);
4.957 us [ 56519] | } = 0; /* main */
```
The size of enum by default is 4, but uftrace currently expects the
sizes is to be sizeof(long) so 8.
So the negative value -1 in enum type is interpreted as 8 bytes so the
it reads more bytes than stored, but it can be interpreted incorrectly.
This patch assumes the size of enum is 4 so type casted as …
> dwarf: Fix the incorrect enum display problem

- utils/dwarf.c
The following anonymous enum type makes an invalid enum spec error.
```c
$ cat 7zFile.c
typedef enum {
SZ_SEEK_SET = 0,
SZ_SEEK_CUR = 1,
SZ_SEEK_END = 2
} ESzSeek;
void File_Seek(ESzSeek origin) {}
int main() {
File_Seek(SZ_SEEK_CUR);
}
```
The uftrace output shows error messages as follows.
```
$ gcc -pg -g 7zFile.c
$ uftrace -a a.out
Usage: invalid enum spec: e:7zFile_c_2d
Usage: invalid enum spec: e:7zFile_c_2d
1.066 us [ 20007] | __monstartup();
0.431 us [ 20007] | __cxa_atexit();
[ 20007] | main() {
0.106 us [ 20007] |   File_Seek();
0.528 us [ 20007] | } = 0; /* main */
```
It's because enum type name cannot begin with a number, but the
anonymous enum type can begin with a numberic number, which is not
possible for normal enum type names, but uftrace cannot properly parse
the …
> dwarf: Fix invalid enum spec error

- arch/i386/mcount-support.c
This patch fixes the following warning when building it for i386.
```
.../arch/i386/mcount-support.c: In function ‘mcount_arch_parent_location’:
.../arch/i386/mcount-support.c:220:3: warning: ISO C90 forbids mixed
declarations and code [-Wdeclaration-after-statement]
220 |   bool found_main_ret = false;
|   ^~~~
```
> i386: Fix a warning from -Wdeclaration-after-statement

- tests/t246_report_srcline2.py
- tests/t247_graph_srcline.py
Before:
```
246 report_srcline2     : NG NG NG NG NG NG NG NG NG NG
247 graph_srcline       : NG NG NG NG NG NG NG NG NG NG
```
After:
```
246 report_srcline2     : SK SK SK SK SK SK SK SK SK SK
247 graph_srcline       : SK SK SK SK SK SK SK SK SK SK
```
> tests: Skip srcline tests when dwarf is not enabled

- check-deps/Makefile
We get the following error messages when the system doesn't have
`python3-config` installed.
```
$ ./configure
/bin/sh: 1: python3-config: not found
/bin/sh: 1: python3-config: not found
...
```
So it'd be better to hide the stderr output to `/dev/null`.
> build: Hide stderr if python3-config not found

- utils/kernel.c
The kernel tracing generates kernel-cpuXX.dat in 600 mode so it cannot
be read in other environments unlike other files that gives read
permission to other accounts.
```
$ ls -l uftrace.data/
...
-rw-r--r-- 1 root root   15910 Sep 29 09:15 info
-rw-r--r-- 1 root root 4851625 Sep 29 09:15 kallsyms
-rw------- 1 root root       0 Sep 29 09:15 kernel-cpu0.dat
-rw------- 1 root root       0 Sep 29 09:15 kernel-cpu1.dat
...
```
It makes the recorded data not portable so the other user can see the
crash as follows.
```
$ uftrace replay --no-pager
Segmentation fault (core dumped)
```
The crash backtrace is as follows.
```
$ uftrace replay --no-pager
AddressSanitizer:DEADLYSIGNAL
=================================================================
==37436==ERROR: AddressSanitizer: SEGV on unknown …
```
> kernel: Change kernel-cpuXX.dat from 600 to 644

- utils/script-python.c
This patch fixes the following heap buffer overflow.
```
$ gcc -pg -g -o t-arg tests/s-arg.c
$ uftrace record -a t-arg
$ uftrace script -S scripts/dump.py --no-pager
uftrace_begin(ctx)
record  : False
version : v0.9.4-129-g4be7 ( dwarf python luajit tui perf sched dynamic )
cmds    :
17910610.546322424  34457: [entry] __monstartup(4005b0) depth: 0
17910610.546323121  34457: [exit ] __monstartup(4005b0) depth: 0
17910610.546324914  34457: [entry] __cxa_atexit(4005d0) depth: 0
17910610.546325298  34457: [exit ] __cxa_atexit(4005d0) depth: 0
17910610.546325981  34457: [entry] main(400a6f) depth: 0
args[0] <class 'int'>: 1
args[1] <class 'int'>: 140727876517768
17910610.546326972  34457: [entry] foo(40076c) depth: 1
args[0] <class 'int'>: 3 …
```
> script: Fix a heap buffer overflow in script-python

- arch/x86_64/mcount-arch.h
- arch/x86_64/mcount-dynamic.c
- arch/x86_64/mcount-insn.c
- libmcount/dynamic.c
- libmcount/internal.h
Conditional branches and relative jumps in the prologue appears in 8% of uftrace functions. Thus there is a need to support them. 
The idea is to use a jcc8 to jump (when condition is met) to a trampoline which jumps to the target of the original instruction. The offset of the new jcc is patched later when the code is saved in the out of line buffer.
> dynamic: support relative conditional branches and relative jumps 

- cmds/dump.c
- cmds/record.c
- uftrace.h
- utils/data-file.c
- utils/filter.h
- utils/fstack.c
- utils/list.h
- utils/rbtree.c
- utils/rbtree.h
Since list.h and rbtree.h internally uses 'new' as a variable name, it
cannot be compiled by C++ compilers.
Besides those, there are more places that use C++ keywords so this
patch also renames those names as follows.
```
s/new/new_entry/g
s/old/old_entry/g
s/class/elf_class/g
s/private/info_str/g
```
> uftrace: Do not use C++ keywords as variable names

- misc/dbginfo.c
This patch fixes the following warning in i386 build.
```
/home/honggyu/uftrace/misc/dbginfo.c: In function ‘print_debug_info’:
/home/honggyu/uftrace/misc/dbginfo.c:32:23: warning: format ‘%lx’
expects argument of type ‘long unsigned int’, but argument 3 has type
‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
32 |   printf("%s [addr: %lx]\n", symname, loc->sym->addr);
|                     ~~^               ~~~~~~~~~~~~~~
|                       |                       |
|                       long unsigned int       uint64_t {aka long long unsigned int}
|                     %llx
```
> misc: Fix a warning from dbginfo in i386 build

- libmcount/mcount.c
This patch suggests to report a bug when the program gets segfault.
The output contains uftrace version info and it looks as follows.
```
$ uftrace record -l a.out
WARN: Segmentation fault: address not mapped (addr: 0x523e66c8)
WARN:  if this happens only with uftrace, please consider
-e/--estimate-return option.
WARN: Backtrace from uftrace v0.9.4-174-g0fce3 ( perf sched )
WARN: =====================================
WARN: [1] (___tls_get_addr[f7dc18d0] <= __cxa_get_globals[f7dd15eb])
WARN: [0] (__cxa_get_globals[f7dc2720] <= __cxa_throw[f7dd27d5])
Please report this bug to https://github.com/namhyung/uftrace/issues.
```
> uftrace: Suggest to report a bug when segfault happens

- Makefile
- misc/version.sh
- uftrace.c
This patch adds arch info to uftrace version string as follows.
Before:
```
uftrace v0.9.4-201-g6801 ( dwarf python luajit tui perf sched dynamic )
```
After:
```
uftrace v0.9.4-201-g6801 ( x86_64 dwarf python luajit tui perf sched dynamic )
```
It also adds a debugging output that shows version info at the
beginning of execution.
> uftrace: Add arch info to uftrace version and show it

- doc/uftrace-dump.md
- doc/uftrace-graph.md
- doc/uftrace-live.md
- doc/uftrace-replay.md
- doc/uftrace-report.md
- doc/uftrace-script.md
- doc/uftrace-tui.md
> doc: Fix grammar errors for -H option in man pages

- cmds/dump.c
- cmds/replay.c
- utils/debug.c
- utils/utils.h
This patch refactors replay print macros to normal functions and reuse
it in dump command to replace existing escape_func_name() to
print_json_escaped_char() in replay.c.
In addition, the struct type info brings another useful information so
this PR also highlights the type name in yellow color.
Fixed: #1129
> uftrace: Refactor replay print functions and reuse it in dump

- cmds/tui.c
- doc/uftrace-tui.md
- utils/field.c
- utils/field.h
Hello!
This PR supports users to customize fields for graph mode in interactive mode.
When you press f key, a menu is displayed like h key for help message.
You can see three fields, and each field has a checkbox.
If a field is checked, then the checkbox is checked with 'x'.
If you run uftrace tui by default, 'total' field is already checked.
Depending on using -f option, fields can be already checked differently.
If you press SPACE key, you can (un) check the field.
If you want to move to another field, press DOWN/UP arrow keys or j/k keys.
If you want to apply your customization, press f or ENTER key.
If you want to revoke your customization, press q key.
Fixed: #1013
Signed-off-by: Sangwon Hong <qpakzk@gmail.com>
> tui: Customize fields in graph mode interactively

- doc/ko/uftrace-report.md
- doc/uftrace-report.md
The commit 2bd1bbe (tests: Add test cases for record with -f option.) updated a wrong description for -s option in report.
Signed-off-by: Sangwon Hong <qpakzk@gmail.com>
> doc: fix a wrong description for report -s

- tests/runtest.py
Add an option to specify the compiler type so that runtest.py
can work with nor only gcc but also clang.
Signed-off-by: SeokHoon Yoon <iamyooon@gmail.com>
> test: Add -c, --compiler option for clang

- arch/aarch64/mcount-dynamic.c
Unlike x86_64, aarch64 doesn't print debug messages for patched
function so this patch adds it same as x86_64.
```
$ gcc -o t-abc tests/s-abc.c
$ uftrace record -P. --debug-domain dynamic:2 t-abc
dynamic: patch normal func: call_weak_fn (patch size: 8)
dynamic: patch normal func: a (patch size: 8)
dynamic: patch normal func: b (patch size: 8)
dynamic: patch normal func: c (patch size: 8)
dynamic: patch normal func: main (patch size: 8)
dynamic: patched all (5) functions in 't-abc'
```
> aarch64: dynamic: Add debug messages for patched function

- tests/runtest.py
- tests/s-return.c
- tests/t002_argument.py
- tests/t051_return.py
- tests/t052_nested_func.py
- tests/t136_dynamic.py
This PR fixes the following test failures when building them with clang in aarch64.
```
002 argument            : OK OK OK OK NG OK OK OK OK NG
051 return              : NG NG NG NG NG NG OK OK OK OK
052 nested_func         : BI BI BI BI BI BI BI BI BI BI
136 dynamic             : BI BI BI BI BI BI BI BI BI BI
```
It also makes the `runtest.py` show statistics summary only when more than
30 tests are executed.
> Fix tests built by clang in aarch64

- utils/symbol.c
Signed-off-by: Lei Maohui <leimaohui@cn.fujitsu.com>
> Fix error on aarch64 with binutils2.35.1 and later versions.

- utils/script-python.c
This commit removes `PyAPI_FUNC` in `utils/script-python.c`,
which causes compiler warning.
This macro is used only for python script within this file,
and doesn't affect in any way, it's ok to remove.
Fixed: #1268
> utils: Remove unnecessary python macro causing compiler warning

- misc/install-deps.sh
The current misc/install-deps.sh installs libpython2.7-dev but
libpython3-dev is better to be used so this patch changes it.
> misc: Replace libpython2.7 to libpython3 in install-deps.sh

- cmds/tui.c
- doc/ko/uftrace-tui.md
- doc/uftrace-tui.md
- utils/field.c
Hello.
Before this commit, the `tui` command provided the `-f` option only for the graph mode.
This commit allows the `tui` command to provide the `-f` option when adding the `--report` option together.
Fixed: #1278.
> tui: Enable TUI report mode to use option -f

- scripts/strings.lua
- scripts/strings.py
- tests/runtest.py
- tests/s-struct.c
- tests/t257_arg_struct_replay.py
- tests/t258_arg_struct_dump.py
- tests/t259_arg_struct_script.py
- tests/t260_arg_struct_luajit.py
- utils/script-luajit.c
- utils/script-python.c
We didn't handle struct type for scripting, so it crashes as follows.
```
$ g++ -pg -g -O2 tests/s-dwarf7.cpp
$ uftrace record -a --no-libcall a.out
$ uftrace script --no-pager -S scripts/dump.py
...
4981.341259000   4788: [entry] main(7fd7928006cd) depth: 0
WARN: invalid argument format: 10
WARN: invalid argument format: 10
4981.341264100   4788: [entry] compare_iters(7fd79280088a) depth: 1
Segmentation fault (core dumped)
```
This patch fixes this problem for both python and luajit, but print the
struct type name in string type as follows.
```
$ uftrace script -S scripts/dump.py
...
4981.341259000   4788: [entry] main(7fd7928006cd) depth: 0
4981.341264100   4788: [entry] compare_iters(7fd79280088a) depth: 1
args[0] <type 'str'>: __normal_iterator
args[1] <type 'str'>: __normal_iterator …
```
> script: Fix a crash for struct type handling in script

- arch/x86_64/mcount-event.c
- tests/t150_recv_event.py
- utils/fstack.c
Currently, uftrace gets segfault when patching SDT events into the
target binary.
```
$ gcc -pg -o t-sdt s-sdt.c
$ uftrace -E uftrace:* --match glob t-sdt
WARN: cannot open record data: /tmp/uftrace-live-CCoVbF: No data available
```
The reason of the segfault is because the access permission of the
SDT memory region becomes PROT_EXEC only without having PROT_READ.
It might be okay in some environments but some are not so this patch
explicitly adds PROT_READ along with PROT_EXEC.
Before:
```
147 event_sdt           : SG SG SG SG SG SG SG SG SG SG
150 recv_event          : NZ NZ NZ NZ NZ NZ NZ NZ NZ NZ
```
After:
```
147 event_sdt           : OK OK OK OK OK OK OK OK OK OK
150 recv_event          : OK OK OK OK OK OK OK OK OK OK
``` …
> event: Fix a crash by adding PROT_READ along with PROT_EXEC

- arch/i386/mcount-arch.h
- arch/i386/mcount-dynamic.c
- arch/x86_64/mcount-noplt.c
- libmcount/dynamic.c
This PR allows `-mfentry -mnop-mcount` compiled binary in i386 arch.
Unlike x86_64, i386 doesn't support xray nor full dynamic tracing.
```
$ gcc -pg -mfentry -mnop-mcount -m32 -o t-abc s-abc.c
$ uftrace -P. -f +addr t-abc
0.870 us [ 39676]  80483d0 | __monstartup();
0.757 us [ 39676]  80483f0 | __cxa_atexit();
[ 39676]  80485c4 | main() {
[ 39676]  8048567 |   a() {
[ 39676]  804857c |     b() {
[ 39676]  8048591 |       c() {
0.541 us [ 39676]  80483e0 |         getpid();
1.394 us [ 39676]  8048591 |       } /* c */
1.840 us [ 39676]  804857c |     } /* b */
2.157 us [ 39676]  8048567 |   } /* a */
2.629 us [ 39676]  80485c4 | } /* main */
```
Before:
```
Test case                 pg
------------------------: O0 O1 O2 O3 Os
136 dynamic             : SG SG SG SG SG
```
After:
```
Test …
```
> i386: Support -mfentry -mnop-mcount compiled binary

- tests/runtest.py
- tests/t136_dynamic.py
- tests/t147_event_sdt.py
- tests/t150_recv_event.py
- tests/t216_no_libcall_report.py
- tests/t223_dynamic_full.py
- tests/t224_dynamic_lib.py
- tests/t225_dynamic_size.py
- tests/t232_dynamic_unpatch.py
- tests/t233_dynamic_unpatch2.py
- tests/t244_report_task_field.py
- tests/t248_dynamic_dlopen.py
- utils/field.h
- utils/report.c
This PR is to fix some tests with the following commits.
- tests: Skip -finstrument-functions builds in dynamic tests
- tests: Add TestBase.check_arch_mfentry_mnop_mcount_support
- tests: Introduce TestBase.check_arch_full_dynamic_support and use it
- tests: Fix get_elf_machine for both python2 and python3
- tests: Enable SDT tests only for x86_64
- tests: Fix random failures in 216 no_libcall_report
- report: Change the order of TID and Num funcs in report --task
> Apply tests fixes in various environments

- Makefile
- libmcount/wrap.c
- libtraceevent/kbuffer-parse.c
This commit adds undefined flag in ASAN build.
This is to catch not only memory errors and leaks
but also undefined behaviors.
> build: Add undefined flag in ASAN=1 build

- utils/dwarf.c
This patch fixes the following runtime errors generated by ubsan,
UndefinedBehaviorSanitizer.
```
$ make SAN=all install
$ gcc -pg tests/s-exp-float.c
$ uftrace -F main -D 1 a.out
/home/honggyu/uftrace/utils/dwarf.c:2185:18: runtime error: member access within null pointer of type 'struct uftrace_module'
/home/honggyu/uftrace/utils/dwarf.c:2186:22: runtime error: member access within null pointer of type 'struct uftrace_module'
0.721 us [ 41456] | main();
```
Fixed: #1300
> utils: Fix runtime errors caught by ubsan

- Makefile
- check-deps/Makefile
- check-deps/Makefile.check
- check-deps/__have_libunwind.c
- configure
- utils/utils.c
The current stacktrace in release mode uses backtrace() in execinfo.h,
but it can't show static function names and it doesn't work reliable in
libmcount*.so libraries during record time.
Moreover, execinfo.h is not well supported in some environments such as
alpine Linux.
So we better use only libunwind when it's available. If not, we just do
not print anything in stacktrace().
This PR also contains build check routine for libunwind as follows.
```
$ ./configure
...         prefix: /usr/local
...
...      libunwind: [ on  ] - libunwind support
```
Fixed: #1298
> utils: Use only libunwind without using execinfo

- utils/debug.c
'sc' means start character and is set to TERM_COLOR_NORMAL initially,
but it has to be set to TERM_COLOR_RESET when color mode is on.
This patch fixes missing reset 'ec' in print_diff_percent and
print_diff_count.
> debug: Fix to properly set end character to TERM_COLOR_RESET

- cmds/info.c
- tests/t261_info_note.py
This patch introduces note.txt under the uftrace record directory.  This
simply checks whether the record directory has note.txt file and prints
the contents if exists.  Otherwise, it doesn't print anything as before.
It'd be useful if we can add extra information for the given record
data.
```
$ uftrace record t-hello note.txt
$ cat > uftrace.data/note.txt
You can leave a note for the recorded data.
$ uftrace info
...
...
You can leave a note for the recorded data.
```
> info: Introduce uftrace.data/note.txt for extra note

- libtraceevent/event-parse.c
- utils/debug.c
- utils/utils.c
- utils/utils.h
This commit change `strerror_r` into wrapper function called
`uftrace_strerror`, because return value of the function can be
either string, or int depending on the system.
Fixed: #1303
> utils: Change strerror_r into wrapper function

- README.md
- doc/ko/README.md
This commit changes the link of ci logo because
building on travis-ci.org is currently not supported.
> doc: Change ci logo link from travis-ci.org to travis-ci.com

- cmds/graph.c
- cmds/replay.c
- cmds/report.c
- doc/uftrace-graph.md
- doc/uftrace-replay.md
- doc/uftrace-report.md
- uftrace.c
- uftrace.h
- utils/debug.c
- utils/utils.h
This patch adds --format=html option to print the output in html format
that can be opened in a web browser.  The html page output looks exactly
same as the output in console.
This mode can be used in replay, report, graph commands.
Closes: #1308
> uftrace: Introduce --format=html option to print html output

- cmds/replay.c
We don't have to make the replay output unnecessarily complicated so
this patch removes the terminal output bold for parenthesis and comma.
> replay: Do not make bold for parenthesis and comma

- cmds/replay.c
gcc puts "<lambda" to annoymous lambda but it'd be better to ignore
to make it same as clang.
It would make less troublesome in format html output.
> replay: Do not print "<lambda" as struct type name

- cmds/live.c
- cmds/record.c
Just a suggestion to fix those messages, I saw them during autotest run because of some error in starting the autotest.
The commits from Paul were here in error, removed, only the single remaining commit is what I wanted to send.
> Fix spelling of errors on missung libmcount.so

- doc/uftrace-live.md
- doc/uftrace-record.md
This commit fixes grammatical error in
uftrace-live.md and uftrace-record.md,
from 'will not shown' to 'will not be shown'.
Fixed: #1322
> doc: Fix grammatical error in doc

- utils/dwarf.c
- utils/extern.c
- utils/symbol.c
When 'make test' is executed, the following warning messages are displayed:
/home/ubuntu/uftrace/utils/dwarf.c: In function ‘func_dwarf_same_file_name1’:
/home/ubuntu/uftrace/utils/dwarf.c:2461:2: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
system("rm -f name*.dbg");
^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/uftrace/utils/dwarf.c:2497:2: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
system("rm -f name*.dbg");
^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/uftrace/utils/dwarf.c: In function ‘func_dwarf_same_file_name2’:
/home/ubuntu/uftrace/utils/dwarf.c:2509:2: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
system("rm -f …
> test: solve warning messages

- check-deps/Makefile
- check-deps/Makefile.check
In a cross-compilation scenario, it might not have python executable.
Even if it exists, the compiler options are for the host environment.
Not for the build target environment.
Using pkg-config to get compiler options of libpython3 fixes
libpython in the cross-compilation scenario.
Signed-off-by: Kun-Chuan Hsieh <jetswayss@gmail.com>
> build: Use pkg-config to get compiler options of libpython3

- tests/t228_read_pmu_cycle3.py
Some gcc generates totally incorrect binary for s-thread-name.c when
optimized and it makes 228_read_pmu_cycle3 test fails as follows.
```
228 read_pmu_cycle3     : OK OK NG NG NG OK NG OK OK OK
```
We can just avoid this failure by changing the target program to
s-fork.c instead.
```
228 read_pmu_cycle3     : OK OK OK OK OK OK OK OK OK OK
```
Link: https://github.com/namhyung/uftrace/pull/1288#discussion_r680653086
> tests: Fix 228_read_pmu_cycle3 test

- misc/install-deps.sh
python3-config can be installed by python3-dev, which depends on
libpython3-dev.
We no longer require to use python3-config but it'd be better to install
python3-dev instead of libpython3-dev.
> misc: Install python3-dev instead of libpython3-dev

- scripts/report-libcall.py
Parenthesis for argument in lambda causes syntax error in python3 like below.
It's because ability to unpack tuple parameters was removed in python 3.
```
ubuntu@ubuntu:~/minchul/uftrace/scripts$ python2 report-libcall.py
ubuntu@ubuntu:~/minchul/uftrace/scripts$ python3 report-libcall.py
File "report-libcall.py", line 26
sorted_dict = sorted(libcall_map.iteritems(), key=lambda (k, v): (v, k), reverse=True)
^
SyntaxError: invalid syntax
```
So this commit removed parenthesis for python3 compatibility.
reference: https://www.python.org/dev/peps/pep-3113/
> scripts: Make lambda expression compatible for python3

- cmds/report.c
- cmds/tui.c
- doc/ko/uftrace-tui.md
- doc/uftrace-tui.md
- utils/report.c
- utils/report.h
The `tui` command couldn't use -s/--sort option with --report option.
This commit allows the command to use -s/--sort option when you use it with --report option.
Fixed: #1359.
> tui: Use -s option with --report option in TUI

- cmds/replay.c
It used to show module name of schedule events as [unknown], but this
patch marks it as [event] as follows.
```
$ uftrace --no-libcall -f +module t-fork
[ 55417]           t-fork | main() {
[ 55417]                  |   /* linux:sched-out */
[ 55432]           t-fork | a() {
[ 55432]           t-fork |   b() {
5.724 us [ 55432]           t-fork |     c();
7.106 us [ 55432]           t-fork |   } /* b */
7.724 us [ 55432]           t-fork | } /* a */
7.724 us [ 55432]           t-fork | } /* main */
1.246 ms [ 55417]          [event] |   /* linux:sched-in */
[ 55417]           t-fork |   a() {
[ 55417]           t-fork |     b() {
1.213 us [ 55417]           t-fork |       c();
2.588 us [ 55417]           t-fork |     } /* b */
3.448 us [ 55417]           t-fork |   } /* a */
1.677 ms [ …
```
> replay: Set module name as [event] for sched events

- arch/aarch64/fentry.S
- arch/aarch64/mcount-dynamic.c
- arch/i386/mcount-dynamic.c
- arch/x86_64/mcount-dynamic.c
- doc/uftrace-live.md
- doc/uftrace-record.md
- libmcount/dynamic.c
- libmcount/dynamic.h
- tests/s-patchable-abc.c
- tests/t263_patchable_dynamic.py
- tests/t264_patchable_dynamic2.py
- tests/t265_patchable_dynamic3.py
- tests/t266_patchable_dynamic4.py
- tests/t267_patchable_dynamic5.py
Recnet gcc and clang provides a way to have NOP sleds at the beginning
of functions with new option '-fpatchable-function-entry=N[,M]'.
The explanation in gcc[1] is as follows.
```
-fpatchable-function-entry=N[,M]
Generate N NOPs right at the beginning of each function, with the
function entry point before the Mth NOP. If M is omitted, it
defaults to 0 so the function entry points to the address just at
the first NOP. The NOP instructions reserve extra space which can be
used to patch in any desired instrumentation at run time, provided
that the code segment is writable. The amount of space is
controllable indirectly via the number of NOPs; the NOP instruction
used corresponds to the instruction emitted by the internal GCC
back-end interface gen_nop. This behavior is target-specific and …
```
> dynamic: Support -fpatchable-function-entry=N tracing

- tests/s-libfoo.cpp
Since -Os optimizes for size, the code size of 'foo()' becomes too small
as follows.
```
00000000000005f5 <foo>:
5f5:   e9 26 ff ff ff          jmpq   520 <AAA::bar(int)@plt>
00000000000005fa <AAA::bar(int)>:
5fa:   48 8b 05 ef 09 20 00    mov    0x2009ef(%rip),%rax        # 200ff0 <_DYNAMIC+0x198>
601:   89 38                   mov    %edi,(%rax)
603:   c3                      retq
```
In this case, the call instruction is overwritten at the entry of 'foo',
but the return address for the entry of foo misinterpreted as the
address 0x5fa, which is the address of 'AAA::bar(int)>' so uftrace gets
confused about the function name and it fails as follows.
```diff
t248_dynamic_dlopen: diff result of -pg -Os
--- expect      2021-11-04 23:01:43.803874511 +0000
+++ result      2021-11-04 …
```
> tests: Fix a failure of 248 dynamic_dlopen with -Os

- arch/aarch64/mcount-dynamic.c
- arch/i386/mcount-dynamic.c
- arch/x86_64/mcount-dynamic.c
uftrace has to skip the function target if the function size is same as
min_size given.  This is needed in the following case.
```
00000000000005f5 <foo>:
5f5:   e9 26 ff ff ff          jmpq   520 <AAA::bar(int)@plt>
00000000000005fa <AAA::bar(int)>:
5fa:   48 8b 05 ef 09 20 00    mov    0x2009ef(%rip),%rax        # 200ff0 <_DYNAMIC+0x198>
601:   89 38                   mov    %edi,(%rax)
603:   c3                      retq
```
In this case, the call instruction is overwritten at the entry of 'foo',
but the return address for the entry of foo is misinterpreted as the
address 0x5fa, which is the address of 'AAA::bar(int)>' so uftrace gets
confused about the function name and it fails as follows.
We should avoid patching when symbol size is less than or equal to
min_size.
Signed-off-by: …
> dynamic: Set dynamic min_size as patched code size + 1

- libmcount/dynamic.c
If there is a simple example as follows.
```cpp
$ cat shared_ptr.cc
#include <memory>
int main()
{
std::shared_ptr<int> p(new int);
}
```
We can compile it with -pg and -fpatchable-function-entry=5 as follows.
```
$ g++ -pg -o shared_ptr.pg shared_ptr.cc
$ g++ -fpatchable-function-entry=5 -o shared_ptr.fpatchable shared_ptr.cc
```
Tracing result of shared_ptr.fpatchable shows much less functions than
shared_ptr.pg example.
```
$ uftrace --no-libcall shared_ptr.pg | wc -l
39
$ uftrace -P. --no-libcall shared_ptr.fpatchable | wc -l
11
```
It's because many functions are shown as weak symbols.
```
$ nm -C shared_ptr.fpatchable | grep "std::shared"
0000000000400b0e W std::shared_ptr<int>::shared_ptr<int, void>(int*)
0000000000400b0e W std::shared_ptr<int>::shared_ptr<int, void>(int*) …
```
> dynamic: Do not skip weak symbol functions for dynamic tracing

- arch/arm/mcount-support.c
uClibc-ng `<elf.h>` doesn't define `EF_ARM_VFP_FLOAT`, so let's define it.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
[Retrieved from: https://git.buildroot.net/buildroot/tree/package/uftrace/0002-arch-arm-mcount-support.c-define-EF_ARM_VFP_FLOAT-wh.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> arch/arm/mcount-support.c: define EF_ARM_VFP_FLOAT when not available

- cmds/replay.c
- tests/t236_replay_srcline.py
At the request and guidance of @honggyukim, I removed nonvital source line information when returning functions for readability and simplicity.
```
Before:
$ uftrace replay --srcline t-abc
0.895 us [ 13079] | __monstartup();
0.295 us [ 13079] | __cxa_atexit();
[ 13079] | main() { /* tests/s-abc.c:26 */
[ 13079] |   a() { /* tests/s-abc.c:11 */
[ 13079] |     b() { /* tests/s-abc.c:16 */
[ 13079] |       c() { /* tests/s-abc.c:21 */
1.132 us [ 13079] |         getpid();
2.930 us [ 13079] |       } /* c at tests/s-abc.c:21 */
3.563 us [ 13079] |     } /* b at tests/s-abc.c:16 */
4.028 us [ 13079] |   } /* a at tests/s-abc.c:11 */
4.529 us [ 13079] | } /* main at tests/s-abc.c:26 */
After:
$ uftrace replay --srcline t-abc
0.895 us [ 13079] | __monstartup();
0.295 us [ 13079] | …
```
> replay: Remove source location information when returning a function

- doc/uftrace-report.md
- utils/field.c
Add "all" field to show all available fields.
It is applied to report, report --diff and report --task.
These are usage examples:
```
$ uftrace report -f all
Total time   Total avg   Total min   Total max   Self time    Self avg    Self min    Self max       Calls  Function
==========  ==========  ==========  ==========  ==========  ==========  ==========  ==========  ==========  ====================
15.780 ms    1.753 ms   13.963 us   14.625 ms   15.780 ms    1.753 ms   13.963 us   14.625 ms           9  linux:schedule
14.669 ms   14.669 ms   14.669 ms   14.669 ms   44.337 us   44.337 us   44.337 us   44.337 us           1  wait3
1.744 ms    1.744 ms    1.744 ms    1.744 ms   22.354 us   22.354 us   22.354 us   22.354 us           1  main
```
```
$ uftrace report --diff uftrace.data.old …
```
> report: Add "all" field for -f option

- cmds/recv.c
According to coverity report, we should check return value of setsockopt,
because this can be either 0 ro -1.
So This commit adds checking procedure for setsockopt.
> recv: Check return value of setsockopt

- tests/runtest.py
The following patch trimed the trailing whitespace in the expected test
strings.
b93c4152 uftrace: Introduce pre-commit and apply the changes
However, uftrace sometimes produces output with trailing whitespace so
some tests especially in graph command were failed due to this change.
```
181 graph_full          : NG NG NG NG NG NG NG NG NG NG
187 graph_field         : NG NG NG NG NG NG NG NG NG NG
188 graph_field_none    : NG NG NG NG NG NG NG NG NG NG
218 no_libcall_graph    : NG NG NG NG NG NG NG NG NG NG
```
This patch applies trailing whitespace strip for both expected and test
result strings for correct comparison.
> tests: Fix test regression due to trailing whitespace

- README.md
- doc/ko/README.md
- uftrace.c
Currently, when uftrace is used solely,
there are no explanations for COMMANDS like below:
```
COMMAND: record|replay|live|report|graph|info|dump|recv|script|tui
```
But I think it's better to put explanation for each commands like perf, git, etc
for users who don't know uftrace well.
```
ubuntu@ubuntu:~$ perf
usage: perf [--version] [--help] [OPTIONS] COMMAND [ARGS]
The most commonly used perf commands are:
annotate        Read perf.data (created by perf record) and display annotated code
archive         Create archive with object files with build-ids found in perf.data file
bench           General framework for benchmark suites
buildid-cache   Manage build-id cache.
buildid-list    List the buildids in a perf.data file
...
```
So this commit adds better explanation for commands when …
> uftrace: Better default message for uftrace

- arch/aarch64/mcount-arch.h
- arch/arm/mcount-arch.h
- arch/i386/mcount-arch.h
- arch/x86_64/mcount-arch.h
- utils/dwarf.c
Let's say there is a simple program 'shared_ptr.cc' as follows.
```cpp
$ cat shared_ptr.cc
#include <memory>
int main()
{
std::shared_ptr<int> p(new int);
}
```
If we compile this program with -fpatchable-function-entry, uftrace
record with arguments gets failed as follows.
```
$ g++ -fpatchable-function-entry=5 -g -o shared_ptr.fpatchable shared_ptr.cc
$ uftrace --no-libcall -a -P. shared_ptr.fpatchable
fstack: /home/honggyu/work/uftrace/utils/fstack.c:1595:read_task_ustack
ERROR: record missing argument info for std::shared_ptr::shared_ptr
```
This problem happens because dwarf_getsrc_die returns NULL with the
start address of functions and it's assigned to Dwarf_Line *line.
```
line = dwarf_getsrc_die(&cudie, dwarf_addr);
```
-fpatchable-function-entry=5 adds 5 NOP instructions at the …
> dwarf: Fix args reading error in -fpatchable-function-entry binaries

- cmds/dump.c
- cmds/replay.c
- cmds/script.c
- doc/uftrace-dump.md
- doc/uftrace-live.md
- doc/uftrace-replay.md
- doc/uftrace-script.md
- tests/t269_arg_no_args_replay.py
- tests/t270_arg_no_args_dump.py
- uftrace.c
- uftrace.h
It needs to provide a way to hide args/retval to reduce the amount of
dump output.  It has to be implemented for replay command later on.
> uftrace: Add --no-args option to hide args/retval

- utils/data-file.c
utils: fix undefined behavior.
In your code you don't initialize evt_id, provider and event, don't check the result of running sscanf.
therefore, in the event of an incorrect call to sscanf, function read_events_file may fill in the data with random data.
Signed-off-by: ihsinme <ihsinme@gmail.com>
> fix undefined behavior.

- tests/runtest.py
Currently, stderr of target test programs are swallowd by runtest.py,
but it'd be much better if it can be printed in verbose mode test.
Before:
```
$ ./runtest.py -vdi -O0 251
Start 1 tests with 1 worker
Test case                 fi
------------------------: O0
...
251 exception4          : SG
```
After:
```
$ ./runtest.py -vi -O0 251
Start 1 tests with 1 worker
Test case                 fi
------------------------: O0
...
terminate called after throwing an instance of 'std::runtime_error'
what():  XXX error
WARN: process crashed by signal 6: Aborted (si_code: 0)
WARN:  if this happens only with uftrace, please consider -e/--estimate-return option.
WARN: Backtrace from uftrace v0.11-58-g376d ( aarch64 dwarf python luajit tui perf sched dynamic )
WARN: …
```
> tests: Show stderr message in verbose mode test

- scripts/dump.lua
- scripts/dump.py
This PR adds uftrace_event handling in dump.py and dump.lua as follows.
$ gcc -pg -o t-sleep tests/s-sleep.c
$ uftrace record --no-libcall t-sleep
$ uftrace script -S scripts/dump.py
uftrace_begin(ctx)
record  : False
version : v0.11-63-g6eba47 ( x86_64 dwarf python luajit tui perf sched dynamic )
cmds    :
9826991.615165883  17706: [entry] main(400850) depth: 0
9826991.615166494  17706: [entry] foo(40082a) depth: 1
9826991.615166805  17706: [entry] mem_alloc(4007db) depth: 2
9826991.615167952  17706: [exit ] mem_alloc(4007db) depth: 2
9826991.615169119  17706: [entry] bar(400810) depth: 2
9826991.615185663  17706: [event] linux:sched-out(30d42)
9826991.617290083  17706: [event] linux:sched-in(30d41)
9826991.617296237  17706: [exit ] bar(400810) depth: 2
9826991.617298178  17706: [entry] …
> scripts: Add uftrace_event handling in dump.{py,lua} and fix dump.lua

- libmcount/wrap.c
- misc/version.sh
- utils/kernel.c
as found by the debian automated-checking tool Lintian. None of these
matter particularly, but it's a patch we apply to the Debian packaging,
so I'll pass it along.
Signed-off-by: paul cannon <pik@debian.org>
> uftrace: correct minor spelling errors

- cmds/record.c
- libmcount/internal.h
- libmcount/mcount.c
- uftrace.c
- utils/perf.c
- utils/utils.c
- utils/utils.h
The --clock option currently doesn't change the clock id of perf events
and this makes the replay output incorrect when clock id is changed.
This patch applies clock id change to perf event as well and moves
clock_source from libmcount/mcount.c to utils/utils.c.
> clock: Fix clock_source setup logic to handle perf events

- utils/symbol.c
We also need to check if m->build_id[0] is not NULL just like we did for
build_id[0].
When m->build_id[0] is empty, it fails loading symbol files.
> symbol: Fix incorrect symbol file loading

- arch/arm/mcount.S
- arch/arm/plthook.S
This patch, supplied by Nobuhiro Iwamatsu <iwamatsu@debian.org>, allows
the uftrace deb to build cleanly on the "armhf" arch (that's the Debian
name for arm-linux-gnueabihf).
The errors as encountered by the build daemon can be seen in the log at:
https://buildd.debian.org/status/fetch.php?pkg=uftrace&arch=armhf&ver=0.11-3&stamp=1647358997&raw=0
Here is a snippet of that output:
gcc -D_GNU_SOURCE -ffile-prefix-map=/<<PKGBUILDDIR>>=. -Wdate-time
-D_FORTIFY_SOURCE=2 -iquote /<<PKGBUILDDIR>> -iquote /<<PKGBUILDDIR>> \
-iquote /<<PKGBUILDDIR>>/arch/arm -Wdeclaration-after-statement -W
-Wall -Wno-unused-parameter -Wno-missing-field-initializers -O2 -g \
-DDEBUG_MODE=0 -DHAVE_CXA_DEMANGLE -DHAVE_LIBPYTHON3 \
-I/usr/include/python3.9  -DLIBPYTHON_VERSION=3.9 -DHAVE_PERF_CLOCKID \ …
> arch/arm: fix build (under some circumstances)

- tests/t248_dynamic_dlopen.py
The test 248 dynamic_dlopen fails since the following patch.
0096b3f3 dynamic: Do not skip weak symbol functions for dynamic tracing
It's because AAA:bar() is a weak symbol so it wasn't shown before, but
this patch makes it appear.
```
$ nm -C libfoo.so
...
0000000000000659 W AAA::bar(int)
```
This patch fixes the test by adding AAA:bar() in the expected test
result.
> tests: Fix a regression in 248 dynamic_dlopen

- check-deps/Makefile
If uftrace directory is under overlay file system, -executable option in
find doesn't work as expected and it gives the entire files.  It makes
'make check-clean' remove all the files under check-deps.
This patch replaces -executable to -perm -u=x,g=x,o=x to avoid such
problem in check-deps/Makefile.
> build: Replace -executable to -perm -u=x,g=x,o=x

- doc/uftrace.html
We now have dynamic tracing for patchable function entry for both with a
compiler option and an attribute.
This usage is much better than the previous other dynamic tracing
options so it'd be better to replace old dynamic tracing ways to using
-fpatchable-function-entry=N and patchable_function_entry attribute in
the tutorial slide.
> slide: Update dynamic tracing section

- uftrace.c
This PR fixes memory leak in t252, which happens
when parse_option is called.
Before:
```
$ ./runtest.py -vdp -O0 252
...
SUMMARY: AddressSanitizer: 2 byte(s) leaked in 1 allocation(s).
t252_filter_H: -pg -O0 returns 1
252 filter_H            : NZ
```
After:
```
$ ./runtest.py -vdp -O0 252
...
252 filter_H            : OK
```
Fixed: #1429
> uftrace: Fix memory leak in parse_option

- utils/data-file.c
- utils/event.c
- utils/event.h
This PR fixes memory leaks when handling events.txt read.
```
$ make ASAN=1
$ cd tests
```
Before:
```
$ ./runtest.py -vdp -O0 147
...
SUMMARY: AddressSanitizer: 54 byte(s) leaked in 3 allocation(s).
t147_event_sdt: -pg -O0 returns 1
147 event_sdt           : NZ
```
After:
```
$ ./runtest.py -vdp -O0 147
...
147 event_sdt           : OK
```
Fixed: #1427
> event: Fix memory leaks by adding finish_events_file()

- arch/arm/mcount-arch.h
- arch/arm/mcount-support.c
- arch/i386/mcount-arch.h
- arch/i386/mcount-support.c
This patch is to fix missing renaming in arm and i386.
The original renaming change was introduced in the following commit.
1b16f4ed uftrace: Rename 'symtabs' to 'uftrace_sym_info'
> arch: Fix missing renaming in arm and i386

- tests/runtest.py
- tests/t269_arg_no_args_replay.py
- tests/t270_arg_no_args_dump.py
This PR includes the following changes.
- afe48159 tests: Fix possibly incorrect libmcount.so loading
- 57b6b34e tests: Add -m32 option when the architecture is i386
- 31047961 tests: Add class Elf and move related code inside of runtest.py
> A few fixes and enhancement for i386 testing

- utils/session.c
I found some typos in comments and corrected them.
> session: correct the function name in the comment

- misc/install-deps.sh
Although many linux distributions use /etc/os-release,
there are some systems that does not use that for OS identification.
(especially for some traditional non-systemd linux distros or macOS)
When these kinds on distros run /misc/install-deps.sh,
message is printed like below:
```
$ sudo ./install-deps.sh
grep: /etc/os-release: No such file or directory
"" is not supported distro, so please install packages manually.
```
So this commit adds an exception for those does not use
/etc/os-release.
> misc: Add an exception for distros that doesn't use /etc/os-release

- utils/argspec.h
argspec.h lacks stdbool.h, and this causes compilation error
when argspec.h is compiled(as a standalone).
Although argspec.h doesn't usually compiled as a standalone,
this can cause potential error when other file(s) include
only argspec.h and nothing else.
Fixed: #1449
> utils: Add missing header in argspec.h

- cmds/tui.c
In terms of macros, clang-format sometimes applies incorrect formatting
and it made tui report field incorrectly modified so let's fix them.
> tui: Fix incorrect clang-format conversion in report

- uftrace.c
After used the exename of opts stucture, it should be freed.
But there is missing a free function after used it,
so a free function is added.
Fixed: #1428
> uftrace: fix a memory leak in a exename of a opts struct

- utils/report.c
Remove redundant `#include` in utils/report.c
There were a few other files with duplicated `#include` but I thought those should be kept. I'll list them below just for the record.
utils/kernel.c
- <sys/stat.h> L15, L1832
> The first is always included while the second is used for unit testing. Since the use case is different, being explicit seems better.
cmds/tui.c
- "uftrace.h" L14, L3033
- "utils/utils.h" L16, L3034
> The directives are specified once for `ifdef HAVE_LIBNCURSES` and once for `else`. Having dependencies contained for each condition would be better for future development in case the conditions become more complex.
misc/prototypes.h
- <sys/stat.h> L188, L496
> constant / function declarations are grouped by category, so keeping the directive serves as documentation for …
> trivial: Remove duplicated #include directive

- .gitignore
Ignore vscode config directory (.vscode), compilation db
(compile_commands.json) and clangd config/index (.clangd/ and
.cache).
Signed-off-by: Seonghyun Park <shp4rk@gmail.com>
> misc: Ignore vscode/clangd files

- uftrace.c
This reverts commit e0f2fe1a9ed2a606f8039a6be28939289123083c.
The above patch freed opts->exename but it mostly wasn't malloced memory
so it shows the following error when recording.
```
$ uftrace record a.out
free(): invalid pointer
Aborted
```
The following asan message shows the problem.
```
$ uftrace record a.out
=================================================================
==37601==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x7ffd1f2c18e6 in thread T0
#0 0x7f117be958af in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10b8af)
#1 0x40fc41 in free_opts /home/honggyu/work/uftrace/uftrace.c:1222
#2 0x4121ae in main /home/honggyu/work/uftrace/uftrace.c:1462
#3 0x7f1179edb0b2 in __libc_start_main …
```
> Revert "uftrace: fix a memory leak in a exename of a opts struct"

- libmcount/dynamic.h
After sorting the includes using .clang-format like below,
```
diff --git a/.clang-format b/.clang-format
index fb412706..2b293a1d 12234
--- a/.clang-format
+++ b/.clang-format
@@ -125,7 +125,7 @@ PenaltyReturnTypeOnItsOwnLine: 60
PointerAlignment: Right
ReflowComments: false
-SortIncludes: false
+SortIncludes: true
SortUsingDeclarations: false
SpaceAfterCStyleCast: false
SpaceAfterTemplateKeyword: true
```
this error comes out during make.
```
minchul@minchul:~/workspace/uftrace$ make
GEN      version.h
CC       uftrace.o
CC       cmds/dump.o
CC       cmds/graph.o
CC       cmds/info.o
CC       cmds/live.o
...
LINK     uftrace
CC FPIC  libmcount/dynamic.op
In file included from /home/minchul/workspace/uftrace/libmcount/dynamic.c:24: …
```
> libmcount: Include capstone header in dynamic.h

- tests/runtest.py
If failed-tests.txt already exists,
rename failed-tests.txt to failed-tests.txt.old
and create failed-tests.txt.
Fixed: https://github.com/namhyung/uftrace/issues/1466
Signed-off-by: Seonghee Jin <seonghee@tsnlab.com>
> trivial: Rename failed-tests.txt to failed-tests.txt.old

- CONTRIBUTING.md
pre-commit is installed via pip[1].
If this CONTRIBUTING.md doesn't guide how to install the package,
future contributors cannot know how to download and run the command below.
$ pre-commit install
So this commit adds pre-commit package installation command in
CONTRIBUTING.md
[1] https://pre-commit.com/#installation
> doc: Add pre-commit installation command in CONTRIBUTING.md

- utils/data-file.c
This commit fixes some warning messages
when the uftrace is built with unittests.
> utils: Fix warnings in data-file.c 

- libmcount/wrap.c
In some cases, mtdp can be null but it is dereferenced without checking
in pr_dbg statements.
The segfault is found when recording chrome during calling backtrace().
This patch is to fix the problem.
> libmcount: Fix a nullptr deference in mtdp with pr_dbg

- doc/ko/uftrace-script.md
There is a new script API `uftrace_event`, but it hasn't been updated
in Korean man page.  This patch is to update the Korean documentation.
Fixed: #1491
Signed-off-by: Euiseo Park <kpk0616@naver.com>
> doc/ko: Update korean document for script command

- cmds/dump.c
This patch enhances the output of --graphviz, especially the previous
attribute setup produces low quality image and this patch fixes it.
Before:
```
digraph "/data_sdb/honggyu/work/uftrace/git/uftrace/master/t-abc" {
splines=ortho;
concentrate=true;
node [shape="rect",fontsize="7",style="filled"];
edge [fontsize="7"];
"__monstartup" [xlabel = "Calls : 1"]
"__cxa_atexit" [xlabel = "Calls : 1"]
"main" [xlabel = "Calls : 1"]
"main" -> "a" [xlabel = "Calls : 1"]
"a" -> "b" [xlabel = "Calls : 1"]
"b" -> "c" [xlabel = "Calls : 1"]
"c" -> "getpid" [xlabel = "Calls : 1"]
}
```
After:
```
digraph "t-abc" {
"__monstartup" [xlabel = "1"]
"__cxa_atexit" [xlabel = "1"]
"main" [xlabel = "1"]
"main" -> "a" [xlabel = "1"]
"a" -> "b" [xlabel = "1"]
"b" -> "c" [xlabel = "1"]
"c" -> "getpid" [xlabel = "1"] …
```
> dump: Fix low quality resolution image in --graphviz output

- utils/dwarf.c
rb_entry's first argument 'rb_next(&save_entry->node)' is used as the pointer to the member in container_of.
If it is NULL, it does arithmetic on the null pointer in container_of's code below.
(type *)((char *)__mptr - offsetof(type, member));
In this part, offsetof(struct debug_entry, node) is 0. So it outputs the error as "applying zero offset to null pointer"
This change is to add null checking to fix it.
Fixed: #1441
Signed-off-by: Jia Ha <wendyisdream1004@gmail.com>
> tests : Fix applying zero offset to null pointer in unittest 16, 17

- INSTALL.md
- configure
On building uftrace from the scratch, `./configure` shows dependent
library install status. `misc/install-deps.sh` will automatically
install those libraries with each distribution's package manager.
But, current `misc/install-deps.sh` doesn't install libunwind.
This is especially optional package for debugging. (though other
packages are also optional packages.) Some users may want to build
uftrace with full feature support. So add `--full` option to install
all libraries which checked by `./configure`.
Additionally, add usage message to show about `--full` options.
Also, change description about `libunwind`. It supports backtracing
information, which is optional for debugging.
Reported-by: Lee Dong Wook <sh95119@gmail.com>
Signed-off-by: JaeSang Yoo <jsyoo5b@gmail.com>
> misc: update description about libunwind support

- Makefile
- libmcount/misc.c
- utils/kernel.c
- utils/tracefs.c
- utils/tracefs.h
Currently, uftrace interacts with kernel tracing system through
a fixed TRACING_DIR; /sys/kernel/debug/tracing, therefore fails
to trace kernel when a tracefs is mounted at a different location.
This commit introduces runtime detection tracefs or debugfs from
/proc/self/mountinfo (which is newer than /proc</self>/mounts).
Fixes #797 
Signed-off-by: Seonghyun Park <shp4rk@gmail.com>
> utils: detect tracefs or debugfs at runtime

- utils/argspec.c
This patch is to fix the following error in unittest.
```
$ make ASAN=1 unittest
$ ./tests/unittest -v argspec_parse_struct
SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x1245a1)
==55110==ABORTING
[001] argspec_parse_struct          : FAIL
```
It's because pr_dbg requires to read a string with %s, but we didn't
provide an argument.
> unittest: Fix a asan crash in argspec_parse_struct

- .codespell_ignore
- .pre-commit-config.yaml
- INSTALL.md
- arch/aarch64/mcount-dynamic.c
- arch/i386/mcount-dynamic.c
- arch/x86_64/dynamic.S
- arch/x86_64/mcount-dynamic.c
- arch/x86_64/mcount-insn.c
- arch/x86_64/mcount.S
- check-deps/Makefile
- check-deps/Makefile.check
- cmds/replay.c
- gdb/uftrace/utils.py
- misc/install-deps.sh
- tests/arch/arm/a.c
- tests/s-thread-exec.c
- tests/s-thread-name.c
- utils/auto-args.c
- utils/demangle.c
- utils/dwarf.c
- utils/fstack.c
- utils/graph.c
- utils/perf.c
- utils/regs.c
- utils/session.c
- utils/symbol.h
- utils/utils.c
codespell is a useful tool to detect typos so this patch adds it as a
pre-commit hook by default.
This codespell pre-commit hook found many typos and this patch also
fixes those typos.
```
$ pre-commit run -a
...
codespell................................................................Failed
- hook id: codespell
- exit code: 65
tests/s-thread-name.c:44: thid ==> this
...
gdb/uftrace/utils.py:73: expresssion ==> expression
gdb/uftrace/utils.py:75: expresssion ==> expression
utils/symbol.h:123: maping ==> mapping
check-deps/Makefile.check:19: verison ==> version
utils/session.c:342: librarry ==> library
utils/session.c:415: resouces ==> resources
utils/session.c:469: sesssion ==> session
utils/dwarf.c:285: executble ==> executable
utils/fstack.c:686: funciton ==> function …
```
> pre-commit: Add codespell hook in pre-commit and fix typos

- misc/version.sh
Closes #1464 
Show python3 and python2.7 version,
when user command 'uftrace --version'.
Signed-off-by: JeongWan Gho <rhwjddhks@gmail.com>
> misc: Make 'uftrace --version' show python version info

- cmds/dump.c
If there are many cores in the system, most of the cpus stays empty when
recording perf and kernel data.
If the files are empty, do not print "reading {perf,kernel}-cpuXX.dat"
messages in uftrace dump output.
> dump: Do not print perf-cpuXX and kernel-cpuXX if empty

- tests/runtest.py
Since the number of workers is bounded to the number of testcases, the
decision to use pool has to be delayed after the bound check.
Before:
$ ./runtest.py 001
Start 1 tests with 1 worker
001 basic               : OK OK OK OK OK OK OK OK OK OK
After:
$ ./runtest.py 001
001 basic               : OK OK OK OK OK OK OK OK OK OK
> tests: Properly check the number of workers for use_pool

- tests/runtest.py
Fix "NameError: name 'pr_debug' is not defined" error.
```
diff --git a/tests/t012_demangle.py b/tests/t012_demangle.py
index 2686c333..e0822eea 100644
--- a/tests/t012_demangle.py
+++ b/tests/t012_demangle.py
@@ -4,7 +4,7 @@ from runtest import TestBase
class TestCase(TestBase):
def __init__(self):
-        TestBase.__init__(self, 'demangle', lang='C++', result="""
+        TestBase.__init__(self, 'demangle', lang='Go', result="""
[31433] | ABC::foo() {
[31433] |   __static_initialization_and_destruction_0() {
```
```
$ ./runtest.py -vdp -O0 012
Test case                 pg
------------------------: O0
Traceback (most recent call last):
File "./runtest.py", line 905, in <module>
results = run_single_case(name, flags, opts.split(), arg)
File …
```
> tests: Fix NameError in build function

- utils/symbol-rawelf.h
Fix #1524 issue.
```
$ ./configure --without-libelf
...         prefix: /usr/local
...         libelf: [ OFF ] - more flexible ELF data handling
...          libdw: [ OFF ] - DWARF debug info support
...      libpython: [ on  ] - python scripting support
...      libluajit: [ on  ] - luajit scripting support
...    libncursesw: [ on  ] - TUI support
...   cxa_demangle: [ on  ] - full demangler support with libstdc++
...     perf_event: [ on  ] - perf (PMU) event support
...       schedule: [ on  ] - scheduler event support
...       capstone: [ on  ] - full dynamic tracing support
...      libunwind: [ on  ] - stacktrace support (optional for debugging)
$ make -j4
CC       cmds/recv.o
CC       cmds/report.o
CC       cmds/live.o
GEN      version.h
CC …
```
> utils: Fix build problems when building with --without-libelf option

- tests/runtest.py
Similar to issue #1509, sometimes TC 125 raised an IndexError with an abnormal output.
IndexError interferes with test normality, so I try to solve it with this PR.
- test normality even when abnormal results are output
- remove the code that checks for empty lines
- remove try...catch code with length check
- resolve pylint: No exception type (W0702:bare-except)
- Missing self time value
```
$ git diff
diff --git a/tests/runtest.py b/tests/runtest.py
index dfe39dfd..991443c5 100755
--- a/tests/runtest.py
+++ b/tests/runtest.py
@@ -334,6 +334,7 @@ class TestBase:
""" This function post-processes output of the test to be compared .
It ignores blank and comment (#) lines and remaining functions.  """
result = []
+        print (output)
for ln in output.split('\n'):
if ln.strip() == '': …
```
> tests: Fix IndexError by checking report length

- libmcount/dynamic.h
- tests/unittest.c
- utils/event.h
- utils/kernel.h
- utils/perf.h
- utils/symbol-rawelf.h
This patch makes headers independently buildable with the following
command.
$ find -name "*\.h" | grep -v prototypes.h | grep -v libtraceevent | xargs gcc -I. -I./arch/x86_64
It shows a single warning because of missing _GNU_SOURCE, but it's
manually defined in the current Makefile so it's not an issue.
Fixed: #1546
> uftrace: Make headers independently buildable

- utils/utils.h
Sometimes it's useful to add explicit breakpoints in the source code.
This patch adds a portable way of adding breakpoints with TRAP() macro.
> utils: Add TRAP() for adding explicit breakpoints

- tests/unittest.c
This patch is to fix the following warning when compiling unittest.
```
$ make unittest -j32
LINK     unittest
unittest.c:1: warning: "_GNU_SOURCE" redefined
1 | #define _GNU_SOURCE
|
<command-line>: note: this is the location of the previous definition
```
> tests: Fix "_GNU_SOURCE" redefined warning in unittest

- tests/t222_external_data.py
This is a fix for the test case found in #1509.
There was a issue where if there was a zero after the decimal point
like 8490.080467500, the zero was deleted when converting to int.
```
$ uftrace replay -f +time
[  9250]     8490.080467500 | main() {
[  9250]     8490.080467800 |   a() {
[  9250]     8490.080467800 |     b() {
[  9250]     8490.080467900 |       c() {
1.200 us [  9250]     8490.080468700 |         getpid();
2.700 us [  9250]     8490.080470600 |       } /* c */
2.900 us [  9250]     8490.080470700 |     } /* b */
3.000 us [  9250]     8490.080470800 |   } /* a */
3.400 us [  9250]     8490.080470900 | } /* main */
```
After the fix, it converts to 8490.080467501 instead of 8490.80467501.
```
$ cat uftrace.data/extern.dat 
8490.80467501 user message
```
```
$ cat …
```
> tests: Fix int conversion issue where zeros were discarded

- tests/s-diff.c
- tests/t025_report_s_call.py
- tests/t158_report_diff_policy1.py
- tests/t159_report_diff_policy2.py
- tests/t160_report_diff_policy3.py
- tests/t177_report_diff_policy4.py
- tests/t240_report_diff_field2.py
- tests/t241_report_diff_field3.py
- tests/t242_report_diff_field4.py
- tests/t243_report_diff_field5.py
The current diff tests have a common tricky problem because we can't
guarantee the difference of execution time for two different executions.
Because of this problem, some diff tests randomly fails as follows.
```
158 report_diff_policy1 : OK OK OK NG OK OK NG OK OK NG  OK OK OK OK OK OK OK OK OK OK
159 report_diff_policy2 : OK OK OK OK OK OK OK OK OK OK  OK OK OK NG OK OK OK OK OK OK
160 report_diff_policy3 : NG OK OK OK OK OK OK NG NG OK  OK OK OK OK OK OK OK OK OK OK
240 report_diff_field2  : OK OK OK NG OK OK NG NG OK OK  NG OK OK OK NG OK OK NG NG OK
241 report_diff_field3  : OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK OK OK OK NG OK
242 report_diff_field4  : OK OK OK OK OK OK OK OK OK OK  OK NG OK OK OK OK OK OK OK OK
243 report_diff_field5  : OK OK OK OK OK OK OK OK OK NG  OK NG …
```
> tests: Fix random failures in diff tests

- cmds/tui.c
- doc/ko/uftrace-tui.md
- doc/uftrace-tui.md
I add size field in report mode because filter options in report command.
contain the field but report mode in `tui` command doesn't.
I referenced commit `b0544ca8` to add this field.
Here is available fields for report mode in `tui` command.
```
./uftrace tui -d ~/test/hello.data --report -f?
uftrace: Unknown field name '?'
uftrace:   Possible fields are: total total-avg total-min total-max self self-avg self-min self-max call size
```
I also rename the macro `REPORT_FIELD_CALL` to `REPORT_FIELD_UINT`,
because of code consistency for commit `a926a9cf`.
Signed-off-by: Joonho Seo <tjwnsgh1110@gmail.com>
> tui: Add field "size" in report mode

- cmds/dump.c
- doc/uftrace-dump.md
- tests/runtest.py
- tests/t272_dump_mermaid.py
- uftrace.c
- uftrace.h
- utils/graph.c
- utils/graph.h
This option shows the function call graph as a mermaid flowchart
for visualization.
- mermaid page : https://mermaid-js.github.io/mermaid/
The usage for this option is add --mermaid in graph command.
The result can be rendered in the browser so it is formatted as HTML.
The mermaid syntax itself can be rendered in other services
including a mermaid plugin like github or draw.io.
The function name cannot be used as a node id because some suffix
like 'end', 'self' is indicated to special usage in mermaid.
So 'id' is added to identify the node to 'struct uftrace_graph_node'.
Signed-off-by: Jia Ha <wendyisdream1004@gmail.com>
> graph: Add the option to show function call graph as mermaid diagram

- .github/workflows/nightly-test.yml
- tests/runtest.py
This patch changes the usage of `--color` option in runtest.py from
boolean to string type, which can accept one of 'auto', 'on', or 'off'.
Having this option, we can always enable color in github action nightly.
> tests: Allow runtest.py --color to explicitly enable color

- tests/runtest.py
This patch fixes the following incorrect alignment in failed-tests.txt.
```
$ cat failed-tests.txt
Compiler                  gcc                            clang
Test case                 pg             finstrument-fu  pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os  O0 O1 O2 O3 Os O0 O1 O2 O3 Os
203 arg_dwarf3          : OK OK NG NG NG SK SK SK SK SK OK OK OK OK OK SK SK SK SK SK
```
It also makes the failed-tests.txt output with color because there is
another way to print the plain output with '--color off' option.
> tests: Fix failed-tests.txt output alignment

- scripts/dump.lua
- scripts/dump.py
As the timestamp represents in nanosecond unit, dump script wants to
show in second unit. But, in modular, the digits may not filled enough
ex.
_time = 1001002003
_time / unit == 1
_time % unit == 1002003
expected:
1.001002003
actual:
1.1002003
// may translated as 1s, 100ms, 200us, 300ns
So, need to change formatting text to start with leading zero, fixed
nine digits.
Signed-off-by: JaeSang Yoo <jsyoo5b@gmail.com>
> scripts: Correct dump scripts timestamp representation

- cmds/tui.c
- utils/utils.h
This PR contains the following changes.
- 65de9c6b utils: Add MIN() and MAX() helper macros
- 125beace tui: Add TUI_ASSERT() and TUI_DASSERT() helpers
- 3fc12800 utils: Add pr_flush() and use it in ASSERT/DASSERT
> utils: Apply some updates for utils helpers

- tests/s-fibonacci.c
This patch fixes the following test failures in t090_report_recursive.
```
$ ./runtest.py 090
Compiler                  gcc                            clang
Test case                 pg             finstrument-fu  pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os  O0 O1 O2 O3 Os O0 O1 O2 O3 Os
090 report_recursive    : OK OK OK OK OK OK OK OK OK OK  OK NG NG NG NG OK OK OK OK OK
```
It fails in clang optimized tests, but it's just because fib() function is optimized out.
To avoid this optimization, use the return value of fib() function.
> tests: Fix t090_report_recursive tests in clang

- tests/s-longjmp.c
Because compiler likes to optimize `bar()` for simplicity, Update 015 longjmp test code.
Fixed: #1576
> tests: Update 015 longjmp test code.

- Makefile
- cmds/dump.c
- tests/runtest.py
- tests/t272_dump_mermaid.py
- utils/mermaid.html
- utils/mermaid.js
This adds an interaction option to mermaid results. It allows users to
check the call graph step by step with one uftrace result.
It supports the following graph following the user's input.
a) Show the graph until specific call depth level.
When the function has sub call flow, clicking the function node
makes it attach the remaining call flow.
It allows to toggle show/hide sub-graph.
b) Show the partial graph starting from a specific function.
This partial graph also support the a) depth option
For this feature, the following is added.
1. Add the call depth level to mermaid node id as "depth_id" format.
2. Add html and javascript to make the option. This code is included
in the header file as raw string.
This header file is converted incorrectly in pre-commit
clang-format hook. So it is …
> dump: Add an interaction option to the mermaid result.

- Makefile
- cmds/live.c
- cmds/record.c
- libmcount/mcount.c
- tests/s-agent.c
- tests/t273_agent_basic.py
- uftrace.c
- uftrace.h
- utils/socket.c
- utils/socket.h
Hi,
This is a rework of PR #1269 from DORSAL. I moved the code to a new repository and made modifications according to old discussions. Sorry for the inconvenience.
This PR is the first step to interact with uftrace targets at runtime. It separates the CLI from the libmcount runtime, by spawning a daemon in libmcount, that is controlled by an separate and independent uftrace instance.
I introduce two new associated parameters:
- `--daemon`/`-m` to spawn the daemon in the target (off by default)
- `--pid`/`-p`to set uftrace to "client mode" and forward its parameters to a running target
Note that the daemon code is compiled conditionally in libmcount. It can be disabled using the `--without-daemon` flag in the configure script.
Follow-up steps:
- implement parameter tweaking at runtime …
> Introduce an agent in libmcount

- utils/socket.c
This patch adds explicit include to fix the following warnings.
```
utils/socket.c:12:6: warning: implicit declaration of function ‘unlink’ [-Wimplicit-function-declaration]
12 |  if (unlink(addr->sun_path) == -1) {
|      ^~~~~~
utils/socket.c:43:3: warning: implicit declaration of function ‘close’; did you mean ‘pclose’? [-Wimplicit-function-declaration]
43 |   close(fd);
|   ^~~~~
|   pclose
```
> utils: Fix warnings in utils/socket.c

- cmds/record.c
- doc/uftrace-dump.md
- doc/uftrace-graph.md
- doc/uftrace-live.md
- doc/uftrace-record.md
- doc/uftrace-replay.md
- doc/uftrace-report.md
- doc/uftrace-script.md
- doc/uftrace-tui.md
- libmcount/mcount.c
- misc/dbginfo.c
- tests/t274_filter_loc1.py
- tests/t275_filter_loc2.py
- tests/t276_filter_loc3.py
- uftrace.c
- uftrace.h
- utils/data-file.c
- utils/dwarf.c
- utils/dwarf.h
- utils/filter.c
- utils/filter.h
- utils/fstack.c
The -O option supports a filter that traces or does not trace the selected
source location with the debug_info loaded.
These are usage example.
The '--srcline' option is required when using record command.
```
$ uftrace record --srcline t-lib
```
The '-O' option is required when using replay command to set a filter to
trace selected source files.
```
$ uftrace replay -O s-libmain.c --srcline
[  4636] | main() { /* /home/uftrace/tests/s-libmain.c:16 */
4.119 us [  4636] |   foo(); /* /home/uftrace/tests/s-libmain.c:11 */
4.544 us [  4636] | } /* main at /home/uftrace/tests/s-libmain.c:16 */
```
You can set a filter to not trace selected source files with the '@hide' suffix.
```
$ uftrace replay -O s-libmain.c@hide
[  5327] | lib_a() {
[  5327] |   lib_b() {
1.226 us [  5327] |     lib_c(); …
```
> filter: Add -L/--loc-filter option to filter by source location 

- .github/workflows/nightly-test.yml
- tests/runtest.py
Since test result is getting bigger, option for printing only abnormal result can be useful at this point.
So this commit adds -q, --quiet for runtests.py,
which can be used as follows:
```
$ ./runtest.py -q
Start 272 tests with 56 worker
Compiler                  gcc                            clang
Test case                 pg             finstrument-fu  pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os  O0 O1 O2 O3 Os O0 O1 O2 O3 Os
015 longjmp             : OK OK OK OK OK OK OK OK OK OK  OK NG NG NG NG OK OK OK OK OK
062 arg_char            : OK OK OK OK OK SK SK SK SK SK  OK NG NG NG NG SK SK SK SK SK
082 arg_many            : OK OK OK OK OK SK SK SK SK SK  NG OK OK OK OK SK SK SK SK SK
084 arg_mixed           : OK OK OK OK OK SK SK SK SK SK  OK NG …
```
> tests: Add -q/--quiet option for runtests.py and nightly test

- Makefile
- misc/bench.c
- misc/bench.sh
There are multiple issues in bench compilation as follows.
First, the baz does not return a value although its return type is int so set it to void.
```
uftrace/misc/bench.c:12:1: warning: non-void function does not return a value [-Wreturn-type]
```
Second, the bench.sh script uses bash syntax, but its shebang is /bin/sh so it makes the following error in some environments.
```
$ make bench
...
./bench.sh: 11: Syntax error: "(" unexpected
make: *** [Makefile:390: bench] Error 2
```
Lastly, the bench executable requires it to be compiled with -pg, but android build doesn't support -pg build so it shows the following error.
```
clang-14: warning: argument unused during compilation: '-pg' [-Wunused-command-line-argument]
ld: error: undefined symbol: _mcount
```
It seems there is no reason …
> bench: Fix multiple problems and issues in bench

- misc/install-deps.sh
Since ID in /etc/os-release cannot contain distribution in /misc/install-deps.sh,
/etc/os-release can also have ID_LIKE,
which can contain distribution in /misc/install-deps.sh like below:
```
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
So this commit adds parsing logic in /misc/install-deps.sh to check ID first, and ID_LIKE also.
Closes: #1468
> misc: Check ID_LIKE along with ID in /etc/os-release

- Makefile
Sometimes build fails like below
| /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/core2-64-poky-linux/uftrace/0.13-r0/git/cmds/dump.c: In function 'dump_mermaid_footer': | /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/core2-64-poky-linux/uftrace/0.13-r0/git/cmds/dump.c:1347:10: fatal error: utils/mermaid.html.cstr: No such file or directory |  1347 | #include "utils/mermaid.html.cstr" /* This file is a converted of mermaid.html to one string literal in build-time */
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.
| make[1]: *** [Makefile:310: /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/core2-64-poky-linux/uftrace/0.13-r0/build/cmds/dump.o] Error 1
Create a dependency on c-str-conversion for dump.o
Signed-off-by: Khem Raj …
> Fix a build race related to utils/mermaid.html.cstr

- tests/runtest.py
- tests/t117_time_range.py
- tests/t122_time_range2.py
- tests/t125_report_range.py
- tests/t135_trigger_time2.py
- tests/t151_recv_runcmd.py
- tests/t222_external_data.py
- tests/t223_dynamic_full.py
- tests/t225_dynamic_size.py
- tests/t233_dynamic_unpatch2.py
- tests/t248_dynamic_dlopen.py
- tests/t263_patchable_dynamic.py
- tests/t264_patchable_dynamic2.py
- tests/t265_patchable_dynamic3.py
- tests/t266_patchable_dynamic4.py
- tests/t267_patchable_dynamic5.py
- tests/t269_arg_no_args_replay.py
- tests/t270_arg_no_args_dump.py
- tests/t277_time_range3.py
This PR adds testing configuration for `-fpatchable-function-entry` to `runtests.py`. It mostly fails on GCC due to #1613 but works well with clang (955 tests passed VS 1006 with `-pg`).
> Enable testing of -fpatchable-function-entry instrumentation.

- Makefile
This patch adds a build option DEBUG=2 that enables '-gdwarf-2 -g3' and it allows gdb to understand C/C++ macros as follows.
```
$ make DEBUG=2
...
$ gdb -q -ex="b main" -ex="r" --args uftrace
Reading symbols from uftrace...
Breakpoint 1 at 0x10873: file /home/honggyu/work/uftrace/uftrace.c, line 1368.
Starting program: /home/honggyu/work/uftrace/uftrace
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Breakpoint 1, main (argc=1, argv=0x7fffffffdd38) at /home/honggyu/work/uftrace/uftrace.c:1368
1368    {
(gdb) info macro list_entry
Defined at /home/honggyu/work/uftrace/utils/list.h:343
included at /home/honggyu/work/uftrace/utils/argspec.h:4
included at /home/honggyu/work/uftrace/utils/filter.h:9
included at …
```
> build: Add DEBUG=2 build option for macro debugging

- arch/aarch64/mcount-dynamic.c
- arch/x86_64/mcount-dynamic.c
This change simplifies the code and is also compatible with Android.
It shows no regressions on x86_64 when tested on top of #1614
> Read patchable entries from memory instead of disk

- utils/demangle.c
This commit fixes following things:
1. Ignore traits (See #1620)
2. Demangle '..' to '::'
3. Consume extra '_' at starting point of string
4. Add placeholder to support Rust v0 mangling rule (start with '_R')
However, because of 2, it replace the '..' to '::', it need a write permission for the source string. It makes segfault for the demangle test because the source string is const.
Signed-off-by: ChoKyuWon <kyuwoncho18@gmail.com>
> demangle: More elaborated demangling for Rust

- INSTALL.md
- Makefile
- README.md
- cmds/live.c
- cmds/record.c
- configure
- libmcount/dynamic.c
- libmcount/internal.h
- libmcount/mcount.c
- libmcount/plthook.c
- libmcount/record.c
- utils/shmem.c
- utils/shmem.h
- utils/symbol.c
This is an updated port of uftrace to Android platform. I have got rid of dedicated Ashmem-based code and instead followed the [termux approach](https://github.com/termux/termux-packages/blob/master/packages/uftrace/cmds-record.c.patch) which mimics the `shm_open`/`shm_unlink` APIs using temporary files.
With these changes uftrace works for simple command-line tools in x86_64/AArch64 adb shell (compiled with `-fpatchable-function-entry=5`/`=2` respectively), both on emulator and on real device.
> uftrace: Port to Android x86_64/AArch64.

- Makefile
Sometimes compiler inserts some builtin functions such as memcpy, memmove even if the source code doesn't have them at all.
It's internally used because the compiler thinks that using those calls is faster when optimized.
However, this can overwrite vector registers such as xmm registers in x86 or VFP registers in arm and that makes uftrace record floating point arguments or return values incorrectly.
One of the example can be found as follows.
```diff
$ ./runtest.py -vdp -c gcc -O0 083
...
t083_arg_float: diff result of gcc -pg -O0
--- expect      2023-02-16 19:28:09.750616419 +0900
+++ result      2023-02-16 19:28:09.750616419 +0900
@@ -4,3 +4,3 @@
float_mul(300.000000, 400.000000) = 120000.000000;
-   float_div(40000000000.000000, -0.020000) = -2000000000000.000000;
+ …
```
> libmcount: Turn off unexpected vectorization in libmcount

- INSTALL.md
- Makefile
- configure
This commit changes default uftrace library location from `${prefix}/lib` to `${prefix}/lib/uftrace`.
Also users can set library location with `--libdir=<DIR>` option of configure script like below:
```
$ ./configure --libdir=/home/minchul/libuftrace
$ cat .config
override prefix := /usr/local
override bindir := /usr/local/bin
override libdir := /home/minchul/libuftrace
...
$ make && sudo make install
...
$ ls /home/minchul/libuftrace/
libmcount-fast-single.so  libmcount-fast.so  libmcount-nop.so  libmcount-single.so  libmcount.so
```
Closes: #1618
> uftrace: Modify install location for uftrace libraries

- cmds/recv.c
- tests/runtest.py
- tests/s-dwarf1.c
- tests/s-dwarf5.c
- tests/s-exp-char.c
- tests/s-exp-mixed.c
- tests/s-ucontext.c
- tests/t147_event_sdt.py
- tests/t151_recv_runcmd.py
- tests/t200_lib_dlopen2.py
- tests/t220_trace_script.py
- tests/t225_dynamic_size.py
This PR fixes some tests with the following patches.
- d5c8653f tests: Fix broken -fpatchable-function-entry tests
- 3142999e tests: Rename --patch-functions option in runtest.py
- 7ea2051f tests: Fix check_perf_paranoid() routine
> tests: Fix multiple issues in runtest.py

- .pre-commit-config.yaml
- gdb/uftrace/mcount.py
- gdb/uftrace/plthook.py
- gdb/uftrace/trigger.py
The pre-commit shows an error in isort hook as follows.
RuntimeError: The Poetry configuration is invalid
This can be fixed by upgrading isort rev to 5.11.5 so this patch changes the version to fix it.
In addition, apply changes from isort 5.11.5 to make pre-commit happy.
Link: https://github.com/PyCQA/isort/issues/2083#issuecomment-1408300628
> pre-commit: Fix RuntimeError in isort hook

- tests/s-posix_spawn.c
The current t191_posix_spawn.py test fails as follows in clang build.
```
191 posix_spawn         : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  NG OK OK OK OK NG OK OK OK OK NG OK OK OK OK
```
The error comes from that the array initialization is done using implicit 'memset' call inside as follows.
```diff
$ ./runtest.py -vdi -O0 -c clang 191
...
t191_posix_spawn: diff result of clang -finstrument-functions -O0
--- expect      2023-02-25 07:50:25.639449974 +0900
+++ result      2023-02-25 07:50:25.639449974 +0900
@@ -1,2 +1,3 @@
main() {
+   memset();
posix_spawn();
191 posix_spawn         : NG
```
This patch simplifies the test program to suppress this 'memset' call.
> tests: Fix t191_posix_spawn.py

- arch/x86_64/fentry.S
The current s-nested.c gets crashed when built with -fpatchable-function-entry as follows.
```
$ gcc -fpatchable-function-entry=5 s-nested.c
$ uftrace record -P foo_internal.0 a.out
WARN: Segmentation fault: invalid permission (addr: 0x7fff263b3080)
```
The crash happens because the inner function 'foo_internal.0' reads r10 register to access variables in the outter function.
However, our '__fentry__' implementation doesn't push r10 register for later usage so r10 is changed unexpectedly.
The x86-64-ABI document[1] describes r10 register as follows.
```
r10 is used for passing a function's static chain pointer.
```
This patch pushes r10 register inside '__fentry__' and it also pushes r11 register together just like '__dentry__' does[2].
[1] …
> x86_64: Fix an error in s-nested.c with -fpatchable-function-entry

- tests/t135_trigger_time2.py
The current t135_trigger_time2.py fails in some cases as follows.
```
$ ./runtest.py 135
Compiler                  gcc                                           clang
Test case                 pg             finstrument-fu fpatchable-fun  pg             finstrument-fu fpatchable-fun
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 O1 O2 O3 Os  O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 O1 O2 O3 Os
135 trigger_time2       : OK OK OK OK OK NG OK OK OK OK NG OK OK NG OK  OK OK OK OK OK OK OK OK OK OK OK OK OK OK NG
```
The failure comes from that 'free' is discarded from the result.
```
t135_trigger_time2: diff result of gcc -finstrument-functions -O0
--- expect      2023-02-25 11:30:13.744456689 +0900
+++ result      2023-02-25 11:30:13.744456689 +0900
@@ …
```
> tests: Fix t135_trigger_time2.py test

- misc/bench.c
- utils/event.c
- utils/extern.c
Hello Namhyung and Honggyu!
I'm back with this very short fix to begin with, because some unit tests can't compile with old gcc.
After having figured out our upstreaming process at Ciena, I'm ready to send you propositions for the agent in upcoming pull requests. I suggest you label my work as `ciena` from now if you want.
> unittest: Fix c99 compiler error

- tests/runtest.py
@namhyung :
When packaging `uftrace` for Fedora using the Copr build service, I enabled running the test suite for checking the build.
I found that on some CentOS 8 build targets, a few tests caused `test/runtest.py` to crash because they referenced an `variable[1]` without first checking if `variable[1]` can be indexed.
Catch this exception in runtest.py and (hopefully) handle it correctly as a diff in the test case result.
> Catch IndexError from self.sort in test/runtest.py

- README.md
A simple way to to make the command-specific markdown files easily accessible is to link them from README.md
> README.md: Add links to command-specific documentation

- tests/runtest.py
- tests/t002_argument.py
- tests/t051_return.py
This fixes about a dozen test case failures using the s-arg.c and s-return.c files on aarch64:
On aarch64 (depending on a number of factors including size and optimisation level) gcc and clang use `memcpy()` to pass and `return` big `structs` to and from function calls.
For large 4k returns, `gcc` may emit `memcpy()` for all optimization level, while for other smaller structs, gcc and clang may emit memcpy() this only for lower optimisation levels.
For smaller structs, gcc and clang may emit memcpy() only    for lower optimisation levels.
In additon, it may change from one compiler version to the next.
It affects all tests tracing s-arg.c:pass() / return.c:return_large()
Two test cases did already filter memcpy(), but about a dozen other test failures were caused by unexpected memcpy() in …
> aarch64/runtest.py: Fix tests where gcc/clang emits memcpy()

- cmds/recv.c
Commit message:
cmd/recv.c: Migrate from deprecated gethostbyname() to getaddrinfo()
The Fedora review-tool runs rpmlint on the binary packages and warned
that the uftrace tool was using gethostbyname. Switching to getaddrinfo
helps to get accepted, also for later uftrace distro packaging reviews:
POSIX.1-2008 removes the specifications of gethostbyname(), gethostbyaddr(),
and h_errno, recommending the use of getaddrinfo(3) and getnameinfo(3) instead:
They return a list of addrs or hostnames, are thread-safe and optionally
allow us to also use IPv6. This 1st step continues with IPv4 and only
still tries to connect to the primary, 1st address (for a small commit).
> cmd/recv.c: Migrate from deprecated gethostbyname() to getaddrinfo()

- cmds/tui.c
Even though tui command started with the report mode, the loading message was "Building graph for TUI...". This commit changes the loading message for the report mode.
> tui: Change the loading message for report mode

- README.md
LanguageTool and LTeX issue warnings when sentences (or list items) repeatedly start with the same word:
_With the recorded data, it:_
_- Can .._
_- Can .._
_- Can .._
Fix this by moving the "can" into the introduction and omit the "Can" from the list. Also fix the last sentence which didn't fit this yet:
_With the recorded data, uftrace can:_ 
_- Show colored and nested function call graphs._ 
_- Show arguments and return values symbolically using libc function prototypes_ 
_  and DWARF debug information._ 
_- Apply filters to minimize the amount of trace data in both record and replay time._ 
_- Extract metadata from traces. (e.g. system information on which the trace was taken)_ 
_- Generate symbol tables and memory maps of the traced program and library functions._ 
_- Generate task …
> README.md: Improve paragraph on features regarding recorded trace data

- Makefile
@namhyung :
Fedora packaging dictates that `/etc` is dedicated for bash completions installed and managed by the system admin and bash completions installed by the packages shall live in `/usr/share` (referenced by `%{_datadir}`)
Support packaging for distros by using a common variable at all locations where we install the bash completions script, which distribution packages can override.
> Allow customizing the bash completions dir for system-RPM installs

- doc/uftrace-info.md
Improve the manual for  `--symbols EXECUTABLE`:
- Fix that the traced executable to generate symbol information for is an required option of the `--symbols EXECUTABLE` argument.
- While at it, update the description as well.
> doc/uftrace-info.md: Improve the description of info --symbols <exe>

- cmds/live.c
- libmcount/mcount.c
- uftrace.h
- utils/socket.c
- utils/socket.h
Hi Namhyung,
I reworked the client/agent protocol, as discussed in #1652.
This PR doesn't implement any option in the client, it is only about the protocol.
Two things to notice:
- the `forward_option()` function is unused because we do not send options yet
- I added a `GET_OPT` message but its action is not implemented (only a placeholder for now)
Closes: #1652
> Implement client/agent protocol

- utils/kernel.c
exit_to_user_mode_prepare tends to be shown unnecessarily many times in kernel tracing result as follows.
```
$ cat hello.c
#include <stdio.h>
int main()
{
printf("Hello World\n");
fflush(stdout);
return 0;
}
$ gcc -pg -o hello hello.c
$ sudo ./uftrace -F main -k hello
Hello World
[ 18510] | main() {
[ 18510] |   puts() {
0.177 us [ 18510] |     down_read_trylock();
0.147 us [ 18510] |     __cond_resched();
0.334 us [ 18510] |     find_vma();
2.159 us [ 18510] |     handle_mm_fault();
0.150 us [ 18510] |     up_read();
0.216 us [ 18510] |     exit_to_user_mode_prepare();
4.651 us [ 18510] |     __x64_sys_newfstatat();
0.219 us [ 18510] |     exit_to_user_mode_prepare();
11.518 us [ 18510] |     __x64_sys_write();
0.218 us [ 18510] |     exit_to_user_mode_prepare();
24.233 us [ 18510] | …
```
> kernel: Add "exit_to_user_mode_prepare" in kernel skip list

- gdb/uftrace/rbtree.py
- libmcount/mcount.c
- utils/filter.c
- utils/filter.h
Hello Namhyung and Honggyu,
I'm submitting this pull request to make it easier to implement #1645.
The idea is to interact with the `mcount_triggers` rbtree in an RCU-like fashion. The approach is simple: I deep copy the whole tree when the agent want to modify it. Then I atomically swap the pointers when the agent is done (on connection end).
I use an arbitrary grace period of `1s`, which blocks the agent. What do you think?
Note: If we are to use hash maps instead of an rbtree in the future, we could take advantage of [liburcu](https://liburcu.org/), which defines RCU-capable hash maps (but not rbtrees). I don't plan to be able to work on this though.
> mcount: Add RCU-like capabilities to the rbtree

- libmcount/dynamic.c
Currently, dynamic patch stat info is not printed when there is skipped functions without failed one.
This patch also checks whether there is a skipped function to print dynamic patched function stats.
```
$ uftrace record --debug-domain dynamic:1 -P. -Z 10 a.out
dynamic: dynamic patch type: a.out: 0 (none)
dynamic: patched all (4) functions in 'a.out'
```
Before:
```
$ uftrace record --debug-domain dynamic:1 -P. -Z 30 a.out
dynamic: dynamic patch type: a.out: 0 (none)
```
After:
```
$ uftrace record --debug-domain dynamic:1 -P. -Z 30 a.out
dynamic: dynamic patch type: a.out: 0 (none)
dynamic: dynamic patch stats for 'a.out'
dynamic:    total:        4
dynamic:  patched:        2 (50.00%)
dynamic:   failed:        0 ( 0.00%)
dynamic:  skipped:        2 (50.00%)
dynamic: no match:        0 …
```
> dynamic: Print dynamic patch stats for skipped

- python/trace-python.c
- python/uftrace.py
The following commit moved import uftrace_python at the top of script.
e26f74c8 python: Set __file__ attribute properly
But it makes the source location info missing as follows.
```
$ uftrace --srcline ./p-abc.py
[ 43034] | __main__.<module>() { /* (null):1 */
[ 43034] |   a() { /* (null):11 */
[ 43034] |     b() { /* (null):8 */
[ 43034] |       c() { /* (null):5 */
1.255 us [ 43034] |         posix.getpid();
5.577 us [ 43034] |       } /* c */
8.690 us [ 43034] |     } /* b */
11.348 us [ 43034] |   } /* a */
16.299 us [ 43034] | } /* __main__.<module> */
```
The source file name is set to UFTRACE_PYMAIN environment variable and get the env inside uftrace_python.so.
So the import statement has to be moved below to UFTRACE_PYMAIN set. After moving it below, the source file name looks …
> python: Fix source location missing problem

- README.md
We've had gitter for chat room but it'd be better to switch it to discord.
I hope many more people to join the community and let's talk in discord.
> doc: Change the chat from gitter to discord

- cmds/live.c
- cmds/record.c
- doc/uftrace-live.md
- doc/uftrace-record.md
- doc/uftrace-replay.md
- doc/uftrace.html
- libmcount/mcount.c
- tests/s-agent.c
- tests/t038_trace_disable.py
- tests/t039_trace_onoff_F.py
- tests/t040_replay_onoff.py
- tests/t041_replay_onoff_N.py
- tests/t042_live_disable.py
- tests/t273_agent_basic.py
- tests/t281_agent_trace_toggle.py
- uftrace.c
- uftrace.h
- utils/filter.h
- utils/fstack.c
Hi Namhyung and Honggyu,
This PR makes it possible to pause and resume tracing from the client, in a similar fashion to `trace_on` and `trace_off` triggers. When tracing is stopped, the instrumentation is simply skipped on function entry or exit, and event collection doesn't take place.
This mechanism can be used in conjunction with function or signal trigger actions.
```
$ uftrace record --agent --trace=off ./prog
$ uftrace --pid $(pidof prog) --trace=on     # toggle tracing on
$ uftrace --pid $(pidof prog) --trace=off    # toggle tracing back off
```
I'm refactoring the `--disable` option to `--trace=on|off` for clarity.
I'm simplifying agent internals to make it easier to integrate other options.
~Based on: #1642~
~Based on: #1665~
> mcount: Toggle tracing at runtime

- cmds/record.c
- utils/utils.c
- utils/utils.h
fix: https://github.com/namhyung/uftrace/issues/1690
Signed-off-by: Yi Hong [zouzou0208@gmail.com](mailto:zouzou0208@gmail.com)
> fix: #1690 unable to identify shebang when it has initial spaces 

- arch/x86_64/mcount-insn.c
In Ubuntu 20.04, latest libcapstone-dev package version is 3.0.5. However, CS_GRP_PRIVILEGE and CS_GRP_BRANCH_RELATIVE macros are declared in over 4.0.x version.
Add a macro to check CS_API_MAJOR version is over 4.
Fixed: https://github.com/namhyung/uftrace/issues/1712
Signed-off-by: Michelle Jin <shjy180909@gmail.com>
> compile: Fix compile error due to low libcapstone-dev package version

- cmds/live.c
- doc/uftrace-live.md
- doc/uftrace-record.md
- libmcount/mcount.c
- libmcount/mcount.h
- tests/s-agent.c
- tests/t273_agent_basic.py
- tests/t284_agent_filter.py
- tests/t285_agent_caller_filter.py
- uftrace.h
- utils/auto-args.c
- utils/filter.c
- utils/filter.h
- utils/fstack.c
These commits give the user full control over tracing filters at runtime. It
applies to the following filters:
- opt-in filters set by `-F/--filter`
- opt-out filters set by `-N/--notrace`
- caller filters set by `-C/--caller-filter`
It allows the user to control the target process from the client as follows:
- add or update an opt-in name filter
- `$ uftrace -p PID -F func`
- add or update an opt-out name filter
- `$ uftrace -p PID -N func`
- remove an opt-in or opt-out name filter
- `$ uftrace -p PID -F func@clear`
- add a caller filter
- `$ uftrace -p PID -C func`
- delete a caller filter
- `$ uftrace -p PID -C func@clear`
- set the pattern matching type
- `$ uftrace -p PID --match <simple|regex|glob>`
We also introduce an internal agent command `AGENT_CAPABILITIES`. It prompts
the …
> Control name filters at runtime

- libmcount/mcount.c
This patch remove warning at function `mcount_filter_init()`
declaration-after-statement.
Fixed: #1716
> mcount: remove variable declaration-after-statement

- Makefile
- check-deps/__have_libcapstone.c
- libmcount/mcount.c
- tests/s-diff.c
- utils/filter.c
- utils/fstack.c
This patch remove argument on void non-args function when using
`fstack_get_loc_mode()`, fstack_get_filter_mode()`.
Fixed: #1719
> uftrace: Add 'void' to functions without arguments

- python/trace-python.c
- python/uftrace.py
- tests/p011_libcall_nested.py
- tests/p012_os_exit.py
- tests/runtest.py
- tests/s-abc-exit.py
When os._exit() is invoked in the target python program, uftrace can't write the symbol and dbginfo files because it doesn't invoke the destructor.
This patch fixes the problem by hooking os._exit and invoke the destructor manually then call _exit().
Fixed: #1685
> python: Handle os._exit() properly

- doc/uftrace-live.md
- doc/uftrace-record.md
Hi,
This is an update to the documentation related to the agent.
I describe the `--agent` and `--pid` options and show examples.
> doc: Describe agent usage

- cmds/live.c
- libmcount/mcount.c
- tests/t286_agent_trigger.py
- uftrace.c
- uftrace.h
- utils/filter.c
- utils/filter.h
These commits give the user full control over triggers at runtime. It applies to
all actions.
It allows the user to control the target process from the client as follows:
- add or update trigger actions
- `$ uftrace -p PID -T func@act1[,act2]`
- delete one or more trigger actions
- `$ uftrace -p PID -T func@act1[,act2],clear`
- delete all trigger actions for a symbol
- `$ uftrace -p PID -T func@clear`
Trigger parameters can be omitted when deleting actions. For example:
- `$ uftrace -p PID -T func@depth,clear`
- `$ uftrace -p PID -T func@time,read,clear`
We also fix the `--trigger` option which was actually not implemented.
Based on #1645.
> Control triggers at runtime

- utils/filter.c
Hi, I spotted a printf debug line that I forgot to remove in a previous PR. You probably want to get rid of it before v0.14.
Related: #1714
> filter: Cleanup debug code

- doc/uftrace.html
Since uftrace now supports python function tracing, it'd be better to have a section in the tutorial slide.
> doc: Add a python function tracing section in slide

- Makefile
- NEWS
It's time for a new release.  Please test and report any issues!
In this development cycle, we've seen many interesting changes including:
* Python language support
* Runtime option changes with agent
* Android build support
And of course, a lot more fixes and improvements are there as well.  Thanks for all the contributors.
> New release: v0.14

- README.md
uftrace provides mulitiple ways for user space function tracing, but it might be confusing to users suggesting all the options in README.md.
We better inform a few options including -pg, -finstrument-functions and -fpatchable-function-entry=N.
> doc: Update README.md for user space function tracing

- cmds/record.c
- doc/uftrace-record.md
- uftrace.c
To process the `-k` option, the `kernel_depth` in opt field is not set and is set to 1 when used (`setup_writers`).
This PR initializes the `opts->kernel_depth` to 1 at the case  `-k` and `-K` if the input value is invalid.
This refactoring clarifies the code semantic when the user only uses the `-k`, and invalid `-K`.
> Refactor the kernel depth option and documentation

- libmcount/dynamic.c
This is the second PR in a series of patches intended to bring runtime dynamic tracing on x86_64 to uftrace.
1. #1702 
2. #1703 🠈
3. #1704
4. #1705
5. #1745
6. #1746
7. #1747
8. #1748
9. #1749
10. #1750
11. #1751
We redefine the pattern handling logic to remove default behaviors that conflict with runtime dynamic patching. We adapt it to runtime dynamic unpatching.
Related: #1698
> dynamic: Refactor patch pattern logic

- tests/runtest.py
tests: Change test result statistics condition
As it comes with more combinations of compiler and flags,
it's better to update the condition to print the test stats.
Specifically we want to print it when there are more than
300 test runs or more than 10 kind of tests were run.
Fixed: #1770 
Signed-off-by: Jungmin Kim <jungmin82@gmail.com>
> tests: Changing test case statistics conditions.

- utils/demangle.c
Currently, uftrace demangles all symbols, regardless of whether they are mangled C++ symbols or unmangled C symbols.
But when setting --demangle=full, uftrace calls __cxa_demangle(), which translates unmangled symbols confusingly; e.g., "f" is translated to "float".
To address this, now we only call __cxa_demangle() if a symbol is mangled (starts with "_Z").
Fixed #1778
> utils: fix demangle_full to only demangle mangled C++ symbols

- doc/uftrace.md
Currently make install on some Ubuntu versions failed like below:
```
GEN      uftrace.1
pandoc: blocks is null
CallStack (from HasCallStack):
error, called at src/Text/Pandoc/Writers/Man.hs:287:47 in pandoc-1.19.2.4-HbfKWUyODESBIy0vGktOwX:Text.Pandoc.Writers.Man
Makefile:18: recipe for target 'uftrace.1' failed
```
It's because the description of --task option has incompatible format in
the pandoc syntax.  We don't need that part so let's get rid of it.
Fixed: #1766
> misc: modify manual to build dockerfile

- tests/runtest.py
Using `socket` module and scan ports linearly, and select unused(unbinded) port.
Also, still sometimes when I run test recv test cases parallelly (such as `t142_recv_multi.py`), still got `connection refused` error. Perhaps these are caused by race condition.
```
ubuntu@ubuntu:~/uftrace/tests$ for i in `seq 25`; do (python3 runtest.py -d 142); done 
Compiler                  gcc                                         
Runtime test case         pg             finstrument-fu fpatchable-fun
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 O1 O2 O3 Os
142 recv_multi          : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK
Compiler                  gcc                                         
Runtime test case …
```
> tests: fix `gen_port()` to select unbind ports

- cmds/dump.c
After Mermaid v10, the function `mermaid.render` does not support callback, but only supports async operation.
This commit fixed the Mermaid to work by temporarily specifying the version of Mermaid as v9.
Ps. The PR has temporarily specified a version of the mermaid. Please do not close issue as we are planning to rewrite `mermaid.js` for ESM in the future.
Ref: #1793
> dump: Fix Mermaid to work properly by specifying the version of Mermaid

- utils/tracefs.c
When parsing /proc/self/mountinfo on some kernels, the number of fields is different and tracefs cannot be obtained.
changed method to check if paths of "/sys/kernel/tracing (tracefs)" and "/sys/kernel/debug/tracing (debugfs)" exist
Fixed: namhyung/uftrace#1753
> utils: Fix an issue not finding tracefs on some kernels

- doc/ko/uftrace.md
- doc/uftrace.md
While translating, I found a small typo error in `uftrace.md` manpage, so I fixed them.
---
Also, here are some additional fixed point suggestion:
https://github.com/namhyung/uftrace/blob/c7c58d7a4aa33009cc14f6053f7fffd51cc4c78a/doc/uftrace.md?plain=1#L17-L21
* `uftrace` now support `rust` and `python` files, not only `C` or `C++` executable file.
https://github.com/namhyung/uftrace/blob/c7c58d7a4aa33009cc14f6053f7fffd51cc4c78a/doc/uftrace.md?plain=1#L39-L47
* When we type `uftrace --help`, the command sequence is `record`, `replay`, `report`, `live`, ..., but the document is `record`, `replay`, `live`, `report` order.
If this suggestion is accepted, I'll amend the commit about these points in this PR.
> doc: Fix typo in uftrace.md

- utils/filter.h
The function add_trigger has been replaced with update_trigger,
rendering it unnecessary. This commit removes the now-unused
add_trigger function.
related: https://github.com/namhyung/uftrace/commit/eeb5d745de91cf6316d27d3270b4b5aa739df55b
Signed-off-by: Soyeon Park <sypark9646@gmail.com>
> filter: Remove obsolete function add_trigger

- misc/wget-pr.sh
GitHub provides an easy way to download the patches of PR by adding .patch postfix to the URL of PR.
This patch adds a simple script that can download the patch of the given pull request.
The usage is simple as follows.
```
$ ./misc/wget-pr.sh
usage: ./misc/wget-pr.sh <PR number>
```
If you want to download the patch of the PR number 1526, then it can be used as follows.
```
$ ./misc/wget-pr.sh 1526
--2023-08-27 07:04:48--  https://github.com/namhyung/uftrace/pull/1526.patch
...
Saving to: ‘1526.patch’
1526.patch              [ <=>                ]   5.47K  --.-KB/s    in 0s
2023-08-27 07:04:48 (22.2 MB/s) - ‘1526.patch’ saved [5601]
```
Then simply apply the 1526.patch file by running 'git am'.
```
$ git am 1526.patch
Applying: record: Do not initialize when libmcount.so is explictly …
```
> misc: Add wget-pr.sh script

- utils/utils.h
The function `get_event_name` in utils/utils.h
is not used within uftrace.
This commit deletes the unused `get_event_name` function.
> utils: Remove unused function: get_event_name

- arch/aarch64/mcount-dynamic.c
- arch/i386/mcount-dynamic.c
- arch/x86_64/mcount-dynamic.c
By trying to allocate the extra page for a trampoline with MAP_FIXED, Uftrace could end up overlapping already mapped pages, which are discarded.  Typically, if data was there with rw- protection, now the data is undefined and has rwx protection.
Since Linux 4.17, the flag MAP_FIXED_NOREPLACE can be used to ensure that the fixed location is mapped atomically, preventing any clobbering.
For earlier kernel, the call to mmap(2) will fall back to a random address, by not honoring the MAP_FIXED request at all.  So callers should ensure that the returned address matches the requested one.
> mcount-dynamic: Use MAP_FIXED_NOREPLACE for trampoline

- tests/runtest.py
apply `black` for linting, and follow common rules in python code.
The following warnings from [pylint](https://github.com/PyCQA/pylint) are fixed.
If you want to find the full pylint warning, run the following command:
```
pylint tests/runtest.py 
```
And if you want to find a specific pylint warning(ex. W0613), you can run a command like this:
```
pylint tests/runtest.py --disable R,C,W,E --enable W0613
```
resolves #1497 
related #1396
> tests: Change tests/runtest.py to match the pylint code style

- arch/x86_64/mcount-dynamic.c
- libmcount/dynamic.c
We have missed handling -U option to functions compiled with -fpatchable-function-entry.
This patch fixes the problem as follows.
Before:
```
$ ./runtest.py "265|266"
Start 2 tests with 2 worker
Compiler                  gcc                                           clang
Runtime test case         pg             finstrument-fu fpatchable-fun  pg             finstrument-fu fpatchable-fun
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 O1 O2 O3 Os  O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 O1 O2 O3 Os
265 patchable_dynamic3  : NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG  NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG
266 patchable_dynamic4  : NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG  NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG
```
After:
```
$ ./runtest.py "265|266"
Start 2 tests with …
```
> dynamic: Fix -U for -fpatchable-function-entry

- arch/x86_64/mcount-noplt.c
- arch/x86_64/symbol.c
- libmcount/internal.h
- libmcount/plthook.c
- utils/symbol.c
- utils/symbol.h
Issue #1777 reported that no-plt binary is handled as plt-enable binary because some functions are still left in plt section. The patch fixes this bug by comparing the name of self with a list of known functions.
> libmcount: support no-plt binary

- uftrace.c
When option parsing failed or binary name is not given, main function returns directly without freeing memory.
This commit fix it with goto cleanup when the main function exit.
Fixes: #1822
> uftrace: fix a memory leak when option parsing failed

- arch/riscv64/Makefile
- arch/riscv64/cpuinfo.c
- arch/riscv64/mcount-arch.h
- arch/riscv64/mcount-support.c
- arch/riscv64/mcount.S
- arch/riscv64/plthook.S
- cmds/info.c
- cmds/record.c
- uftrace.c
- utils/arch.h
- utils/compiler.h
- utils/dwarf.c
- utils/regs.c
This pull request is a porting effort to enable successful, error-free builds on the RISC-V 64-bit architecture environment and to support tracing using the `mcount` function.
This feature has also been tested on the `VisionFive2` RISC-V board. 
The following features are currently supported in the PR.
- Basic mcount Tracing
- Argument Handling
The following features are not yet supported
- PLT hooking (this feature is in progress)
- Dynamic tracing
<br>
This PR was born out of this issue.
- https://github.com/namhyung/uftrace/issues/1503
------
This work has been discussed previously with @honggyukim in the PR link below.
- https://github.com/honggyukim/uftrace/pull/18
The Argument Handling feature was split into the PRs below and then merged back together.
- …
> arch/riscv64: Add basic mcount tracing support for RISC-V 64bit

- cmds/replay.c
The full demangler __cxa_demangle() may or may not add parentheses at the end of symbol names, so NEEDS_PAREN was introduced.
Previously, NEEDS_PAREN was set when the last character of the symbol name was not ')'. Now, it is also set when the last few characters are "operator()", to handle functors and lambdas in C++.
Related to #1827
> replay: Revise the logic of setting NEEDS_PAREN to correctly add parentheses

- arch/aarch64/mcount-dynamic.c
- arch/i386/mcount-dynamic.c
- arch/x86_64/mcount-dynamic.c
- cmds/record.c
- utils/tracefs.c
EM_RISCV, TRACEFS_MAGIC, MAP_FIXED_NOREPLACE macros are added to fix build errors
since they are not declared in the low kernel version.
The error messages are below:
```sh
uftrace/cmds/record.c:1592:75: error: ‘EM_RISCV’ undeclared (first use in this function)
uint16_t supported_machines[] = { EM_X86_64, EM_ARM, EM_AARCH64, EM_386, EM_RISCV };
^
uftrace/utils/tracefs.c:26:53: error: ‘TRACEFS_MAGIC’ undeclared (first use in this function)
if (!statfs(TRACEFS_DIR_PATH, &fs) && fs.f_type == TRACEFS_MAGIC) {
^
uftrace/arch/x86_64/mcount-dynamic.c:46:6: error: ‘MAP_FIXED_NOREPLACE’ undeclared (first use in this function)
MAP_FIXED_NOREPLACE | MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
^
```
Fixed: https://github.com/namhyung/uftrace/issues/1834
Signed-off-by: Michelle Jin <shjy180909@gmail.com>
> build: Fix build errors due to low kernel version

- python/trace-python.c
- utils/script-python.h
Python.h should not be on the first line.
Python.h needs to be rearranged.
issue: #1648
Signed-off-by: Jin Jang <keepgoingxxx@gmail.com>
> build: Fix compile warning message

- Makefile
Since uftrace has many targets and build options in make, this commit adds make's help messages to organize them.
Closes: #1837
> uftrace: Add help message for make

- misc/wget-pr.sh
I improved the recently added wget-pr.sh script.
It's really useful to get the patch file by pull request number. However, some systems (e.g. CentOS 7 or 8, fedora 33 or 34) do not provide wget unless install manually.
This commit improves the script to get the patch with curl if wget is not available. This also renames the file to a more appropriate name.
> misc: Enhance and rename wget-pr script

- libmcount/wrap.c
When specifying estimate_return, the return address is not hijacked. This patch ensures that mcount_rstack_reset_exception() is not called in this case, to avoid recording incorrect end times.
Before:
I got an inverted time bug in estimate_return mode (it only occurs when using dynamic tracing). 
I found that `mcount_rstack_reset_exception()` was called unexpectedly, which sets the end time using `mcount_gettime()`, but the end time should be estimated by `mcount_rstack_inject_return()`. 
This PR should fix this small problem.
```shell
$ clang++ tests/s-exception3.cpp -o test/exp
$ uftrace -P. -e test/exp
[117574] | main() {
[117574] |   A::A() {
[117574] |     foo1() {
[117574] |       foo2() {
[117574] |         foo4() {
5.050 us [117574] |           C::C();
[117574] |           foo5() …
```
> mcount: Restore/reset rstack only when the return address is hijacked

- README.md
Fix a duplicated "with" and even with it fixed, the sentence was not clear and easy to read.
Therefore, split the description of tracing possibilities into two:
- One for dynamic tracing, mentioning or `-P.`
- one for tracing by using instrumentation.
While at it, I also recoginzed that the part regarding `-fxray-instrument` can be made clearer and that the readability of the options by adding a space after `-f` (even tough we'd normally omit the space of course), when so many of the are given in one long sentence.
> README.md: Fix duplicated "with"

- README.md
I think this is the first PR where the description turned out to be much longer than the diff in the "Files changed" view is. ;-)
- This it's not scary at all, only a few characters here and there!
- I just wanted to ensure you that it's not me/my preference, these are fixes for warnings generated by a tool.
These issues were found by using these LanguageTool extensions for VS Code:
- [LTeX: Grammar/Spell Checker Using LanguageTool with Support for LATEX, Markdown, and Others](https://marketplace.visualstudio.com/items?itemName=valentjn.vscode-ltex)
- [Offline Language Provider for English](https://marketplace.visualstudio.com/items?itemName=adamvoss.vscode-languagetool-en) for [LanguageTool for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=adamvoss.vscode-languag …
> doc: Fix typos and improve language in README.md

- utils/debug.c
- utils/kernel.c
- utils/perf.c
uftrace: Fix dead store warnings found by infer
This patch fixes some dead store warnings found by a static analysis
tool, called infer[1].
The warning messages are as follows.
```
$ cd /path/to/uftrace
$ infer run --force-integration make
...
utils/debug.c:386: error: Dead Store
The value written to `&percent` (type `double`) is never used.
384. void print_diff_percent(uint64_t base_nsec, uint64_t pair_nsec)
385. {
386. 	double percent = 999.99;
^
utils/debug.c:387: error: Dead Store
The value written to `&sc` is never used.
385. {
386.  double percent = 999.99;
387.  const char *sc = get_color(COLOR_CODE_NORMAL);
^
388.  const char *ec = get_color(COLOR_CODE_RESET);
389.
utils/kernel.c:57: error: Dead Store
The value written to `&ret` is never used.
55. {
56.   struct kfilter *pos, …
```
> uftrace: Fix dead store warnings found by infer

- utils/kernel-parser.c
This patch fix warning on compile time with including unistd.h header file.
```
utils/kernel-parser.c:151:9:
warning: implicit declaration of function 'close';
did you mean 'pclose'?
[-Wimplicit-function-declaration]
151 |         close(kp->fds[cpu]);
|         ^~~~~
|         pclose
```
Fixed: #1859
> utils: Fix warnings implicit declaration of function 'close'

- libmcount/mcount.c
Since the following commit removed setting UFTRACE_PIPE, there is no need to read the env from libmcount side.
fa064544 record: Get rid of UFTRACE_PIPE env variable
This patch also removes the local variable "pipefd_str" related code.
> libmcount: Remove UFTRACE_PIPE related code

- utils/shmem.h
- utils/socket.h
Each header has to be buildable independently, but some headers fail as follows.
Before:
```
$ find -name "*\.h" | grep -v prototypes.h | xargs gcc -I. -I./arch/$(uname -m)
./utils/socket.h:8:27: warning: ‘struct sockaddr_un’ declared inside parameter
list will not be visible outside of this definition or declaration
8 | void socket_unlink(struct sockaddr_un *addr);
|                           ^~~~~~~~~~~
...
./utils/socket.h:15:48: warning: ‘struct uftrace_msg’ declared inside parameter
list will not be visible outside of this definition or declaration
15 | int agent_message_read_response(int fd, struct uftrace_msg *response);
|                                                ^~~~~~~~~~~
./utils/shmem.h:4:53: error: unknown type name ‘mode_t’
4 | int uftrace_shmem_open(const char *name, …
```
> utils: Fix incorrect header includes

- utils/debug.c
- utils/utils.h
We don't have much information when uftrace hits pr_err, but it just shows the given error message.
Instead, it'd be useful if we can attach gdb inside pr_err so that we can see its backtrace and so on.
This patch adds DTRAP, which enables TRAP only when debug mode is on.
We can add DTRAP just before pr_err goes to exit().
> utils: Add DTRAP macro and use it in pr_err

- Makefile
- NEWS
I think it's time for a new release. :)  We have a good set of new features and bug fixes including:
* basic RISC-V (RV64G) architecture support
* fixes for a couple of kernel tracing bugs
* better support for binaries built with -fno-plt
* ignoring unpaired __cyg_profile_func_exit() (probably due to compiler bugs)
* various documentation and test updates
Maybe I can wait for a few more days for last minute changes and fixes.  Please test the code and let me know if it works well for you.  Thanks!
> New release v0.15

- check-deps/Makefile
- check-deps/__cc_has_mno_sse2.c
Fix issue of uftrace build fail on rhel 7.9
System information
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```
Build error:
```sh
[uftrace]$ ./configure
...         prefix: /usr/local
...         libelf: [ on  ] - more flexible ELF data handling
...          libdw: [ on  ] …
```
> build: Fix build failure on RHEL 7

- libmcount/dynamic.c
The musl libc defines PAGE_SIZE macro and shows warning like this:
/usr/src/uftrace/libmcount/dynamic.c:43: warning: "PAGE_SIZE" redefined
43 | #define PAGE_SIZE 4096
|
In file included from /usr/include/fortify/stdlib.h:30,
from /usr/src/uftrace/libmcount/dynamic.h:5,
from /usr/src/uftrace/libmcount/dynamic.c:24:
/usr/include/limits.h:97: note: this is the location of the previous definition
97 | #define PAGE_SIZE PAGESIZE
> mcount: Fix a compiler warning on PAGE_SIZE

- python/trace-python.c
by changing the wrong logic in update_dbg_info
backtrace(need set follow-fork-mode child)
```
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:457
457	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:457
#1  0x00007ffff7c8de6c in __GI__IO_default_xsputn (n=<optimized out>, data=<optimized out>, f=<optimized out>) at ./libio/genops.c:386
#2  __GI__IO_default_xsputn (f=0x7fffffff7a10, data=<optimized out>, n=174) at ./libio/genops.c:370
#3  0x00007ffff7c74918 in outstring_func (done=0, length=174, 
string=0x55555c1634d0 "F: 723bd tensorflow._api.v2.experimental.numpy.random.<module>\nL: 1 …
```
> fix: #1858 by changing the wrong logic in update_dbg_info

- .github/workflows/nightly-test.yml
- .github/workflows/on-demand-test.yml
- .github/workflows/pr-test.yml
- .github/workflows/push-test.yml
by changing actions/checkout from v3 to v4
actions/setup-python from v4 to v5
warning on GitHub Acitions
before:
after:
> ci: Fix ci warning on GitHub Acitons

- doc/uftrace.html
It'd be better to have more practical python tracing example in slide document so this patch adds tensorflow and keras tracing example.
The example python program can be found at [1].
[1] https://github.com/keras-team/keras-io/blob/master/examples/vision/mnist_convnet.py
> slide: Add tensorflow and keras tracing example

- python/trace-python.c
The uftrace_python_symbol keeps code PyObject in rb tree so GC can not run correctly in the trace process. Fixed the problem by dropping it.
Fixed: #1886
> python: Fix GC isn't working correctly.

- utils/script-python.h
Fix compiler warnings when using python2.7
```sh
/usr/include/python2.7/pyconfig-64.h:1191:0: error: "_POSIX_C_SOURCE" redefined [-Werror]
#define _POSIX_C_SOURCE 200112L
^
In file included from /usr/include/inttypes.h:25:0,
from /home/uftrace/libmcount/mcount.h:12,
from /home/uftrace/utils/script.h:11,
from /home/uftrace/utils/script.c:13:
/usr/include/features.h:168:0: note: this is the location of the previous definition
^
In file included from /usr/include/python2.7/pyconfig.h:6:0,
from /usr/include/python2.7/Python.h:8,
from /home/uftrace/utils/script-python.h:18,
from /home/uftrace/utils/script.h:13,
from /home/uftrace/utils/script.c:13:
/usr/include/python2.7/pyconfig-64.h:1213:0: error: "_XOPEN_SOURCE" redefined [-Werror]
#define _XOPEN_SOURCE 600
^
In file included from …
```
> build: Fix compiler warnings

- tests/runtest.py
- tests/t230_graph_task.py
Fixes the following `SyntaxWarning:` from the Python Interpreter:
```sh
uftrace/tests/./runtest.py:328: SyntaxWarning: invalid escape sequence '\['
pid_patt = re.compile('[^[]+\[ *(\d+)\] |')
uftrace/tests/./runtest.py:496: SyntaxWarning: invalid escape sequence '\|'
+ '-->\|(?P<call_num>\d+)\|\s+(?P<end_depth>\d+)_(?P<end_id>\d+)\[\"(?P<end_name>\S+)\"\];', ln)
uftrace/tests/t230_graph_task.py:39: SyntaxWarning: invalid escape sequence '\['
line = re.sub('\[\d+\]', 'TID', line)
```
> Fix Python SyntaxWarning on invalid escape sequence in the tests scripts

- utils/symbol-libelf.c
The current return value check after dwfl_module_getdwarf shows too many repeated debug messages as follows.
```
$ sudo apt install vulkan-tools
$ uftrace record -P. -la -v vkcube
uftrace: running uftrace v0.15.2-32-g1919a ( x86_64 dwarf python3 luajit tui perf sched dynamic kernel )
uftrace: checking binary /usr/bin/vkcube
uftrace: removing uftrace.data.old directory
uftrace: using /home/honggyu/usr/lib/uftrace/libmcount.so library for tracing
uftrace: creating 2 thread(s) for recording
mcount: initializing mcount library
symbol: cannot find debug file: No DWARF information found
symbol: cannot find debug file: No DWARF information found
(... repeated about 40 times ...)
symbol: cannot find debug file: No DWARF information found
symbol: cannot find debug file: No DWARF information found …
```
> utils: Lower the debug level after dwfl_module_getdwarf

- libmcount/wrap.c
If dlopen is called with (null) for the filename, it does nothing so it's not useful to print a debug message for such case.
But the current implementation shows too many message as follows.
```
$ sudo apt install vulkan-tools
$ uftrace record -P. -la -v vkcube
...
wrap: dlopen is called for 'libVkLayer_MESA_device_select.so'
wrap: dlopen is called for '(null)'
wrap: dlopen is called for '(null)'
(... repeated 18 more times ...)
mcount: shmem_finish: tid: 10312 seqnum = 2 curr = 0, nr_buf = 2 max_buf = 2
```
This patch is to avoid printing these unhelpful messages.
> wrap: Do not print "dlopen is called for '(null)'"

- Makefile
- NEWS
I'm preparing a new release with the following changes:
* separate debug file support
* add a new 'o' format for octal values
* add {total,self}-stdv field to uftrace report
* improve Python tracing by not bothering GC
* and a lot of bug fixes
Please check out the code and test it on various platforms!
> New Release v0.16

- libmcount/wrap.c
According [Advanced Programming in the UNIX® Environment,](https://learning.oreilly.com/library/view/advanced-programming-in/9780321638014/), lots of daemon program will close all file descriptors to detach from the daemon startup environment to prevent it from interaction with terminal status changes. 
uftrace will get into trouble when it has been used to trace this type of programs.
Sample programs:
```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
int fact(int n) {
if ( n == 0 ) {
return 1;
}
return n * fact(n-1);
}
int test1(int n)
{
FILE *fp = fopen("/dev/tty", "a+");
fprintf(fp, "%d! = %d\n", n, fact(n));
fclose(fp);
return 0;
}
void closex()
{
int i;
int max = sysconf(_SC_OPEN_MAX);
for(i = max; i > 2; i -- ) {
close(i);
}
}
int main(int argc, char *argv[]) {
int i; …
```
> make uftrace more friendly to daemon programs

- cmds/dump.c
- cmds/info.c
- uftrace.h
In some cases, there is a requirement to get the time offset between UTC time and our timestamp from the given clock source, CLOCK_MONOTONIC by default.
This patch provides an additional info to provide UTC time offset in the output of uftrace info.
This number can be used to make time adjustment easier for external tools such as tracecompass[1].
Closes: #1916
[1] https://eclipse.dev/tracecompass
Requested-by: Matthew Khouzam <matthew.khouzam@gmail.com>
> info: Add utc_offset info for external usage

- cmds/info.c
- libmcount/record.c
- libmcount/wrap.c
- utils/kernel.c
- utils/utils.h
Align argument for calloc() call in some code and macro in utils.h file.
This patch remove warning on #1933 
```
/home/paran/uftrace/cmds/graph.c:213:53: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
213 |         struct session_graph *graph = xzalloc(sizeof(*graph));
|                                                     ^
/home/paran/uftrace/utils/utils.h:193:38: note: in definition of macro ‘xzalloc’
193 |                 void *__ptr = calloc(sz, 1);                                                       \
|                                      ^~
/home/paran/uftrace/cmds/graph.c:213:53: note: earlier argument should specify number of elements, later size of each element
213 |         struct …
```
> uftrace: Align exact argument on calloc

- misc/demangler.c
This commit adds support for the -h and --help options to display usage of misc/demangler like follows.
```
$ misc/demangler -h
demangler v0.11-683-g804a
OPTION:
--simple           Use internal simple demangler (default)
--full             Use libstdc++ demangler
--no               Do not use demangler
-v, --verbose          Be verbose
-h, --help             Display this help and exit
```
An end marker has also been added to the demangler_options array for proper termination and prevent potential undefined behavior.
Fixed: #1939
> misc: Add -h/--help options and end marker to demangler_options

- uftrace.c
uftrace: Add sub-command specific help
i redirect subcommand help to man pages just like git and perf do.
```c
case -3:
+		if (opts.mode) {
+			execlp("man", "man", "uftrace", argv[1], (char *)NULL);
+			abort();
+		}
if (opts.use_pager)
start_pager(setup_pager());
pr_out(uftrace_usage);
pr_out(uftrace_help);
wait_for_pager();
ret = 0;
goto cleanup;
}
```
Fixed: #1316
Signed-off-by: ParkSeungHyeok <tmdgur1324@naver.com>
> uftrace: Add sub-command specific help

- misc/checkout-pr.sh
It takes some time to get the patches for review but it'd be useful to have a script for that.
The script accepts only a parameter to get the pull request ID. It fetches from the source repo and checkouts to the fetched head.
> misc: Add checkout-pr.sh script for easier checkout

- cmds/record.c
This patch to fix crash when the root is not existed, due to some embed devices maybe not have it.
source:
```c
static void unlink_shmem_list(void)
{
...
list_for_each_entry_safe(sl, tmp, &shmem_need_unlink, list) {
...
struct dirent **shmem_bufs;
sscanf(sl->id, "/uftrace-%[^-]-%*d-%*d", shmem_session);
...
free(shmem_bufs);
...
}
}
```
My SOC do not have `/dev/shm/` and `shmem_bufs`'s value has not initialized, so `scandir()` not flush `shmem_bufs` and it has bad address, then bad thing happened:
```shell
/userdata # ./uftrace record -vv ./prog_test
...
uftrace: flushing /uftrace-bd6de237f8a0b25b-1383-000
uftrace: unlink for session: bd6de237f8a0b25b
munmap_chunk(): invalid pointer
Aborted (core dumped)
```
So I add `access()` to fix it:
```c
static void unlink_shmem_list(void)
{
... …
```
> record: Fix crash when the root is not existed

- Makefile
- NEWS
I'd like to release a new version (v0.17).  Please check out the current version and run the test on your environment.
This is a small release including the following changes.
* global variable watchpoint support
* argument/return value and srcline support for dlopen libraries
* show man page of current command when -h option is used
> Release v0.17

- arch/x86_64/symbol.c
The `struct uftrace_elf_iter sec_iter` is being used without initialization, and only specific values are being copied. This can lead to unexpected behavior in the copied other iters.
```
SUMMARY: MemorySanitizer: use-of-uninitialized-value
arch/x86_64/symbol.c:33:14 in arch_load_dynsymtab_noplt
Exiting
==2474640==WARNING: MemorySanitizer: use-of-uninitialized-value ==2474525==WARNING: MemorySanitizer: use-of-uninitialized-value ==2474780==WARNING: MemorySanitizer: use-of-uninitialized-value
0 0x55985b0a1f46 in arch_load_dynsymtab_noplt arch/x86_64/symbol.c:33
1 0x55985b0792f7 in load_dynsymtab utils/symbol.c:726:2
2 0x55985b05bb30 in load_module_symbol utils/symbol.c:1111:2
3 0x55985b05a3fe in load_module_symtab utils/symbol.c:1144:2
4 0x55985b05db5f in load_module_symtabs …
```
> symbol: Fix uninitialized 'sec_iter' in the 'arch_load_dynsymtab_noplt'

- tests/t295_graph_field_total.py
- tests/t296_graph_field_self.py
Previously, t295 and t296 excluded system_initialize_function
by filtering its name in the test logic.
This change moves that logic to use the Filter option instead,
making the exclusion cleaner and more consistent.
```
========== FUNCTION CALL GRAPH ==========
TOTAL AVG   TOTAL MAX   TOTAL MIN   FUNCTION
10.758 ms   10.758 ms   10.758 ms : (1) t-sort
10.758 ms   10.758 ms   10.758 ms : (1) main
139.750 us  262.084 us   17.416 us :  +-(2) foo
10.305 us   31.875 us    5.083 us :  | (6) loop
:  |
10.357 ms   10.357 ms   10.357 ms :  +-(1) bar
10.172 ms   10.172 ms   10.172 ms :    (1) usleep
```
```
$ make -j 8 test TESTARG=graph_field
Running 0 test cases
======================
unit test stats
====================
0 ran successfully
0 failed
0 skipped
0 signal caught
0 unknown result
TEST …
```
> test: exclude system_initialize_function in t295 and t296 using filter option

- cmds/record.c
- libmcount/record.c
- python/trace-python.c
- utils/utils.h
The shmem directory under TMPDIR is used to store named pipe for communication.  Since the named pipe is created under the created 'uftrace' directory, the 'uftrace' directory has to have an exec permission so that named pipe files can be created inside it.
This patch fixes the problem by adding exec permission for 'uftrace' directory creation.
Before:
```
$ uftrace record --force pwd
mcount: /data/data/com.termux/files/home/uftrace/libmcount/record.c:81:prepare_shmem_buffer
ERROR: mmap shmem buffer: Permission denied
```
After:
```
$ uftrace record --force pwd
/data/data/com.termux/files/home/uftrace
```
> record: Add shmem directory to exec permission

- tests/s-exp-mixed.c
- tests/s-thread.c
Clang optimization can inline some functions unexpectedly even when -fno-inline is given.  This happenes when clang decides some simple functions as a target of constant folding and it ignores -fno-inline as a result for s-thread.c example.
The same issue was also previously fixed at the commmit below.
f2ac933e tests: Fix 051 return test when using clang
One more similar fix is that `mixed_sub()` of s-exp-mixed.c is renamed as `mixed_sub.specialized.1()` by clang optimization.
To handle those issues, this patch disables clang optimization for some functions explicitly.
Before:
```
$ ./runtest.py -c clang '003|049|176|244|084|085'
Compiler                  clang
Runtime test case         pg             finstrument-fu fpatchable-fun
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 …
```
> tests: Fix s-thread.c and s-exp-mixed.c tests from clang

- Makefile
- NEWS
Hi all, I'm preparing a new release (v0.18) with these changes:
* filter condition support
* support LTO build
* add avg/max/min fields to uftrace graph
* many updates on the test
* a fix for Go programs built with gccgo
Please take a look and play with it.  It'd be great if you could report how it goes on your platform.
> New Release v0.18

- scripts/func-percentile.py
In #1982, I suggested adding a feature to output function execution time as a percentile to the uftrace report. Although it's been a long time, it hasn't been implemented. As an alternative, I'm requesting to add a script that provides this functionality.
NOTE: Percentiles can be easily calculated using NumPy's `percentile()`. However, I implemented it myself to reduce dependencies. The calculation uses linear interpolation, matching NumPy's default method.
> script: Add func-percentile.py
